### ISSUE TITLE
Implement Processing 3 pull requests

### ISSUE THREAD

**Issue by micycle1** [benfry/processing4#115]
There's currently quite a lot of unmerged (and unclosed) PRs for Processing 3. Many of the requests are years old, and have zero acknowledgment from repo owners so it seems quite clear that they'll never make it into Processing 3 and remain open indefinitely.

So, my suggestion is that Processing 4 should look to implement the best of these PRs -- ones like [make offscreen PGraphicsFX2D work](https://github.com/processing/processing/pull/4698) for example, rather than letting useful work (that's been done already) go to waste.

**Comment by benfry** [comment]
I don't have infinite time, and posts like this aren't helpful.
