### ISSUE TITLE
Language Server for VS Code and others

### ISSUE THREAD

**Issue by austince** [benfry/processing4#117]
## Description

I'm wondering if there has been any work to create a Language Server for Processing yet. It would be very useful for people who would like to use the language outside of the Processing IDE like [this project for VS Code](https://github.com/TobiahZ/processing-vscode). I'm not sure if I'll have time I'd love to help try to get it started if it hasn't been before!

**Comment by pr1metine** [comment]
I am working on a LS. It's in a very early stage though and it can merely format PDE files.

**Comment by sampottinger** [comment]
That's awesome @pr1metine! Obviously I'm sure you are aware but Processing 4 does have a new preprocessor with java 11 syntax support. LMK if you need help wading into any of that!

**Comment by pr1metine** [comment]
Thank you, @sampottinger ! I'd be happy for your help especially on the Preprocessor and Linting. [This](https://github.com/pr1metine/ls4pde) is what I've been working on so far.

For further questions hit me up in my [Twitter DMs](https://twitter.com/pr1metine).

**Comment by Cyfine** [comment]
I would like to see an official language support VS Code plugin for Processing in the future.

**Comment by benfry** [comment]
Me too! Just need someone to do the work.

**Comment by kgtkr** [comment]
I started this work a few days ago. It is implemented based on the code of Processing Development Environment. This is very unstable, but I have implemented formatters and error reporting.

![image](https://user-images.githubusercontent.com/17868838/139575101-16460199-21fd-497a-a0c1-5b616b70884f.png)


https://github.com/kgtkr/processing-language-server
https://github.com/kgtkr/processing-language-server-vscode

postscript(2021/11/01)

![image](https://user-images.githubusercontent.com/17868838/139665455-6c6eeada-a08f-4936-86be-0aaf22bc2198.png)

**Comment by SableRaf** [comment]
Bumping this issue now that Processing 4.0 has been released. 

This would be a great time to revive community efforts towards a Language Server for Processing!

_For anyone interested to learn about the Language Server Protocol (and maybe help with development) here are some useful references:_
- https://microsoft.github.io/language-server-protocol/
- https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Comment by SableRaf** [comment]
Note: there was also some work done by @SyamSundarKirubakaran in 2021
The code can be found here: https://github.com/processing-language-server/LS4P and [a conversation about it in the Processing forum](https://discourse.processing.org/t/processing-language-server-gsoc19/9554).

**Comment by kgtkr** [comment]
I was able to easily implement lsp by using the source code of the integrated editor.
However, this is easier to maintain if integrated into processing
Do you have a plan? i might be able to implement

**Comment by SableRaf** [comment]
Hi @kgtkr 👋 Could you describe what you specifically need in order to integrate the LSP in Processing ?

**Comment by kgtkr** [comment]
Once the prototype is complete, please do a code review. Please wait until my work is finished.

**Comment by kgtkr** [comment]
@SableRaf #564

**Comment by benfry** [comment]
Initial work from @kgtkr now incorporated for Processing 4.1. I'm closing this issue since the base support is now present, and we can file separate/more specific issues as needed for adding other enhancements. 

For instance, we don't have an official _client_ yet, but hopefully the community can help fill that hole for various platforms for at least the time being.
