### ISSUE TITLE
JSSC binaries for Windows appear to be macOS files

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#119]
…or at least `codesign` thinks so. Is it possible that the cross-compilation for these libs wasn't set quite right? They're `.dylib` files after all.

For that matter, we can also nix the windows_32 versions.

**Comment by sampottinger** [comment]
Hey there! Checking on this now. Just for housekeeping, the original issue is https://github.com/processing/processing4/issues/71.

**Comment by sampottinger** [comment]
I checked both `master` here and the integration branch over at https://github.com/sampottinger/processing4/. The serial library is loaded and runs correctly on Windows. Apologies... I'm probably missing something obvious but I also checked and the file here does seem to be a dll (https://github.com/processing/processing4/tree/master/java/libraries/serial/library/windows64).

```
$ git pull
Already up to date.

$ find ./ -name *jssc*
.//java/libraries/serial/library/linux-armv6hf/libjssc.so
.//java/libraries/serial/library/linux-arm64/libjssc.so
.//java/libraries/serial/library/jssc.txt
.//java/libraries/serial/library/windows32/jssc.dll
.//java/libraries/serial/library/jssc.jar
.//java/libraries/serial/library/linux32/libjssc.so
.//java/libraries/serial/library/macosx/libjssc.jnilib
.//java/libraries/serial/library/windows64/jssc.dll
.//java/libraries/serial/library/linux64/libjssc.so
```

<img width="720" alt="Screen Shot 2020-08-16 at 7 54 43 PM" src="https://user-images.githubusercontent.com/110391/90353154-5f2faf00-dffa-11ea-8068-792c38d27f3f.png">

**Comment by sampottinger** [comment]
LMK how you want to proceed @benfry. Per your other request, removal of win32 at #120. Thanks!

**Comment by benfry** [comment]
It came up because notarization was complaining about these binaries inside jssc.jar:

```
Processing.app/Contents/Java/modes/java/libraries/serial/library/jssc.jar/natives/windows_32/libjssc.dylib
Processing.app/Contents/Java/modes/java/libraries/serial/library/jssc.jar/natives/windows_64/libjssc.dylib
```

It looks like there are also `.dll` files in the same directories, so things should function, but in the meantime I have the those `.dylib` entries being removed manually as part of dist as of https://github.com/processing/processing4/commit/ebe2a93987ac3df8dacce4dd48431787c99d438b.

I'll hold on #120 until you have a sense of what's going on; I just didn't want to do anything more invasive.

**Comment by sampottinger** [comment]
Oh! My apologies ... thank you for catching that. I will see what’s going on in there. 👀

**Comment by benfry** [comment]
@sampottinger did you have a chance to look into this one? Hoping it's just something simple, but didn't want to delete things willy-nilly.
