### ISSUE TITLE
the word var return "syntax error"

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#131]
# Description
Cool to test this last version, and unfortunatly I found a little problem !
In the last Processing version 2 alpha, when the name `var`is use that's return a `syntax error`.
`var' is now a key word reserved ? if it's the case maybe the message must be change.

## Steps to Reproduce
```
float var = 0.0f;
// same behavior for all type
```
## Your Environment

 

* Processing version: 4.0 a2
* Operating System and OS version: Mojave 10.14.6

<img width="257" alt="Capture d’écran 2020-09-16 à 09 33 11" src="https://user-images.githubusercontent.com/3332269/93306340-01140880-f800-11ea-912b-4a067bbfa65b.png">

**Comment by dzaima** [comment]
In Java 11, `var` is sort-of reserved. Technically, in Java itself it's only a reserved class name (so should be fine as a variable name), but Processing's preprocessor is treating it [as its own token](https://github.com/processing/processing4/blob/06bf5566e8b0404ce08f2b387ef87f6d407f1887/java/src/processing/mode/java/preproc/JavaLexer.g4#L94), and so doesn't expect it in other places. Making prettier errors for syntactical problems is hard with ANTLR.

**Comment by knupel** [comment]
ok , thx for your light. But in the previous build ant of Processing 4 with Java 11. I didn't have this problem, it's why i'm a little surprise !  So If I understand now `var` is like `auto` in c++ ? and we can use with any type ?

**Comment by dzaima** [comment]
Yes, it's like the C++ `auto`. The preprocessor overhaul that added Java 11 syntax was done at at [October 6th, 2019](https://github.com/processing/processing4/commit/ee299ef935e257f78f633384aec1784431cef9c5), so whenever it worked must be before that.

I believe it should be possible to mostly trivially remove the `VAR` token being special, but I haven't looked into it.

**Comment by knupel** [comment]
I prefere follow the rule, I just change all my word `var`to `arg`.  So I think I can close this issues.  Thx !
