### ISSUE TITLE
Fix “autogenerated by Processing preprocessor” text

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#135]
Seeing this in the generated `.java` code; needs to be updated:

    /* autogenerated by Processing preprocessor v3.0.0 on 2020-09-15 */

Not sure where it comes from, and 3.0.0 is confusing; should instead probably use `processing.app.Base.REVISION` instead.

**Comment by benfry** [comment]
Also looks like the rewritten `size()` command that's generated doesn't follow our guidelines for whitespace (i.e. before parens, etc) per the rest of the examples or our online guidelines in the wiki.

**Comment by jeremydouglass** [comment]
Here it is:

https://github.com/processing/processing4/blob/6d8fa349fa01fd522c1ac0ddac2ae64736eaa1fb/java/src/processing/mode/java/preproc/PdeParseTreeListener.java#L909

**Comment by benfry** [comment]
Thanks, I'll open another issue for the spacing issue.
