### ISSUE TITLE
Odd spacing in preprocessor-generated code

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#136]
Looks like the rewritten size() command that's generated by the preprocessor doesn't follow our guidelines for whitespace (i.e. before parens, etc) per the rest of the examples or our online guidelines in the wiki. In the past, I believe we just grabbed the `size()` command and dropped it back in as-is, but at a minimum it should have a single space after each parameter. Not sure if there are other things like this from the preproc as well.

**Comment by sampottinger** [comment]
Ah dang sorry just saw this. Quick fix and my bad... I don't think "rewrites" like this happen elsewhere. Fixed in https://github.com/processing/processing4/pull/138

**Comment by benfry** [comment]
Great; thanks!
