### ISSUE TITLE
Option+Backspace on Mac does not delete word left from cursor

### ISSUE THREAD

**Issue by companje** [benfry/processing4#140]
## Description

In Processing 4 alpha the Option+Backspace on Mac OSX does not delete the word left of the cursor like it used to do in the Processing 3 IDE.

## Steps to Reproduce
While editing press Option+Backspace on Mac keyboard. It should delete the word left of the cursor. It does nothing in my case.

## Your Environment

 

* Processing version: 4.0a2
* Operating System and OS version: Mac OSX Catalina 10.15.5

**Comment by benfry** [comment]
You mean shift, not option, right? 

If so, you might just be dealing with a clean preferences file, where that's turned off by default. Open Home > Library > Processing > preferences.txt and change:

    editor.keys.shift_backspace_is_delete = false

to 

    editor.keys.shift_backspace_is_delete = true

**Comment by companje** [comment]
I really meant Option+Backspace instead of Shift. Also Cmd+Option+ArrowKeys to toggle between tabs was not working.
But somehow - when I tried to make a screengrab of it - it now suddenly works. I will try to reproduce the problem since I'm quite sure there was unexpected behaviour here. I will re-open the issue when the problem re-occurs.

**Comment by companje** [comment]
Somehow it works when the IDE starts, but after a while (and I'm still investigating when exactly) Option+Backspace and Cmd+Option+ArrowKeys stop working.

**Comment by benfry** [comment]
Sorry, missed that the issue title included “word.” Let me know if you learn anything…
