### ISSUE TITLE
`StringIndexOutOfBoundsException` on PApplet initialisation when using EA versions of Java

### ISSUE THREAD

**Issue by lenrik1589** [benfry/processing4#142]
## Expected Behavior

you can make a PApplet with Java 11+.

## Current Behavior

On early access or preview versions creating `PApplet` fails with `StringIndexOutOfBoundsException` "index -1 out of bounds for length 0";

## Steps to Reproduce

1.get yourself a copy of `processing.core` and Java 15+ (early access version of java);
2.create a class, extending `processing.core.PApplet` (normal sketch);
3.try to run this sketch.

## Your Environment

 

* Processing version: 4.0a using Intellij IDEA Community Edition
* Operating System and OS version: Ubuntu 20.04 with kde plasma
* Other information: Java 15/16

## Possible Causes / Solutions

probably have default value for `javaVersion` and `javaPlatform` in case `System.getProperty("java.version")` returns something not expected

**Comment by lenrik1589** [comment]
after updating all the libraries to those, provided in 4.2a (on Java 14), `PGraphics2D` does not implement `getNative` (just returns null) so PSurfaceJOGL.setCursor(PImage image, int hotspotX, int hotspotY)` just throws NPE

**Comment by benfry** [comment]
Ok, though this is going to be a low priority; only Java 11, the LTS, is supported.

**Comment by lenrik1589** [comment]
Another solution i can think of would be to catch this error and display a warning, like "you are currently using unsupported version of java, consider switching to java 11" and probably also a link to download location.

**Comment by benfry** [comment]
Are you sure you're using the version of the “core” classes from this repo? The 3.x code will definitely do this, but I don't see anything obvious for why 4.x would be failing. 

What JDK is this using?

**Comment by benfry** [comment]
No response; closing.
