### ISSUE TITLE
NullPointerException in getSystemZoom() on startup in alpha 2

### ISSUE THREAD

**Issue by makakken** [benfry/processing4#143]
## Description
When i attach a screen to my macbook, and close the macbook (so only second screen is applied) Processing 4 is crashing on startup. Maybe it's related to #57?

## Expected Behavior
Processing4 simply starting on second screen.

## Current Behavior
After start of Processing, it's shortly appearing in the MacOS-Dock, and then silently crashing and not starting.

## Steps to Reproduce>
1. Attach external screen to macbook pro.
2. close macbook ( MacOS Catalina 10.15.7)
3. Start Processing (It crashes)

## Your Environment
* Processing version: Processing 4.0a2
* Operating System and OS version: MacOS Catalina 10.15.7
* Other information: MacBookAir 13" 2020

## Possible Causes / Solutions
Maybe there is something wrong with the window manager? When i open the primary display (MacBook Display) and have attached the second screen, it works.

**Comment by benfry** [comment]
Nuts, was hoping this newer Java would *help* with some of these second display issues.

Probably a Java bug, but can you please try the following:

+ Open a Terminal window, and `cd` to the directory that contains Processing.app. For instance, `cd /Applications` if you have it in your Applications folder.
+ Type `./Processing.app/Contents/MacOS/Processing` to start the software.
+ See what's printed in the Terminal window when it starts up and crashes, then copy and paste that here.

Thanks!

**Comment by makakken** [comment]
Terminal Output:
```
2020-10-11 18:21:44.824 Processing[25798:1818013] int launch(char *, int, char **) Launchpath: /Applications/Processing.app/Contents/PlugIns/jdk-11.0.8+10/Contents/Home/lib/jli/libjli.dylib
2020-10-11 18:21:44.865 Processing[25798:1818019] int launch(char *, int, char **) Launchpath: /Applications/Processing.app/Contents/PlugIns/jdk-11.0.8+10/Contents/Home/lib/jli/libjli.dylib
java.lang.NullPointerException
	at processing.app.Platform.getSystemZoom(Platform.java:416)
	at processing.app.ui.Toolkit.highResImages(Toolkit.java:913)
	at processing.app.BaseSplash.main(BaseSplash.java:12)
```

**Comment by benfry** [comment]
Ahh… That's actually good news; that's our bug. In fact, I'm a little surprised the app was working at all for folks using anything but retina displays on macOS machines. 

Added a workaround for 4.0a3, but has revealed a new bug with #145.
