### ISSUE TITLE
null pointer exception when loading image in settings() Processing 4.0a2

### ISSUE THREAD

**Issue by x13420x** [benfry/processing4#150]
worked fine in 4.0a1....there has been issues in the pást with this size(paint.width, paint.height) but the error is actually thrown one line before 
```
PImage paint;

void settings(){

paint = loadImage("ericarose.png"); 
size(paint.width, paint.height);
noSmooth();}

void setup(){

image(paint,0,0);
background(paint);}
void draw(){}

```

**Comment by benfry** [comment]
Don't load images in `settings()`. This is explicitly stated in the reference: https://processing.org/reference/settings_.html
