### ISSUE TITLE
Can we get rid of `pdexEnabled`?

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#157]
Question for @sampottinger… In 3.x and earlier there was a variable called `pdexEnabled` that shut off the fancier PDEX features when there were `.java` tabs (since they didn't play well together). Can this be removed? I'd imagine it's no longer necessary with the changes you've made to the preproc/build/run process.

**Comment by sampottinger** [comment]
See #230

**Comment by benfry** [comment]
Merged. We're now rid of him.
