### ISSUE TITLE
Misleading error message when using size() or fullScreen() outside setup

### ISSUE THREAD

**Issue by PixelCatalyst** [benfry/processing4#161]
## Description

Given `size()` or `fullScreen()` invoked outside `setup()` (e.g. in `draw()`) `IllegalStateException` is rightfully thrown. However, when using the Processing Development Environment additional advice message "When not using the PDE..." is displayed. This message might be misleading to inexperienced users as it refers to advanced use case of running Processing in external IDE.

The same error happens in both Processing 3 and 4, even after the the fresh installation

Code to replicate:
```
void setup() {
 size(500, 500);
}
void draw() {
 background(255);
 
 size(400, 400); //can also be fullScreen()
}
```

## Your Environment

 

* Processing version: Processing4 built up to commit e96622d
* Operating System and OS version: Windows 10 build 19042.685

## Possible Causes / Solutions

Looks like `PApplet` has an `external` field that should determine if processing-core is run from PDE or IDE. The condition to display the error message appears to have unnecessary negation, but I don't fully understand how that variable is calculated.

**Comment by benfry** [comment]
`--external` wasn't getting set properly, but that's now fixed as part of https://github.com/processing/processing4/issues/158

So this should work properly in 4.0 alpha 4 once it's ready.
