### ISSUE TITLE
noSmooth() is not applied when used in setup (PDE)

### ISSUE THREAD

**Issue by PixelCatalyst** [benfry/processing4#163]
## Description
Processing 4 seems to wrongly interpret if it is working isde PDE or not. This causes `noSmooth()` to be impossible to call in `setup()`, as Processing (PDE) demands it to be run inside `setttings()`. Is this expected change in bevahior (it worked no-problem in Processing 3.5.4) ?

Code to replicate:

```
void setup() {
 size(500, 500, P2D);
 
 noSmooth(); //Error message is dispalyed on P4 and then drawing looks like noSmooth was not executed. On P3 working as expected
}
void draw() {
 background(255);
 
 ellipse(200, 200, 100, 100);
}
```

## Effect in P3

![P3_circle](https://user-images.githubusercontent.com/34219846/105409267-7ff6d300-5c30-11eb-939b-2d52eb9524c5.jpg)

## Effect in P4

![P4_circle](https://user-images.githubusercontent.com/34219846/105409293-884f0e00-5c30-11eb-94b1-107e165ffdfb.jpg)

## Your Environment

 

* Processing version: Processing4 built up to commit e96622d
* Operating System and OS version: Windows 10 build 19042.685

**Comment by REAS** [comment]
Hello @PixelCatalyst. Can you confirm the P4 version for your report. Is this alpha3 or earlier? I'm testing on alpha 3 and see the expected behavior, but I'm testing on OS X, so not a valid test for your software.

**Comment by benfry** [comment]
No response; closing. This was probably https://github.com/processing/processing4/issues/149 which was fixed in alpha 3.

If not, please open a new issue!
