### ISSUE TITLE
Add the ability to edit .glsl files from the Editor window

### ISSUE THREAD

**Issue by andrevenancio** [benfry/processing4#178]
This is probably more like a suggestion than an issue.

I just recently started playing with Processing. One of the things I find it difficult is not being able to import a glsl into the file explorer. I can create a new file and it creates a new .pde file, I can import a shader as long as it's on the data folder but there's no way of editing the shader directly on the processing window.

Would be nice to edit it on the processing window. :)

**Comment by danieltorrer** [comment]
Hey @andrevenancio, not sure if you already knew them, but there are some non-official extensions that might have what you need:
- Hamoid created a shader tool: https://discourse.processing.org/t/processing-shader-tool/5476/13
- Izza11 created a shader mode: https://github.com/Izza11/shader-mode

They can be helpful in the meantime, while the discussion to add shader support continues

**Comment by andrevenancio** [comment]
One of them I knew (doesn't work on processing 4) the other I'll give it a go. Thanks

**Comment by benfry** [comment]
Thanks; it'd be great to have a Tool that does this well for now, though I totally understand the need for it. 

While support could be hacked in, it means 1) setting a new precedent where we're showing entries from the `data` folder as tabs, and 2) needing to support syntax highlighting, indenting, etc for glsl. Neither are terribly difficult, but just introduces some inconsistencies (wait, why not `txt` files? `json`? etc) and potential headaches (syntax support) which mean a Tool would be a good way to bridge the gap until someone has the time to do it “right.”

**Comment by scudly** [comment]
So, don't add syntax highlighting, auto-indenting, or any of the headaches.  Just let us edit generic text files, of any extension, from within the editor.  Raw text editing gets us 99% of the way there.

**Comment by benfry** [comment]
> So, don't add syntax highlighting, auto-indenting, or any of the headaches. Just let us edit generic text files, of any extension, from within the editor. Raw text editing gets us 99% of the way there.

That only covers 50% of what I wrote. But again, this is why Tools exist: someone could make this in a day, and maintain it themselves—without introducing inconsistencies to how the development environment works, or more feature requests to add more than raw text editing.
