### ISSUE TITLE
setting which display to use does not work

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#187]
In preferences, the "Run sketches on display" has no effect for me.

Also setting it in the code with `fullscreen(2)` for example, does not work.

alpha 3
OSX 10.15.7

**Comment by knupel** [comment]
work on OSX 10.14.6 but it's very old system, just from 2 years ago :)

**Comment by benfry** [comment]
Working fine here on 10.15.7 and the soon-to-be-release 4.0a4, both by setting Preferences and from code using `fullScreen()`.

Are you sure that `2` is the screen you're after? After plugging in a second display to test this, it made by default screen `2`, and `1` is the external display.
