### ISSUE TITLE
friendly message for "cannot change mode"

### ISSUE THREAD

**Issue by micuat** [benfry/processing4#189]
## Description

(not sure to put this here or processing3)

The dialog is quite "unfriendly" at the moment and suggest to change

https://github.com/processing/processing4/blob/4153e4fd5c52f5d9358da2b94a91da28af908652/build/shared/lib/languages/PDE.properties#L588-L589

from https://discourse.processing.org/t/i-cant-change-mode/28732/5

## Expected Behavior

something like "please create a new sketch to change mode" ?? or what is even better is the mode change action will automatically open a new window

## Current Behavior

`Cannot change mode,\nbecause "%s" mode is not compatible with current mode.`

**Comment by villares** [comment]
> ...or what is even better is the mode change action will automatically open a new window

We have seen behaviour like what @micuat proposed before, like creating a folder when one is missing and just telling the user!

**Comment by benfry** [comment]
After looking through this for a bit, there just isn't an error message that makes sense here and will be useful enough. And there are too many edge cases to really make it a good experience for users. So for alpha 6, I'm changing it to just open a new window in situations where things don't match—i.e. there have been changes, the code would be incompatible, etc. 

In those cases, the user will know what they want to do (i.e. copy and paste code, or close the old window w/o saving, or whatever) and the mild inconvenience is outweighed by the complication of trying to anticipate all possible situations and automatic resolutions (that may not work, and may not be what the user wanted anyway).
