### ISSUE TITLE
build installation points at deprecated batlik version

### ISSUE THREAD

**Issue by arashizadi** [benfry/processing4#192]
Apache removed the binary link of batik-bin-1.13.zip (https://apache.osuosl.org/xmlgraphics/batik/binaries/batik-bin-1.13.zip) since they released version 1.14. in order for processing 4 alpha to install successfully, following needs to be done:

1) after ant requirement, download https://apache.osuosl.org/xmlgraphics/batik/binaries/batik-bin-1.14.zip  
2) unzip batik-bin-1.14, then rename main folder and all the .jar files that has 1.14 to 1.13. This includes jar files in lib folder.
3) zip the main folder and name it batik-bin-1.13.zip.
4) place the zip binary into \processing4-master\java\libraries\svg

Of course, that can be solved through the ant automated installer.

**Comment by benfry** [comment]
All set now. Bummed that they actually remove the download link; I'll just have to add something that automatically uses the fallback link on download.processing.org.
