### ISSUE TITLE
Implementation of PVector.setHeading()

### ISSUE THREAD

**Issue by arijit4** [benfry/processing4#193]
There's an method named `PVector.setHeading()` in `p5.Vector` class of p5.js to set the direction of an vector to any given angle. But there's no such option in Processing. It can be settled down easily. But the function seems more self explanatory and easy to understand. It also goes well with the `PVector.heading()` method already present in Processing.

An implementation might look like the following :

```processing
void setHeading(float angle) {
    this.rotate(angle - this.heading());
}
```

**Comment by benfry** [comment]
Adding it for parity with p5.js… Here's the full implementation from there:

```javascript
_main.default.Vector.prototype.setHeading = function setHeading(a) {
  var m = this.mag();
  this.x = m * Math.cos(a);
  this.y = m * Math.sin(a);
  return this;
};
```

**Comment by arijit4** [comment]
@benfry In  [673a19e](https://github.com/processing/processing4/commit/673a19ee43cc3aa570dc859844ed6de2501f0ddf), you added
```java
public PVector setHeading(float angle) { 
    float m = mag();
    x = m * Math.cos(a);
    y = m * Math.sin(a);
    return this;
 }
```

shouldn't it be the following?
```java
public PVector setHeading(float angle) { 
    float m = mag();
    x = m * Math.cos(angle);
    y = m * Math.sin(angle);
    return this;
 }
```

**Comment by benfry** [comment]
Yes, and it was immediately fixed in the next commit.

**Comment by arijit4** [comment]
@benfry `PVector.setHeding()` isn't highlighted as other methods in `PVector`. But it works perfectly though...
