### ISSUE TITLE
Method overloads to accept PVector instead of coordinates

### ISSUE THREAD

**Issue by anoniim** [benfry/processing4#195]
Would it make sense to overload methods that take `x` and `y` (and `z`), e.g. `vertex`, `point`, `line`, `triangle`, `quad`, `square`, `circle`, `text`, `translate` etc. to accept `PVector`?

This could look like:
```
public void vertex(PVector vector) {
    vertex(vector.x, vector.y, vector.z);
}

public void point(PVector vector) {
    point(vector.x, vector.y, vector.z);
}

...
```

I found myself adding these to my base sketch class for convenience and wonder if there is a reason for them not to be included in the core library. Is it because of the ambiguity of 2D vs 3D?

**Comment by anoniim** [comment]
Sorry, just found [#5220](https://github.com/processing/processing/issues/5220) and [#1897](https://github.com/processing/processing/issues/1897) in the old project.

Would it be a good time to reconsider for Processing 4?

There are people keen on creating a pull request (myself included).

**Comment by benfry** [comment]
No plans to do this for 4.x, but I've just added a few notes to https://github.com/processing/processing/issues/1897 for background.
