### ISSUE TITLE
PShape performance could be improved using buffer object streaming 

### ISSUE THREAD

**Issue by codeanticode** [benfry/processing4#196]
Performance was quite good with GLModel (from the [GLGraphics](http://glgraphics.sourceforge.net/) library) in certain instances where PShape still struggles (for example when modifying the coordinates of many vertices at once), because GLModel used a technique called [buffer object streaming](https://www.khronos.org/opengl/wiki/Buffer_Object_Streaming). This technique allows one to write data directly into a regular Java buffer, which internally is mapped to video memory. This relies on the function [glMapBufferRange](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMapBufferRange.xhtml), which was available only on desktop, not on mobile (OpenGL ES), back when the OpenGL renderer in Processing 2 & 3 was implemented it. In order to keep code parity between desktop and mobile versions of the OpenGL renderer Processing, buffer streaming was not used in PShapeOpenGL. It turns out that glMapBufferRange eventually became available in [OpenGL ES 3.0](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glMapBufferRange.xhtml). So it could be possible to re-implement buffer streaming to improve PShape performance, perhaps in combination with other PShape enhancements such as this one https://github.com/processing/processing/issues/2280, for both Processing 4 and new versions of the Android mode. [to be tagged as proposed enhancement]

**Comment by benfry** [comment]
Since you're the maintainer of that code, are you offering to implement it? Or is this a request for someone else to do so?

**Comment by codeanticode** [comment]
I'd like to implement it. Just could not assign issues to myself in this repo :-)

**Comment by benfry** [comment]
That's odd, it should have similar permissions as the 3.x repo, but let me know if I need to set something for you.

**Comment by codeanticode** [comment]
Looks like I'm able only to unassign myself from the issue, but that's ok.  You can add "enhancement" and "opengl" as labels.

**Comment by codeanticode** [comment]
Explored stream object copy, actually not that hard to implement: https://github.com/codeanticode/processing4/commit/a23aaa51980e0bfc1dc2dc7e3c1c47ba3ff8648f

That could help, but what makes PShape sluggish compared with the old GLModel class is that the latter operated directly on the tessellated geometry that's rendered through GL. PShape adds a lot of overhead necessary to properly tessellate primitives, arbitrary polys, stroke lines, etc. 

One way to bypass this overhead is to allow direct modification of the tessellated geometry. There was some ["experimental" API](https://github.com/processing/processing4/blob/master/core/src/processing/opengl/PShapeOpenGL.java#L2661) in PShapeOpenGL that allowed to retrieve the tessellated vertices, but don't think it was very useful. Something more useful in terms of perf could be to add a beginTessUpdate/endTessUpdate block where all setVertex/Fill/Normal inside of it would operate on the tess geo. I tried that out (https://github.com/codeanticode/processing4/commit/6595427e117b31e685fe3e53477410854f88c0bb) and seems to make a differnce. From something like:

```
for (int ci = 0; ci < group.getChildCount(); ci++) {
  PShape child = group.getChild(ci);
  float rx = random(-1, 1);
  float ry = random(-1, 1);
  float rz = random(-1, 1);
  child.translate(vi, v.x, v.y, v.z);
}
```

to

```
group.beginTessUpdate(TRIANGLES);
for (int ci = 0; ci < group.getChildCount(); ci++) {
  PShape child = group.getChild(ci);
  float rx = random(-1, 1);
  float ry = random(-1, 1);
  float rz = random(-1, 1);	      
  for (int vi = 0; vi < child.getVertexCount(); vi++) {
    child.getVertex(vi, v);
    v.x += rx;
    v.y += ry;
    v.z += rz;
    child.setVertex(vi, v.x, v.y, v.z);
  }
}
group.endTessUpdate();
```

the fps difference can be quite significant (3X) for large geometries. Perhaps is worth removing the getTesselation() methods from PShape, and adding beginTessUpdate/endTessUpdate (or better named).

**Comment by PratiquesAlgorithmiques** [comment]
Hello Andrés, I'd like to test this. What is v in the above examples ? Thanks !

**Comment by codeanticode** [comment]
oh sorry, v is just a temporary PVector to get the current vertex coordinates, here you have the full code, as a Java application: 

```
package test;

import processing.core.PApplet;
import processing.core.PMatrix3D;
import processing.core.PShape;
import processing.core.PVector;

public class Sketch extends PApplet {

	PShape group;

	int numBoxes = 162500;
	//int numBoxes = 500;
	float boxSize = 2;

	PMatrix3D mat = new PMatrix3D();
	
	int fcount, lastm;
	float frate;
	int fint = 3;	
	
  public void settings() {
	  size(600, 600, P3D);
//	  fullScreen(P3D);
	  noSmooth();
  }
    
  public void setup() {   
	  noStroke();
	  group = createShape(GROUP);
	  
	  for (int i = 0; i < numBoxes; i++) {
	    PShape s = createShape(BOX, boxSize, boxSize, boxSize);
	    s.setFill(color(255, 0, 0));
	    s.translate(random(-width/2, width/2), random(-height/2, height/2), random(-1000, 1000));
	    group.addChild(s);
	  } 
  }
  
  public void draw() {
	  background(0);
	  lights();
	  PVector v = new PVector();
	  
	  group.beginTessUpdate(TRIANGLES);
	  for (int ci = 0; ci < group.getChildCount(); ci++) {
	    PShape child = (PShape)group.getChild(ci);
	    float rx = random(-1, 1);
	    float ry = random(-1, 1);
	    float rz = random(-1, 1);	      
	    for (int vi = 0; vi < child.getVertexCount(); vi++) {
	  	child.getVertex(vi, v);
	  	v.x += rx;
	  	v.y += ry;
	  	v.z += rz;
	      child.setVertex(vi, v.x, v.y, v.z);
	    }
	  }
	  group.endTessUpdate();

	  translate(width/2, height/2, 0);
	  rotateY(frameCount * 0.001f);
	  rotateX(frameCount * 0.001f);
	  shape(group);
	  
//	  if(frameCount % 60 == 0) {
//	    println(frameRate);
//	  }
	  fcount += 1;
	  int m = millis();
	  if (m - lastm > 1000 * fint) {
	    frate = (float)(fcount) / fint;
	    fcount = 0;
	    lastm = m;
	    println("fps: " + frate); 
	  } 	  
  }
    
  public static void main(String[] args) {
    PApplet.main("test.Sketch");
  }
}
```

You would need to build [this branch](https://github.com/codeanticode/processing4/tree/pshape-stream) in my fork of processing4 to test this.

**Comment by PratiquesAlgorithmiques** [comment]
30fps with 65000 boxes. Things are looking up ! Thanks Andrès ! Jeff

**Comment by codeanticode** [comment]
Nice, no hiccups?

**Comment by codeanticode** [comment]
@benfry Implemented buffer object streaming [here](https://github.com/codeanticode/processing4). Also used the opportunity to finalize the attribute API in PShape, and do some refactoring/cleanup in PGrpahicsOpenGL.

As discussed in previous comments, the new buffer object streaming adds to new methods to PShape, right now they are called beginTessellationUpdate and endTessellationUpdate. All setters/getter calls between this begin/end block work on the tessellated geometry instead of the input geometry, and the setter calls save the new values directly into the corresponding mapped vertex buffers, without triggering a re-tessellation. This enables much faster geometry update in certain cases. An example of use:

```
PShape group;
int numBoxes = 150000;
float boxSize = 2;

void setup() {
  //size(600, 600, P3D);
  fullScreen(P3D);
  noStroke();
  group = createShape(GROUP);

  for (int i = 0; i < numBoxes; i++) {
    PShape s = createShape(BOX, boxSize, boxSize, boxSize);
    s.setFill(color(255, 0, 0));
    s.translate(random(-width/2, width/2), random(-height/2, height/2), random(-1000, 1000));
    group.addChild(s);
  }
}

void draw() {
  background(0);
  lights();

  PVector pos = new PVector();
  group.beginTessellationUpdate();
  for (PShape child : group.getChildren()) {
    float rx = random(-1, 1);
    float ry = random(-1, 1);
    float rz = random(-1, 1);
    for (int idx = 0; idx < child.getVertexCount(); idx++) {
      child.getVertex(idx, pos);
      pos.add(rx, ry, rz);
      child.setVertex(idx, pos);
    }
  }
  group.endTessellationUpdate();

  translate(width/2, height/2, 0);
  rotateY(frameCount * 0.001f);
  rotateX(frameCount * 0.001f);
  shape(group);

  if (frameCount % 60 == 0) {
    println(frameRate);
  }
}
```

Any thoughts, comments?

**Comment by benfry** [comment]
Ok, let's use `beginTessellation()`/`endTessellation()`… we don't use three word API calls anywhere in the API unless it's completely unavoidable.

I'm nervous about a major change like this coming in late, but we'll see how it goes.

**Comment by codeanticode** [comment]
Get your concern, I ended up making more changes that I originally anticipated, but also did run a fair amount of tests, including with complex libraries such as Hemesh :-) I will go ahead, change the names of the methods and create the PR.

**Comment by codeanticode** [comment]
The other PR with all the recent gl changes: https://github.com/processing/processing4/pull/238

BTW, how can add the new example for the tessellation update mode? The default examples don't seem to be included with the main repo anymore.

**Comment by benfry** [comment]
@codeanticode Are we clear to close this one?

**Comment by codeanticode** [comment]
Yep, closing.
