### ISSUE TITLE
Failled to build with Java 11

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#2]
My terminal explain to me I need Java 1.8 to build this version is weird or not ?
`/Users/stan/En_cours/code/github/PROCESSING_and_CO/processing4/build/build.xml:57: Unsupported Java version: 11.0.4. To build, make sure that Java 8 (aka Java 1.8) is installed.`

**Comment by benfry** [comment]
This fork doesn't do anything yet.

**Comment by knupel** [comment]
ok, so for the moment we must conitnue to test on this one https://github.com/sampottinger/processing
