### ISSUE TITLE
Add ability to move ~/.processing directory

### ISSUE THREAD

**Issue by Addisonbean** [benfry/processing4#203]
## Description

Processing uses `~/.processing` for it's data with no way to change that. It would be nice to be able to control the location of that directory so it can follow XDG directory specifications and keep users home directories clean.

## Expected Behavior

Processing should provide an environment variable to control where the processing data directory is found, and fall back to `~/.processing` if not specified.

## Current Behavior

There is no clearly documented way to move `~/.processing` to another location (there may be a way, however I was not able to find it via `processing-java --help` or the online documentation).

## Steps to Reproduce

N/A

## Your Environment

* Processing version: 3.5.4
* Operating System and OS version: Arch Linux (Linux kernel 5.9.3) 
* Other information: `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` are set and were not used by processing when deciding where to create this directory

## Possible Causes / Solutions

Add an environment variable that can provide an alternate location for `~/.processing`, and fall back to the old location if not specified.

An even better solution would be to default to `~/.config/processing` unless `$XDG_CONFIG_HOME` is set or if `~/.processing` already exists.

**Comment by benfry** [comment]
And back to your original request, would we be covered by using `~/.config/processing` by default instead of `~/.processing`? It seems like that's the direction we should be going here (and is a lot more straightforward than reading an environment variable for the location, and then needing to document that somewhere, testing it on various devices, etc).

**Comment by Addisonbean** [comment]
Personally, yes that would make me happy. However I imagine someone at some point will want it elsewhere, plus I like the flexibility offered by being able to move it anywhere so I think it's a good idea anyway. It seems weird to me to not have a way to change the location of the config, but it's not something I see myself using so I don't really care.

**Comment by benfry** [comment]
Ok, this is now implemented for 4.0 beta 1. Instead of the home directory, it'll use `$XDG_CONFIG_HOME` if it's available, or `~/.config` if not.
