### ISSUE TITLE
Proper vector, matrix and quaternion classes

### ISSUE THREAD

**Issue by ertdfgcvb** [benfry/processing4#206]
### General purpose vector classes
This “issue” has probably been discussed many times but as a new release is in the works it’s probably worth considering again. 
Processing’s PVector class is extremely simple… sometimes too simple, that’s why many libraries and frameworks need to re-implement their own vector classes, creating transportability issues among other things.
It would be nice if Processing would come with a well built, solid and detailed vector class(es) and the companion matrices and quaternions (PMatrix exists but not documented?).

An example from openrndr which also has intVectors:
https://github.com/openrndr/openrndr/tree/master/openrndr-math/src/main/kotlin/org/openrndr/math

An example from jMonkeyEngine (v2, v3, v4, mat, quat, etc.) which offers ”in place” or ”new object” for all operations:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/math

### Overload
On an additional note vectors (and Matrices) should also be accepted by all the geometric and drawing functions in processing (vertex(), translate(), line(), ellipse(), createGraphics(intVect), etc.)… 
The Processing team seems to disagree with this approach, so this will probably not happen. 
Discussion about method overload also here: 
- https://github.com/processing/processing4/issues/195
- https://github.com/processing/processing/issues/1897

**Comment by benfry** [comment]
The overloading I just covered a day or two ago in the issue you linked, meaning that it's up to date for 4.x.

For vector, matrix, and quaternion classes, this would be the relevant discussion: https://github.com/processing/processing/issues/1779

Bottom line is that I'd like to see it developed (independently) as a library first, develop a user base so it can get tested, and then when it's ironed out a bit, we would move that into the core. That was the conclusion that people came to in that thread as well, but nobody did the work to make it happen.

But without that sort of considered effort, we run into the same issue as with `PVector`, where it was incorporated but imperfect: some folks had been using it, we did some cleanup to make it behave more like the rest of the API and fix performance issues, but it's kind of an outlier.

**Comment by wblut** [comment]
Many external libraries, especially geometry-based, will have specific demands, like double precision or immutability. It would be unyieldy (I don't want to say the impossible-word) to create a general vector class that covers everyone's needs. The same goes, but even more, for matrix implementations. I have never come across a library that covered all the matrix functionality I needed at some point, except some very general ones with serious performance issues.

Transportability issues can be fixed without asking a full-blown math implementation in Processing: one solution that external libraries can offer is by implementing a subclass of PVector that in addition implements the same interface as their internal vector class. Like WB_PVector in my hemesh library -rest in peace. WB_PVector can be used everwhere hemesh wants its own vector type but additionally everywhere where Processing expects a PVector. A Processing based solution is to make a vector-interface, with PVector as its default implementaton, and only refer in code to the instance. However that means replacing the public properties .x with methos like .x().

If I'd like to see one thing changed  it's this: add, sub, div and... mult. M-U-L-T,  4 letters. Not add, sub,div, mul, no, that would be too nice. Mult... grmbl...

**Comment by ertdfgcvb** [comment]
Well, apparently I stirred up the old vector pond…  
IMO more important than the method implementations (chaining, in place vs. copy etc) is an out-of-the-box availability of a shared data type: vecf2,3,4, veci2,3,4, mat3, mat4, etc. and consequent use in the API and libs. Methods can always be extended, eventually… 
But it finally appears that the current state is the best with ultra-basic vec and mat classes which cover just the most essential situations… for everything else it’s up to the user do go custom, build own 2d or int vector, quat, etc. 
(Still a bit jealous when looking at game engines with all the math libs ready to use…)

**Comment by wblut** [comment]
Not sure if there's reason to be jealous, for advanced things we basically have all java libraries at our disposal within Processing. Any implementation of vector and matrix math is opiniated. Game engines have a "single" purpose for their math libs: display graphics.  I don't think that's true for Processing. If I'd need to make a choice between customizing Processing for grizzled mathy generatives like me or for people getting into computational art from non-tech backgrounds, I'd go for the latter every time. I mean, I already have all those game engines and related coding projects catering to me.

**Comment by ertdfgcvb** [comment]
And what about removing PVector (and the undocumented/hidden PMatrix) completely? They aren’t used anywhere int the API and they could be offered as an optional import (still part of the core libs)… at least it becomes evident that it’s up to the user to make the right math / geom choice and projects don't mix different vector (Vec3 + PVector) types when importing / using something else… 

Possibilities:
1. remove PVector completely, core is clean, PVector becomes a small lib (still part of the official dist), external choices exist…
2. keep current state (not generic enough, no 2d, no int, etc. not used anywhere in gfx API)
3. create additional data-types but with basic impl., still part of core: user needs to extend / implement for more specific cases
4. boost current vec + mat (+ quat) classes, full math lib.: too opinionated, won’t cover all cases anyways, better or specific libs already exist 

Personally I value the portability of small PDE projects… being able to write sketches that don't depend on external libraries is something which has advantages and I like that there are a few “core libs” for general use (sound, video, etc) and that are ready to use and available within PDE.

**Comment by benfry** [comment]
No, we can't do that. `PMatrix` is used internally, that's why it exists, and `PVector` is used in a large amount of code that's out there.

**Comment by ertdfgcvb** [comment]
I didn't mean remove from core, just remove as a default import.
The fix would just be `import processing.PVector` or similar for old programs to run in P4… But at least it becomes an explicit import; when dealing with external vector classes there is not a mix of `PVector` or `Vec3` (or anything else) in the same program.   
But probably point 2. from the above list is the way to go: no breaking changes (especially for aesthetic reasons like this one).

**Comment by LoganDark** [comment]
This would start to turn Processing into a sort of opinionated game engine, as it would become unfairly complicated to use anything except matrices and quaternions, because of them being in the standard library - you would also be encouraging beginners to use quaternions, which are basically black boxes which can't really be properly understood (I can back up this claim; keep reading).

While it's true that it would not become any _more_ complicated, it would feel unfair - as quaternions aren't the only way to represent rotations. Here is a [good explanation](https://docs.rs/ultraviolet/0.8.1/ultraviolet/) on why quaternions aren't even the best choice:

> There are a couple relatively unique/novel features in this library, the most important being the use of the Geometric Algebra.
>
> Instead of implementing complex number algebra (for 2d rotations) and Quaternion algebra (for 3d rotations), we use Rotors, a concept taken from Geometric Algebra, to represent 2d and 3d rotations.
>
> What this means for the programmer is that you will be using the `Rotor3` type in place of a Quaternion, though you can expect it to do basically all the same things that a Quaternion does. In fact, Quaternions are directly isomorphic to Rotors (meaning they are in essense the same thing, just formulated differently). The reason this decision was made was twofold: first, the derivation of the math is actually quite simple to understand. All the derivations for the code implemented in the Rotor structs in this library are written out in the `derivations` folder of the GitHub repo; I derived them manually as part of the implementation.
>
> On the other hand, Quaternions are often basically just seen as black boxes that we programmers use to do rotations because they have some nice properties, but that we don’t really understand. You can use Rotors this same way, but you can also easily understand them. Second is that in some sense they can be seen as ‘more correct’ than Quaternions. Specifically, they facilitate a more proper understanding of rotation as being something that occurs _within a plane_ rather than something that occurs _around an axis_, as it is generally thought. Finally, Rotors also generalize to 4 and even higher dimensions, and if someone wants to they could implement a Rotor4 which retains all the properties of a Rotor3/Quaternion but does rotation in 4 dimensions instead, something which simply is not possible to do with Quaternions.

So if you want to do this correctly, if you want to minimize the amount of opinionation in your standard library and _actually_ help people make their game engines or quick demos or what have you, please consider supporting _not only quaternions_, but also these more obscure objects that can be used and understood more easily.

My stance on this is "support everything or support nothing" - support 2D vectors, 3D vectors, [3D isometry matrices](https://docs.rs/ultraviolet/0.8.1/ultraviolet/transform/struct.Isometry3.html), quaternions, rotors, [bivectors](https://docs.rs/ultraviolet/0.8.1/ultraviolet/bivec/struct.Bivec3.html), etc. or just... please don't bother.

**Comment by benfry** [comment]
Closing this since our final word for 4.x is here: https://github.com/processing/processing4/issues/206#issuecomment-863137646

Short version: make a useful library, get folks to use it, if it becomes a standard, let's incorporate it. And for folks who'd like to discuss further, the forum is the best place: https://discourse.processing.org/
