### ISSUE TITLE
Illegal reflective access by processing.app.platform.LinuxPlatform

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#207]
The X11 `WM_CLASS` property which is used as the application name by Gnome3 and other window managers, so in response to https://github.com/processing/processing/issues/2534, we added code to modify the name. It relies on a hack that makes a field `public`, so Java 11+ complains about it. 

To fix, we need a more reliable way to specify the application name so that it doesn't show up as `Processing.app.Base` on Linux. This could be as simple as modifying the launcher script to set the `WM_CLASS` environment variable to `Processing` on startup, but someone would need to spend some time looking into it and testing any possible solution on various Linux distros. 

There may also be an alternative using JNA, but on a quick look, it seemed to required a contrib library for JNA, which we probably don't want to rely on for sake of longevity.

**Comment by mario6097** [comment]
Is this issue the reason for https://github.com/processing/processing4/issues/333?
Is there a workaround, since otherwise I can not use Processing4 on my machine F35?
It would be great if somebody fix it.

**Comment by benfry** [comment]
I don't think so—I believe this is a benign problem that we just need to deal with at some point.

**Comment by benfry** [comment]
To be clear: this is a warning (just like the message says in all caps, I guess), not an error that will break the software (for now). But I'd still like to address the issue it's complaining about.

**Comment by benfry** [comment]
Another detailed thread from someone looking into the same issue: https://github.com/cryptomator/cryptomator/issues/956#issuecomment-787061581

**Comment by benfry** [comment]
Warning fixed with https://github.com/processing/processing4/commit/8e5433430e266592b83da0a68542d4d082738c38 but the deeper issue is still unresolved. See https://github.com/processing/processing4/issues/207.
