### ISSUE TITLE
Windows cursor deletion off

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#21]
Filing for [kll](https://discourse.processing.org/u/kll) from a [processing forums discussion](https://discourse.processing.org/t/processing-in-style-with-java-11/13776/24). There is a report that deletion happens at the wrong position on Windows with no zoom, Monospaced, 10pt. Possibly related to #19.

**Comment by sampottinger** [comment]
I was not able to reproduce this on Windows 10 but I have requested further information from kll and will continue investigating.

**Comment by kllsamui** [comment]
sorry,

> I can’t seem to reproduce this in Windows using the settings you provided yet but I will continue looking. Do you have any sort of display scaling set up outside of Processing?

not understand but talking here is ok.

but need you to tell me what i have to do exactly.
* what windows info you need?
* you want me to test again after delete processing systems dir ( preferences )
( like at a first install )?

but if it runs on your win10, i take it as my local problem.

( i do need to tell you that my virus program AVG
2 times delayed the start of your program for about 20 sec. )

**Comment by sampottinger** [comment]
Hey @kllsamui! Thanks so much for writing back.

> what windows info you need?

I am curious what your display settings are under Start > Settings > System > Display as shown below.

<img width="968" alt="Screen Shot 2019-11-11 at 7 00 36 PM" src="https://user-images.githubusercontent.com/110391/68638312-f8eb8e00-04b5-11ea-84d7-caa8c841a7f8.png">

> ( i do need to tell you that my virus program AVG 2 times delayed the start of your program for about 20 sec. )

Yeah my guess is because this was not a signed executable (I need to open a separate issue about that). I'm not sure if Ben typically signs the windows releases or not but I didn't for my binary.

**Comment by kllsamui** [comment]
-1- my windows info:
![win10_displaysettings](https://user-images.githubusercontent.com/19226581/68639635-c6827500-0537-11ea-8b79-7bca8a232bbe.png)

![win10_displaysettings2](https://user-images.githubusercontent.com/19226581/68639647-cf734680-0537-11ea-9840-fab41acc9c66.png)

____
-2- deleting processing systems dir
restart processing 40c

![processing_40c_install](https://user-images.githubusercontent.com/19226581/68639687-edd94200-0537-11ea-81c7-7e738e4606a7.png)

test your java 11 test code 

![processing_40c_samtest](https://user-images.githubusercontent.com/19226581/68639697-f467b980-0537-11ea-9bc6-af99cf703fcb.png)

edit a new code line and have same space / cursor delete problem again

-3- new download your version to win 7
! same:
-a- NO question allow JAVA to run
-b- AVG check program 
 ( so this is very different from your last build!! /
 and the sign of windows release might not be the point. )

BUT on win7 computer not see the line edit / backspace problem

![win7_processing40c](https://user-images.githubusercontent.com/19226581/68639913-a43d2700-0538-11ea-860e-28d3b9feeead.jpg)

 works fine.

**Comment by sampottinger** [comment]
Hey @kllsamui! Thank you for this information.

> -1- my windows info:

Thank you for these details.

> edit a new code line and have same space / cursor delete problem again

That's a bummer. I am seeing some visual artifacts in your screenshot that make me wonder if there's some sort of system zoom thing going on. I'll investigate that further.

>  BUT on win7 computer not see the line edit / backspace problem

It is very interesting that windows 7 seems to be fine for you but not windows 10. Thank you for those details.

> -a- NO question allow JAVA to run -b- AVG check program ( so this is very different from your last build!! / and the sign of windows release might not be the point. )

Thank you for trying this though I don't know if I understand. To clarify, are you saying that:

 - you _do_ see issues with AVG and / or a confirmation to run the program on Windows 10 but
 - you _do not_ see issues with AVG and / or a confirmation to run on Windows 7?

Thanks,
Sam

**Comment by kllsamui** [comment]
> Thank you for trying this though I don't know if I understand. To clarify, are you saying that:
    you do see issues with AVG and / or a confirmation to run the program on Windows 10 but
    you do not see issues with AVG and / or a confirmation to run on Windows 7?

i run your 2 first builds and they behave same like processing 3.5.3 does ( did ):
-1- after unzip at very first start get the question to allow JAVA to run
( i not get that question with your latest build )
-2- that AVG check new processing program i see first time with your build,
but that does not mean anything, it could be caused by a new AVG version doing that???
_____
so i download p3.5.3 again ( and delete systems dir ) and test a new unzip/start:
_GRRRR ok, with new 3.5.3 also not get the allow run JAVA question anymore
( so something changed on my computer )_

AND not get the AVG checking.
so that is clearly related to your LATEST build only.
so something new inthere triggers the virus checker, but ends up good.

**Comment by sampottinger** [comment]
Thank you very much @kllsamui. I'm not sure about AVG and my guess is that the other behavior is related to [SmartScreen](https://en.wikipedia.org/wiki/Microsoft_SmartScreen#Windows). I've opened a separate issue for SmartScreen: https://github.com/processing/processing4/issues/25. I was able to reproduce this on my machine by building on a different computer and copying the executable over. :-/

**Comment by sampottinger** [comment]
With that said @kllsamui, it looks like system zooming seems to work on Mac but, as best I can tell, something about Windows zooming is causing the rendering of `JEditTextArea` to be incorrect in some settings and likely has to do with [JEP 263](https://openjdk.java.net/jeps/263). The other components likely render correctly because Swing has internally added support for this scaling but JEditTextArea uses custom rendering and likely requires further modification.

**Comment by sampottinger** [comment]
Hey there! The update on this... It looks like this is, in fact, related to https://openjdk.java.net/jeps/263. Specifically, the size of the text seems to be incorrectly calculated by `getPartialPixelWidth` inside `JEditTextArea` when windows display scaling is set higher than 100% such that the cursor's x position is inflated. Interestingly, this only seems to impact font size calculation but the rendering is fine.

**Comment by sampottinger** [comment]
Hey there! I disabled the partial pixel calculations and it didn't resolve the issue. So, I may not have been correct in my last message. Also interesting is that the issue only happens if the display scaling was active at the time that processing starts. If the OS display scaling is enabled after processing starts, the issue is not present. Also, this happens regardless of the zoom settings inside processing itself.
