### ISSUE TITLE
Export fails with Windows target because Launch4j expects different Java version format

### ISSUE THREAD

**Issue by jetp250** [benfry/processing4#211]
## Description

Launch4j, as bundled with Processing 4.0a4, expects the minimum JRE version specified to be in the format `x.x.x[_xx]`. This probably works for all versions prior to Java 10, but with Java 11 it would be for example `11.0.11`. Linux export doesn't use Launch4j and is therefore unaffected (tested, exported fine).

The new versioning system is detailed in [JEP 223](http://openjdk.java.net/jeps/223) which was part of Java 9.
The relevant Launch4j ticket is [#183](https://sourceforge.net/p/launch4j/bugs/183/) which was part of the Launch4j release 3.12.

## Expected Behavior

Launch4j would work with the new versioning system too and export would work.

## Current Behavior

The exporter does create the `application.windows` folder with (what looks like) populated `lib` folder and two launch4j files, `launch4j-build.xml` and `launch4j-config.xml`. Launch4j then throws a BuilderException about an illegal version format:
```
...\application.windows\launch4j-build.xml:5: net.sf.launch4j.BuilderException: Invalid data: Minimum JRE version should be x.x.x[_xx]
```
[Full stacktrace](https://paste.gg/p/anonymous/4b5a4f866347417eb5bb995bc1e1721f/files/24162e9e48494eb7aaa9f70ffa88ef75/raw)

## Steps to Reproduce

1. Create a new Processing 4.0a4 project
2. Choose File -> Export Application, choose Windows as the target. 
3. Press Export.

Error happens regardless of whether the "Include Java.." checkbox is ticked or not. 

## Your Environment

 

* Processing version: 4.0a4
* Operating System and OS version: Windows 10 (20H2, build 19042.1052)
* Other information: Installed Java version is `openjdk 16.0.1 2021-04-20`, no other versions

## Possible Causes / Solutions

Updating Launch4j to at least version 3.12 should fix this.

**Comment by benfry** [comment]
Thanks for the report; already fixed this on Friday! It'll be in 4.0 alpha 5: https://github.com/processing/processing4/commit/bb60818b1ffdcd4e6fcf6a823557d51f710bde70
