### ISSUE TITLE
Implementing PShape.saveShape()

### ISSUE THREAD

**Issue by arijit4** [benfry/processing4#213]
## Description
There's a method named `PShape.loadShape(String)` which imports a `.svg` file. We can use and modify that file in our program. But there's no such method to export such drawings as an `.svg` file. There's a way for exporting `PShapes` as `.pdf` file. But when we work with a very complex program, we've to clean the canvas using `background(int)`. Thus, the pdf gets full of unneccerry layers. So, it will be so much helpful to have a `PShape.saveShape(String)` method to export an `PShape` as an `.svg` file.

## Expected Behavior
Takes an String as the filename and exports the `PShape` as an `.svg` file.

**Comment by benfry** [comment]
For what it's worth, the complement to the PDF library is the SVG library, which already exists and can save whole displays as SVG. But that's different from `saveShape()`.

**Comment by arnoudvanderleer** [comment]
Is `saveShape` supposed to be just a left inverse to `loadShape`? I.e. is it supposed to be able to export everything that can be obtained as an import from an SVG file?
Or should it also export shapes that would never be possible to import from an SVG file?

**Comment by arnoudvanderleer** [comment]
Actually, there is no method `PShape.loadShape(String path)`. We have the constructor `PShapeSVG(Xml data)` and `PGraphicsOpenGL.loadShape(String path)`. I will add the save method to PShape, but would there be a better place for it?

**Comment by arnoudvanderleer** [comment]
I believe there is a simple "hack" to achieve this (haven't tested it). We can add the following to `PShape`:
```Java
  private void saveSVG(String filename) {
    PGraphics g = new PGraphicsSVG();
    g.setPath(filename);
    g.beginDraw();
    g.shape(this);
    g.endDraw();
  }
```
However, then we run into the problem that the functionality for loading SVG files is in `PShapeSVG` in the `core` module, but functionality for saving it is in `PGraphicsSVG` in the `libraries` folder of the `java` module. Therefore, it is unreachable from `PShape`.
It would make sense to move all functionality for loading and saving SVG data to one or two separate classes that have more or less the same status, but I am not sure where.

**Comment by arnoudvanderleer** [comment]
Okay, such a large change is too big for me to undertake without a proper conversation with @benfry (or any other person who has been involved in processing and it's vision for a long time).
Can someone comment on the preferred path forward?
 - Are we going to move PGraphicsSVG (or its contents) (which contains all the code necessary to write SVG files) to the core library?
 - Or will we duplicate its code to create something similar in the core library? (I.e, a subclass of PGraphics (to enable the Shape class to draw on it) that can write to an SVG file)
 - Or will we add the tools necessary to the SVG library?
 - Or will we not implement this function, since it can be achieved with a couple of lines of Processing code? (see below)

A small demo:
```Processing
import processing.svg.*;

PShape star;

void setup() {
  noLoop();
  size(600, 600);
  
  star = createShape();
  
  star.beginShape();
  
  star.fill(102);
  star.stroke(255);
  star.strokeWeight(2);
  
  star.vertex(0, -50);
  star.vertex(14, -20);
  star.vertex(47, -15);
  star.vertex(23, 7);
  star.vertex(29, 40);
  star.vertex(0, 25);
  star.vertex(-29, 40);
  star.vertex(-23, 7);
  star.vertex(-47, -15);
  star.vertex(-14, -20);
  
  star.endShape(CLOSE);
}

void draw() {
  PGraphics g = new PGraphicsSVG();
  g.parent = this;
  g.setPath("/home/arnoud/sketchbook/output.svg");
  g.beginDraw();
  g.shape(star);
  g.endDraw();
}
```

**Comment by benfry** [comment]
The SVG Export library is a complement to the PDF Export library. It's just a renderer for sending a sketch to an SVG. 

The most useful approach here to do `saveShape()` would really be a separate, full-featured SVG library. You could use the full Batik library behind the scenes, and wrap up better ways to load and save SVG data with the much broader range of SVG features that Batik supports. 

If that evolves to a point where it could replace what we have in `loadShape()`, that's great, but I think doing a piecemeal `saveShape()` will have the same issues as `loadShape()`, where folks expect it to support all of SVG, when it was never intended that way. 

And in the meantime, you can also use hacks like what's seen above with opening up an SVG renderer to draw to it as a way to save a shape.
