### ISSUE TITLE
Move doclet to separate repository

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#218]
I'm thinking we should make the doclet into its own repository for clarity. (i.e. processing-doclet or processing4-doclet, or it could even be part of the docs repo.) As far as I can tell, there's nothing specific to this repo. Obviously it uses the `.java` files here, but the doclet has dependencies on the sound and video libraries, and this repo could just be one more dependency like those. (Relatedly, this repo has no connection to those repos, so it adds a weird back-connection where we've been trying to keep things separate.)

@runemadsen Thoughts? I could definitely be missing something.

Related: https://github.com/processing/processing4/pull/132

**Comment by runemadsen** [comment]
I actually think that would make a lot of sense. @Anadroid is on vacation this week, but if you set up a `processing-doclet` repo and give us access, we can move it over when she's back.

**Comment by benfry** [comment]
Ok, done! (I think…)

https://github.com/processing/processing-doclet

**Comment by runemadsen** [comment]
Great! We have moved the `/doclet` folder to the repo and submitted a PR that deletes it from this repo (alongside a few smaller tweaks to the Javadoc comments).

https://github.com/processing/processing4/pull/222

**Comment by benfry** [comment]
Excellent, thanks!
