### ISSUE TITLE
Calls to unregisterMethod may not work

### ISSUE THREAD

**Issue by WhiteSte** [benfry/processing4#223]
I'm referring to [#199](https://github.com/processing/processing4/pull/199), i'm using the last version (4.05a)

## Description
I'm supposing that the method unregisterMethod from PApplet class is not working at all. 
 

## Expected Behavior
After loading a method inside PApplet it should be removed.

## Current Behavior
Methods seems to me that are not removed. 

## Steps to Reproduce

SKETCH
```
TestObject test;
  
  void setup() {
    test = new TestObject(this, "object 1");
    test.remove();
}
  
  void draw() {
    if (frameCount == 10) {
      exit();
    }
  }
```

CLASS

```
public class TestObject {
  
    private PApplet parent;
    private String name;
    private boolean flag = false;
  
    public TestObject(PApplet parent, String name) {
      this.parent = parent;
      this.name = name;
      parent.registerMethod("post", this);
    }
  
    public void post() {
      if (flag == true) System.out.println("You should have removed this Method");
      System.out.println("Running: " + name);
      this.remove(); // That should stop spamming in console
      flag = true;
}
  public void remove(){
    System.out.println("Removing: " + name);
    parent.unregisterMethod("post", name);
  }
}
```

## Your Environment

 

* Processing version: 4.05alpha
* Operating System and OS version: Mac os latest version Big Sur 11.4
* Other information: 

## Possible Causes / Solutions

I saw that a modification to this method  was made some weeks ago, maybe that's the cause

**Comment by benfry** [comment]
Found the problem; looking into it.

**Comment by benfry** [comment]
Fixed for alpha 6. 

There are a couple bugs in your test case—it's removing the name of the object not the object itself (change `name` to `this`). 

```java
public class TestObject { 
  private PApplet parent;
  private String name;
  private boolean flag = false;

  public TestObject(PApplet parent, String name) {
    this.parent = parent;
    this.name = name;
    parent.registerMethod("post", this);
  }

  public void post() {
    if (flag == true) System.out.println("You should have removed this Method");
    System.out.println("Running: " + this);
    this.remove(); // That should stop spamming in console
    flag = true;
  }
  
  public void remove() {
    System.out.println("Removing: " + this);
    parent.unregisterMethod("post", this);
  }
}
```

You're also removing the method before it has a chance to actually run… i.e. You're adding and then removing the `post()` method inside `setup()` before any `post()` calls are made, so `test.remove()` should be called somewhere later.

**Comment by WhiteSte** [comment]
> Fixed for alpha 6.
> 
> There are a couple bugs in your test case—it's removing the name of the object not the object itself (change `name` to `this`).
> 
> ```java
> public class TestObject { 
>   private PApplet parent;
>   private String name;
>   private boolean flag = false;
> 
>   public TestObject(PApplet parent, String name) {
>     this.parent = parent;
>     this.name = name;
>     parent.registerMethod("post", this);
>   }
> 
>   public void post() {
>     if (flag == true) System.out.println("You should have removed this Method");
>     System.out.println("Running: " + this);
>     this.remove(); // That should stop spamming in console
>     flag = true;
>   }
>   
>   public void remove() {
>     System.out.println("Removing: " + this);
>     parent.unregisterMethod("post", this);
>   }
> }
> ```
> 
> You're also removing the method before it has a chance to actually run… i.e. You're adding and then removing the `post()` method inside `setup()` before any `post()` calls are made, so `test.remove()` should be called somewhere later.

Yep the idea was that post() should never run because i was adding and removing at the "same time". I'm not a real programmer so it was just a demo to make the idea. Btw, thanks for the fix, do you have an idea of a date for release 6 or do you think it could work if i download the actual code and then make by myself the jar files?

**Comment by benfry** [comment]
Yeah, it's not a critique of your code—just trying to help.
