### ISSUE TITLE
Calls to registered method not working 

### ISSUE THREAD

**Issue by WhiteSte** [benfry/processing4#224]
(Ref #223)
I tried making a jar and using the actual code. Now register method i think is not working anymore. Any method is not working anymore, i attach here my core.jar file, you can test it on the code of the referred topic

EDIT: Just saw that you released the version 4.06a . I've just tried, the error persist here
[core.jar.zip](https://github.com/processing/processing4/files/6796649/core.jar.zip)

**Comment by benfry** [comment]
Seems to be working correctly here using the fixed version of your example (i.e. making sure to use `this` instead of `name`).

**Comment by WhiteSte** [comment]
you are right, it seem it's working, Libraries that i'm using still doesn't work, i will take a look at them. Thanks!

**Comment by benfry** [comment]
Ok, thanks for the update. There certainly could be a problem, so let me know if you find that it's broken.
