### ISSUE TITLE
Editor cursor position is offset to the right when display scaling >100% (on Windows)

### ISSUE THREAD

**Issue by soprano** [benfry/processing4#226]
## Description

Display of cursor position in Editor in Windows 10 for the 4.0 alpha versions 5 and 6 is offset to the right when using OS display scaling (>100%)

Change the display of the cursor to the correct position in the Editor

## Expected Behavior

When you see the cursor and you delete to the left or to the right, it is supposed to do it as in the position of the displayed cursor.

It should work like in version 3.5.4

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 4.0.5 and 4.0.6 in Windows 10
* Operating System and OS version: Windows 10
* Other information:

**Comment by benfry** [comment]
Can you provide more details? Are you on a US English version of Windows or another language? Do you have a HiDPI screen? Have you set the interface scaling in the Preferences window?

**Comment by soprano** [comment]
US English. It is not display dependent.  On the same computer if I use the release version 3.5.4, it works perfectly.
You should be able to reproduce it. Check the code for the calculation of width of font.
On Mac I am using the alpha 4.0.3 and it doesn't happen.

**Comment by soprano** [comment]
I tried interface scaling off and on and it does not change anything. Bug is still there. Did you try to reproduce the bug? Do you have a Windows 10/11 computer?

**Comment by soprano** [comment]
![image](https://user-images.githubusercontent.com/372871/126081058-8b6886e8-f673-4ec4-9c04-1643cfee3486.png)

**Comment by soprano** [comment]
See after adding all those numbers, the cursor is far to the right.

**Comment by soprano** [comment]
I tried all the fonts in Preferences, not a single one behaves well, all work equally wrong.
Am I the only one seeing this bug?

**Comment by sampottinger** [comment]
Hey there! I attempted to reproduce this on a Windows 10 computer and was unsuccessful. Do you mind providing the specific build number? https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/. If you are comfortable, getting your display settings would also be helpful. 

Attempted to reproduce with Windows 10 17763.1817
![processing_cursor](https://user-images.githubusercontent.com/110391/126884529-fc75c26c-785f-4b96-a75e-bfcacce6c812.png)

**Comment by soprano** [comment]
Hello. I discovered the differences between what you tried and what I tried. I got it in 2 computers, one with Windows 10 and one with Windows 11, but it does not happen if the Display Settings of the Operating System  are scaled as default (100%).

I have both computers scaled at 250%. But both computers with scale at 250% work perfectly on version 3.5.4.

**Comment by soprano** [comment]
I also tried by scaling in the Windows setting to only 125% and the bug appears.
Basically, version 3.5.4 compensates correctly for that scaling and 4.0.a6 seems to ignore the scaling factor.
I will try to see if I can compensate that with the scaling in the Preferences of Processing.

I tried that and compensating for scaling in Preferences does not change anything. There is no workaround for this bug unless only having to have a very small size of display in a big monitor by only using the no scaling of 100%. Any scaling on Windows larger than 100% will show the bug that doesn't show on version 3.5.4.

**Comment by soprano** [comment]
Using the same monitor, this problem doesn't show up on my Mac Mini. Mac Mini alpha versions work fine if you scale the display in the OS.

**Comment by soprano** [comment]
I am using a 40 inch 4K monitor.

**Comment by soprano** [comment]
I see in the left image you have the Display of the O.S. at 100%. I am pretty sure you will see the bug if you change it to any other value (e.g. 125%). My preferred value is 250%.

**Comment by soprano** [comment]
@benfry. It's different from the bug in MacOS. This one happens even if you don't change any font size.
The bug I am reporting here does not happen in the Mac alpha versions.

**Comment by benfry** [comment]
In alpha 5, I removed the `sun.java2d.uiScale.enabled` setting so that most scaling would work properly (i.e. the startup screen doesn't show in micro size on a HiDPI screen), but unfortunately, it looks like this has issues with custom components (like the editor component we're using) and especially with fractional sizes. 

To see if it's the fractional size issue or just a custom component issue, what happens if your scaling is at 200% or even 300%?

**Comment by soprano** [comment]
> In alpha 5, I removed the `sun.java2d.uiScale.enabled` setting so that most scaling would work properly (i.e. the startup screen doesn't show in micro size on a HiDPI screen), but unfortunately, it looks like this has issues with custom components (like the editor component we're using) and especially with fractional sizes.
> 
> To see if it's the fractional size issue or just a custom component issue, what happens if your scaling is at 200% or even 300%?

I tried any scaling different than the default (100%) in Windows and that is the only configuration that works fine. As I said above my preferred configuration is 250%. I am also using another Windows 11 computer with same monitor and same problem, and a Mac Mini M1 with same monitor and also alpha version 3 and 6 and on Mac it works perfectly. On Windows it only works fine if I switch to Processing 3.5.4.

**Comment by benfry** [comment]
Added the UI scaling flag back for alpha 7, but it leaves the underlying problem still broken. That's now being tracked here: https://github.com/processing/processing4/issues/231

**Comment by soprano** [comment]
Thank you for fixing it.

**Comment by soprano** [comment]
Not fixed in 4.0 b1 version (Beta).

**Comment by sampottinger** [comment]
Reopening given #245.

**Comment by soprano** [comment]
Not fixed for 4.0b1.

**Comment by sampottinger** [comment]
Just checking… Do you need any help from my end on this @benfry ?

**Comment by RishYang** [comment]
I had encountered the same issue in 4.0 b1 version (Beta) on Windows with 125% display scaling. However, I changed[ the setting of the High DPI scaling override to "System (Enhanced)"](https://blog.pauby.com/post/high-dpi-settings-windows-10#high-dpi-scaling-override) and the issue is kinda solved.

**Comment by benfry** [comment]
> Just checking… Do you need any help from my end on this @benfry ?

@sampottinger Happy for any help! It just needs a lot of time and testing across various platforms, screen types, and UI zoom settings. I just haven't had time to do it myself.

**Comment by PeterQuinn925** [comment]
I see this problem in 4.0b2. I don't know if the fix was applied to that version of not.
display: 
scale 125%
Resolution 1920 x 1080

**Comment by HasseDAC** [comment]
I faced the same problem in 4.0b2 and windows 10 home.
Display scale 100% could solve it.
However, the characters get too small to read.

**Comment by Iqwertz** [comment]
I also have this problem on 4.02b, The high scaling dpi override fixed it, but the application is a bit blurry now!

**Comment by MattStillerman** [comment]
I had this same problem with 4.0b2 Windows 10 Pro at 150% display.  I changed my font to Consolas and font sizes to 14.  I left the interface scale to "automatic" (unchanged).  I left "use smooth text" turned on.  The problem seems to have been resolved by these changes.

**Comment by duskvirkus** [comment]
Had the same issue when I opened up processing on a school computer (might not be up to date). Here's more documentation I took before finding this issue.

Screen Recording:
https://user-images.githubusercontent.com/43045568/145496973-11494b0d-3564-41bf-ada1-6b0de3ad681a.mp4

Screenshots:
![processing-bug-1](https://user-images.githubusercontent.com/43045568/145496783-a3d64881-18ed-4e80-b985-e91a5e474a8c.PNG)
![processing-bug-2](https://user-images.githubusercontent.com/43045568/145496786-6b464558-138c-4cf7-84f5-0712f53de5e3.PNG)
![processing-bug-3](https://user-images.githubusercontent.com/43045568/145496907-3f617625-f8cb-46af-a78f-eac33886a42b.png)

**Comment by TomasJuocepis** [comment]
Last time I used processing was years ago, version 2.0 I believe. Today I decided to do some doodling with processing again. Went online, downloaded the latest vesion (4.0b2), and immediately ran into this issue which makes it unusable. Issue is exactly as described - cursor offset to the right,. Offset increases with additional characters on the line. Using a high dpi (17" 4k monitor) windows 10 laptop. Windows 10 Pro 10.0.19044.

**Comment by jruberto** [comment]
I too experience this bug, running 150% scaling on my 4k display.
Windows 10 Pro 10.0.19041
processing-4.0b2

Using @MattStillerman suggested settings makes the app useable until this gets fixed. Thank you, Matt!

**Comment by danksearle** [comment]
I saw the bug too, thanks to the info in this thread saying that it is due to the Windows display scaling I found that by reducing my resolution low enough so I can turn off Windows scaling (which means a resolution of 1920 x 1200 for me), the bug disappears.

Edition	Windows 10 Pro
Version	20H2
Installed on	‎12/‎21/‎2021
OS build	19042.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

processing-4.0b2

The resolution that I was originally trying to use, where I saw the bug, was 3840 x 2400 with a scaling of 250%.

**Comment by colinwilcox** [comment]
Encountered this issue w/ 4.0b2

processing-4.0b2
Edition	Windows 10 Pro
Version	20H2
Display scale: 125%
Display resolution: 2560x1080



> I had encountered the same issue in 4.0 b1 version (Beta) on Windows with 125% display scaling. However, I changed[ the setting of the High DPI scaling override to "System (Enhanced)"](https://blog.pauby.com/post/high-dpi-settings-windows-10#high-dpi-scaling-override) and the issue is kinda solved.

This worked for me. Thanks! 👍 
It actually looks better when I override the display scale this way. I noticed that the font for many of the UI elements in the main window was a bit jaggy, e.g. the tab / menu text. Now it looks properly rendered.

**Comment by OldSurferDude** [comment]
I couldn't find - the setting of the High DPI scaling override to "System (Enhanced)" -
Looks like I'm stuck with a tiny font or a funky cursor

**Comment by OldSurferDude** [comment]
I was premature.  I don't have a choice, all I get is "funky cursor"

**Comment by zakatakk** [comment]
I have also encountered this on 150% scaling in 4.0b2 with a 1280 x 720 resolution.

**Comment by mariana-s-fernandes** [comment]
I have the same problem, using an Acer Aspire V3-372 , Windows 10 Home with 150% scaling and 1920x1080 resolution, Processing 4.0.b1

**Comment by benfry** [comment]
Adding a “Disable HiDPI Scaling” option in Preferences for 4.0 beta 3. It's a temporary solution, but resolves the immediate issue for now. 

Further development for a better long-term solution will be covered here: https://github.com/processing/processing4/issues/342

**Comment by GilesCartmel** [comment]
Thanks Ben that helps for the time being.   Small interface font, but at least I can set the editor font a little larger to compensate... and the cursor no longer drifts to the right.

**Comment by benfry** [comment]
@GilesCartmel what sort of device are you using? (What hardware, what OS version, what sort of display hardware, what pixel resolution, what zoom level set in Windows?)

**Comment by GilesCartmel** [comment]
@benfry 
Processor	Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz   2.40 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Home
Version	21H1
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0
15" Dell XPS laptop with 4K (3840x2160) screen, zoom level set to 175%
NVIDIA GeForce GTX 1650

**Comment by benfry** [comment]
@GilesCartmel If you turn off the Preference in Processing but put your Windows zoom level to 200% instead of 175% is the cursor still weird?

**Comment by GilesCartmel** [comment]
@benfry Disable HiDPI unchecked, Interface Scale automatic, Windows "Make Everything Bigger" set to 200%.... works ok.   Set Windows back to 175%.... problem re-appears.

**Comment by benfry** [comment]
@GilesCartmel Thanks, that's helpful and gives me something to go on… I thought we were down to just low-res displays misbehaving in beta 3 until the pref was checked, but this is actually easier to track down.

**Comment by benfry** [comment]
Should be better in beta 4, but finally, hopefully, fixed for 4.0 beta 5.

**Comment by GilesCartmel** [comment]
4.0 beta 4.... now the cursor's going the other way... not keeping up with the text.

**Comment by benfry** [comment]
Yep, fixed in beta 5.

**Comment by GilesCartmel** [comment]
Looking forward to it Ben.  Thanks.

**Comment by GilesCartmel** [comment]
Just got around to downloading and checking beta 5 and can confirm that works ok for me now.  Good work Ben, thanks.

**Comment by benfry** [comment]
Great! Thanks for letting me know.
