### ISSUE TITLE
New color theme hurts my eyes

### ISSUE THREAD

**Issue by LoganDark** [benfry/processing4#227]
## Description
I would have replied to #48, but unfortunately it's been locked due to others.

Onto the issue:

![javaw_spM09XKDNK](https://user-images.githubusercontent.com/4723091/126057874-c8e2a72e-d52d-4c69-a2c1-0a34754031c4.png)

This color scheme is physically painful to my eyes. It is far too bright and vibrant. It is almost (but not quite) as bad as `#0000FF`. Looking at this makes it hard to focus on the text around it, and causes actual pain and headaches.

I heard from a couple places that this is not the final design. That's good... I hope you reconsider your color scheme, this reeeally hurts. I cannot stare at this for hours while coding. Please don't make a custom theme mandatory for enjoying Processing 4...

**Comment by MapMaths** [comment]
Agree. There should be a tool in preference to change the color theme by user.

**Comment by benfry** [comment]
From the download link:

> * We've started work on refreshing the design. This round has a new set of colors. If you like them, great! If not, please hold your complaints. The internet doesn't need more negativity! We know some people won't like it, and we're [still working on it](https://twitter.com/ben_fry/status/1409968426093735941). We think you'll be happy with the final version—we have some exciting updates that we aren't yet ready to share, and it will all make more sense as the system comes together. [#48](https://github.com/processing/processing4/issues/48)

**Comment by LoganDark** [comment]
> From the download link:
> 
> > * We've started work on refreshing the design. This round has a new set of colors. If you like them, great! If not, please hold your complaints. The internet doesn't need more negativity! We know some people won't like it, and we're [still working on it](https://twitter.com/ben_fry/status/1409968426093735941). We think you'll be happy with the final version—we have some exciting updates that we aren't yet ready to share, and it will all make more sense as the system comes together. [#48](https://github.com/processing/processing4/issues/48)

This issue of the theme hurting my eyes is still an issue until the replacement comes. Please leave it open so I can track when it's actually fixed.

**Comment by benfry** [comment]
Removing more drama and locking the thread; this isn't a forum for complaints.
