### ISSUE TITLE
Sketch does not close on escape key

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#23]
When you press escape the sketch does not close.
This works in 3.5.3.
OSX 10.12.6

**Comment by sampottinger** [comment]
Thanks @clankill3r!

**Comment by sampottinger** [comment]
Hey there @clankill3r! Sorry I wasn't able to reproduce this (10.14.6). :( Just to make sure there isn't anything funky happening... can you escape to close on:

```
void setup() {
  size(300, 300);
  background(#FFFFFF);
}


void draw() {
  ellipse(mouseX, mouseY, 10, 10);
}
```

Thanks!

**Comment by clankill3r** [comment]
Yeah I can close that one.
I also can't reproduce, I will keep an eye on this.
I just close it for now.
