### ISSUE TITLE
Open dialog crashes Processing on Linux

### ISSUE THREAD

**Issue by matwolf** [benfry/processing4#233]
## Description
Open project crashes Processing

When you click file – open, the Processing IDE closes.

## Expected Behavior
An open file dialog appears letting you choose a folder.

## Current Behavior
Nothing happens for several seconds and the Processing IDE closes without any notice. This is 100% reproducable.

Strange: I can pick projects from the recent-list, but am not able to open from the files menu.

## Steps to Reproduce
1. Start Processing
2. Click File – Open…

## Your Environment
* Processing version: 1275 (4.0a6-1 in Manjaro's repository)
* Operating System and OS version: Manjaro Linux 

$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
$ uname -a
Linux xmg 5.12.19-1-MANJARO #1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021 x86_64 GNU/Linux

## Possible Causes / Solutions
I̶ ̶h̶a̶v̶e̶ ̶n̶o̶ ̶i̶d̶e̶a̶.̶
Solved: set `chooser.files.native` to `false`in `~/.processing/preferences.txt`– thanks, Ben!

**Comment by benfry** [comment]
Have you tried with one of the downloads that we provide? https://github.com/processing/processing4/releases

**Comment by matwolf** [comment]
Thank you for the quick response and the hint!

Not until now. Downloaded, ran install.sh, clicked icon – same behaviour. Started directly from folder, so messages popped out:

`$ ./processing⮨`
`$ WARNING: An illegal reflective access operation has occurred`
`WARNING: Illegal reflective access by processing.app.platform.LinuxPlatform (file:/home/mat/Desktop/processing-4.0a6/lib/pde.jar) to field sun.awt.X11.XToolkit.awtAppClassName`
`WARNING: Please consider reporting this to the maintainers of processing.app.platform.LinuxPlatform`
`WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations`
`WARNING: All illegal access operations will be denied in a future release`
`\#`
`\# A fatal error has been detected by the Java Runtime Environment:`
`\#`
`\#  SIGSEGV (0xb) at pc=0x00007f3d527d94b8, pid=68469, tid=68534`
`\#`
`\# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)`
`\# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)`
`\# Problematic frame:`
`\# C  0x00007f3d527d94b8`
`\#`
`\# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/mat/Desktop/processing-4.0a6/core.68469)`
`\#`
`\# An error report file with more information is saved as:`
`\# /home/mat/Desktop/processing-4.0a6/hs_err_pid68469.log`
`\#`
`\# If you would like to submit a bug report, please visit:`
`\#   https://github.com/AdoptOpenJDK/openjdk-support/issues`
`\# The crash happened outside the Java Virtual Machine in native code.`
`\# See problematic frame for where to report the bug.`
`\#`

Is the installed Java version of concern, or does Processing bring a JRE of its own? Hoewever, this is my Java:

`$ java -version⮨`
`openjdk version "16.0.2" 2021-07-20`
`OpenJDK Runtime Environment (build 16.0.2+7)`
`OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)`

This is the log file mentioned above :
[hs_err_pid68469.log](https://github.com/processing/processing4/files/6931143/hs_err_pid68469.log)

**Comment by benfry** [comment]
Ok, the Illegal Reflective Access message is a red herring (see https://github.com/processing/processing4/issues/207) but the crash is something happening in the JVM. 

I don't test on Java 16 (11 is what's supported) but if you have 16 working, I would try:

```
cd /path/to/processing-4.0a6
mv java java.hiding
ln -s /path/to/your/jvm/folder ./java
```

The exact path you're using for the link should ensure that from inside the Processing download, `./java/bin/java` points to the `java` binary.

**Comment by benfry** [comment]
Also, given that it's crashing on Open, it probably means there's a bad interaction between your Window Manager and the file selector. You might try editing `preferences.txt` to set:

`chooser.files.native = true`

to 

`chooser.files.native = false`

Or vice-versa, if it's already set to `false`.

**Comment by matwolf** [comment]
Ben,

`chooser.files.native`was set to true in `~/.processing/preferences.txt` and setting it to false did the trick (in both, the installed instance as well as in the downloaded image) and I now see a file open dialog in the Java-style!

Seemingly, there is some incompatibility with the file open routine of Manjaro's (and presumably Arch's as well).

Thanks a lot and sorry for bothering you – I might have figured that out on my own.

Cheers from Vienna/Austria
Matthew

**Comment by benfry** [comment]
Glad it worked; thanks for the update.

**Comment by hamoid** [comment]
Thank you for the info. I had the same thing on Arch, needs to be `chooser.files.native=false`.

By the way the path is now `.config/processing/preferences.txt` (4.x) and no longer `.processing/preferences.txt` (3.x), at least on my system. Changing the latter has no effect in my Processing 4.

**Comment by benfry** [comment]
The config change was requested here: https://github.com/processing/processing4/issues/203 and also described in the release notes for beta 1: https://github.com/processing/processing4/blob/master/build/shared/changes.md#features-and-updates

**Comment by hamoid** [comment]
No issue with the change at all :-) I only replied in case someone finds this thread, changes the setting in `.processing/preferences.txt` and it continues to crash.
