### ISSUE TITLE
i18n support for contributed modes

### ISSUE THREAD

**Issue by codeanticode** [benfry/processing4#236]
Currently, multiple language support is provided for the main Processing app, but this support does not extend to the contributed modes. Each mode could (optionally) provide localized properties files that translate the elements of the mode's UI into different languages.

**Comment by codeanticode** [comment]
A simple implementation of this support is provided with these changes:

* [New addModeStrings() method in Language](https://github.com/codeanticode/processing4/commit/ba0cc9f406bb91831e0194af63f52736c8f0c4db): the mode's base and localized properties in the current language are read into the LanguageBundle.
* [Load mode strings when initializing the mode](https://github.com/codeanticode/processing4/commit/ab9ab26b6108d21c7bcd4552a93a6d135d3b098e). The method addModeStrings() is called right after creating the instance of the mode.

However, an problem with this simple implementation is potential resource collisions, where a mode could overwrite existing strings from the PDE or those used by other modes. Possible ways of handling this problem are adding the name of the mode as a prefix on all the strings, or the full mode package string.

Another possibility could be that modes have their own separate language bundle to avoid collisions without needed to add extra prefixes, but fallback to the bundle if a string from the base PDE is requested.

**Comment by codeanticode** [comment]
@benfry I implemented a way to support multiple bundles per mode:

https://github.com/codeanticode/processing4/tree/mode-lang-support-with-mult-bundles

The functions text(), interpolate(),  etc. are overloaded to accept the calling mode, while keeping the original definitions to be used from the main app, see for example [here](
https://github.com/codeanticode/processing4/blob/13ab22fb377f737b9dd25808918e411c0e30e571/app/src/processing/app/Language.java#L231).

The idea is that the get() function when called from the mode will first try to get the string from the mode's bundle (if it exists) and then from the base bundle if the key is not present. I think this is one possible solution that solves the problem of colliding keys (priority is given to the mode's strings without overwriting existing keys) and the changes to the API are minor (calling the language methods from the moded only need to add the mode object to the call). BTW, the Language instance uses the [hash of the mode object](https://github.com/codeanticode/processing4/blob/mode-lang-support-with-mult-bundles/app/src/processing/app/Language.java#L191) as the key in the map of modes to bundles. Let me know what you think of this approach

**Comment by benfry** [comment]
Ok, added one comment; maybe put this in as a PR so I can review?

**Comment by codeanticode** [comment]
Here: https://github.com/processing/processing4/pull/237

**Comment by benfry** [comment]
Incorporated a subset of that PR based on the feedback there for 4.0 beta 5. See https://github.com/processing/processing4/commit/ddd4b1075398782bd1bdd854c16d2aa61fcc02da
