### ISSUE TITLE
IDE cursor position is wrong based on how long? indented? bracketed? the line is

### ISSUE THREAD

**Issue by Xeloboyo** [benfry/processing4#241]
## Description

In some longer lines the cursor's visual location is weirdly offset to the right. The cursor 'itself' is in the correct position.
Things like bracket indicators are also weirdly positioned.
## Expected Behavior

I expect the cursor to be where it should be I suppose
## Steps to Reproduce

![d171](https://user-images.githubusercontent.com/13158938/128813054-69abfc66-d661-4817-8492-bd0927abe931.gif)
[code.zip](https://github.com/processing/processing4/files/6959152/code.zip)
![d173](https://user-images.githubusercontent.com/13158938/128813408-0fa03775-181d-4c19-9572-e3deac25d744.gif)

## Your Environment

 

* Processing version: 4.0b1
* Operating System and OS version: Windows 10
* Other information: I installed 4.0b1 over 4.0a3 by just overwriting the 4.0a3 install, maybe that killed something
Ive noticed all the UI fonts / splash screen are blurry and weird in the beta too if that helps
![image](https://user-images.githubusercontent.com/13158938/128813565-5e09afb9-259e-44a5-be72-611d23e4723f.png)
## Possible Causes / Solutions

qwq i dunno

**Comment by sampottinger** [comment]
Hello @Xeloboyo! Thank you for this bug report. I worry this may be related to #226. Can you please confirm if you have display scaling enabled?

**Comment by Xeloboyo** [comment]
Thanks, turning it off fixed it. My eyes are kinda strained now thoh haha
