### ISSUE TITLE
Option + Arrow Keys (left or right) shortcut on macOS not working anymore

### ISSUE THREAD

**Issue by ndsh** [benfry/processing4#242]
## Description
When using the Option Key + Arrow Keys the text cursor doesn't jump from word to word. This is macOS specific I believe.

## Expected Behavior
In Processing 3 one could use the Option Key + Arrow Keys (Left or Right) to jump from word to word.

## Steps to Reproduce
1. Press Option Key together with either Left or Right arrow key.
2. Text cursor won't move

## Your Environment
* Processing version: Processing 4.0b1
* Operating System and OS version: macOS Big Sur
* Other information: Fresh install of Processing 4.0b1

## Possible Causes / Solutions
Is something overwriting internally or binding the shortcut in some other way?

**Comment by sampottinger** [comment]
Hello @ndsh! Strange... that is working for me on my 11.4 machine. Just curious, do you have any accessibility tools enabled?

![key_jump_demo](https://user-images.githubusercontent.com/110391/129056972-869df9aa-b3c5-4bae-a675-7a2a139c139a.gif)

**Comment by ndsh** [comment]
hej @sampottinger. thanks for the fast reply. i just double checked everything and it turned out a faulty install of *Little Snitch* somehow wouldn't want to play with processing 4.
after deinstalling little snitch it does work indeed for me, too. oddly enough this behaviour didn't come up with processing 3.

thanks. now i can fully enjoy the new version!
