### ISSUE TITLE
Can't have Processing 3 and Processing 4 open at same time

### ISSUE THREAD

**Issue by micycle1** [benfry/processing4#244]
## Description
When Processing 4 is open and I go to open Processing 3, another instance of Processing 4 opens.
Likewise, when Processing 3 is open and I go to open Processing 4, another instance of Processing 3 opens.

On the contrary, when either is opened when the other is still loading (at its splash screen), then both versions open as expected.

## Your Environment
* Processing version:
* Operating System and OS version: Windows 10

**Comment by benfry** [comment]
That's by design; we don't really want multiple running at once, since they'll fight over sketchbook, preferences, etc. It's the same reason that it doesn't launch multiple instances of the software itself (even on Windows and Linux, where it's possible to do such a thing).
