### ISSUE TITLE
Feature request: make it possible to create libraries and tools from the Processing IDE

### ISSUE THREAD

**Issue by hamoid** [benfry/processing4#248]
## Description

Going from writing Processing sketches to creating tools or libraries is quite a big step. One reason may be that it requires a different IDE and tools like git and ant, so few users attempt this.

I was thinking that there might be more contributions if one could create a tool in the Processing IDE itself. Being able to create a small libraries would solve the hard-to-reuse-code issue in the IDE, enabling users to make collections of commonly used functions accessible in all their sketches. Would be very nice to see more people exchanging their tools in the forums :-)

Was this planned at some stage? What would be the difficulties of getting it implemented?

If creating libraries and tools as they exist today is too complex, might it be possible to introduce something simpler with a more limited API, at least initially? 

- Tools: a way to run sketches from a menu, and those sketches are provided the path of the current document and access to read and write text into the editor? The person writing the sketch could then create, modify and delete assets in the folder, create UIs with Processing's default drawing methods and modify the source code in the IDE.
- Libraries: some way to publish sketches with their classes to a location that makes them available from any sketch they write to help reuse code.

Is this worth thinking about and discussing? Maybe in the forum?

**Comment by benfry** [comment]
Yeah, better discussion for the forum, thanks. Unlikely to be included with the PDE, unfortunately. We have to draw the line somewhere, and opening up the ability to create arbitrary kinds of code like Libraries/Tools/Modes adds an enormous amount of complexity (that I also don't have time to maintain).
