### ISSUE TITLE
http://wiki.processing.org/w/Troubleshooting doesn't work

### ISSUE THREAD

**Issue by ajvdmeij** [benfry/processing4#250]
## Description
Help-. Known problems doesn't get you anywhere

## Expected Behavior
I thought I would see the known problems.

## Current Behavior
It gives a "ERR_NAME_NOT_RESOLVED" error. I thought it was a typo but http://wiki.processing.org doesn't work at all

## Steps to Reproduce

1. Go to Help
2. Known Problems (in Dutch: Bekende problemen)
3. It starts a web page that doesn't exist: http://wiki.processing.org/w/Troubleshooting

## Your Environment

* Processing version: 4
* Operating System and OS version: MACOS Big Sur 11.5.1
*

**Comment by benfry** [comment]
Thanks for letting me know. Looks like the URLs were being set in the translation files, which is unnecessary (since there's no translated version). As a result, URL changes that were made years ago were being overridden with old links like this one.

Fixed for 4.0 beta 2.

**Comment by ajvdmeij** [comment]
That was quick! And great to get a message from you, Mr. Fry: I am a great
admirer of your work!

Arjan van der Meij
The Netherlands

Op vr 13 aug. 2021 om 18:24 schreef Ben Fry ***@***.***>

**Comment by benfry** [comment]
Cheers, thanks!
