### ISSUE TITLE
Startup message is always shown on startup

### ISSUE THREAD

**Issue by johhnry** [benfry/processing4#253]
## Description

It seems that the startup message is always shown on startup. The checkbox should also be checked since it's written "Show this message on startup" but enabling it and disabling it doesn't change anything.

![Screenshot from 2021-08-19 12-12-27](https://user-images.githubusercontent.com/35373357/130052622-263ba643-eae3-4de2-93f1-09d02d391ab9.png)

## Expected Behavior

The checkbox should be checked and unchecking it should hide the startup message.

## Steps to Reproduce

1. Download Processing 4
2. Run `install.sh`
3. Open Processing 4

## Your Environment

 

* Processing version: `4.0b1`
* Operating System and OS version: `Pop!_OS 21.04`

**Comment by alefnull** [comment]
i've been having this same issue since installing on Windows 10 Pro 19042.1165.

**Comment by behreajj** [comment]
For the time being, a workaround on the forums:
https://discourse.processing.org/t/welcome-to-processing-4-window-always-launches/31865
