### ISSUE TITLE
Misspelling in Loading screen in 4.0b1: Replace to "Institute" in "Massachusetts Institue of Technology"

### ISSUE THREAD

**Issue by soprano** [benfry/processing4#254]
## Description

Misspelling in Loading screen in 4.0b1: Replace to "Institute" in "Massachusetts Institue of Technology"

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 4.0b1
* Operating System and OS version: Both Mac and Windows
* Other information:

## Possible Causes / Solutions

Just add the "t".

**Comment by benfry** [comment]
That's what happens when these MIT people start focusing on STEM and ignoring the Humanities.

**Comment by benfry** [comment]
@runemadsen Are you folks using a specific version of Space Grotesk? The moment I try to edit the PSD for the splash screen, the type “updates” and all alternates are lost (even if I manually select them with the glyphs palette).

**Comment by benfry** [comment]
Patched version added for beta 2.
