### ISSUE TITLE
randomSeed() is constraining random()

### ISSUE THREAD

**Issue by REAS** [benfry/processing4#255]
```
int seed = 0;

void draw() {
  randomSeed(seed);
  println(random(0, 100));
  seed++;
}
```

I think this little code should produce values from 0 to 99.000, but it's not, this is what it's printing:

```
72.487625
72.47866
72.50554
72.49658
72.45179
72.44283
72.4697
72.46075
72.41596
72.407
72.43387
72.42491
```

This on Mac OS X Big Sur on an M1

**Comment by jeremydouglass** [comment]
Hey Casey,

That's right, those seeds are semi-deterministic within narrow integer ranges -- similar seeds have similar values. Your code snippet does the same thing on Processing 3 (tested on 3.4).

This is the best way to seed -- do it once:

```
int seed = 0;

void setup() {
  randomSeed(seed);
}

void draw() {
  println(random(0, 100));
  seed++;
}
```

To inspect what is happening, trying jumping up by 1000 every couple of seconds:

```
int seed = 0;

void setup() {
}

void draw() {
  randomSeed(seed);
  println(random(0, 100));
  seed++;
  if(frameCount%120==0) {
    seed+=1000;
    println("**********");
  }  
}
```

...and if you want to jump through seeds and have them be different (which is still less random than the generator itself) then just step by a large number.

```
int seed = 0;

void draw() {
  randomSeed(seed);
  println(random(0, 100));
  seed+= 7919;
}
```

P.S. I learned way too much about Processing's random number generation while working on a cross-mode random number generator, RandomAnywhere that would give the same results in Java, JavaScript, and Python modes. https://discourse.processing.org/t/cross-language-random-numbers/3474

For past discussion of this specific problem, see: https://discourse.processing.org/t/can-i-have-multiple-independent-random-number-generators-with-different-seeds/10125/9?u=jeremydouglass

...and the specific seed correlation in Java's PNRG: https://discourse.processing.org/t/the-first-random-value-is-always-the-same-when-using-randomseed/21700/6?u=jeremydouglass

**Comment by REAS** [comment]
well, thank you @jeremydouglass, this is the first time i've seen it and i appreciate the new information 🌞
