### ISSUE TITLE
Feature Requested: Intellisense

### ISSUE THREAD

**Issue by malviys** [benfry/processing4#256]
Hi there I am new to processing contribution, is anyone working or worked on Intellisense for processing, can you help me regaring that I want to add this feature.

## What I have done.
I have successfully setup my project and able to run the processing environment 

## Your Environment
Processing version: 4.0a5
Operating System and OS version: Windows 11 Pro Build 22000.160

**Comment by benfry** [comment]
I think you might be looking for this option in Preferences:

<img width="269" alt="Screen Shot 2021-10-03 at 12 02 06 PM" src="https://user-images.githubusercontent.com/1623101/135762057-da16c8aa-f40b-4aa7-9087-11aa9155b2fe.png">
