### ISSUE TITLE
Video Library Problem with exported application and with java-processing on OSX Big Sur

### ISSUE THREAD

**Issue by ludiccc** [benfry/processing4#259]
## Description
If I export a sketch that uses Movie library, or try to use it with processing-java I get this error:
(this example is with Loop example, the simpliest one).
`Loop.pde:16:0:16:0: UnsatisfiedLinkError: Unable to load library 'c':
dlopen(libc.dylib, 9): image not found
dlopen(libc.dylib, 9): image not found
Native library (darwin/libc.dylib) not found in resource path`

## Expected Behavior
The program should run.

## Current Behavior
It provides errorr regarding libgc.dylib.

## Steps to Reproduce
1. Load _loop_ sketch.
2. Export Application
3. Copy _data_ folder into the exported folder.
4. Run the application

## Your Environment
* Processing version: 4beta1
* Operating System and OS version: OSX 11.5.2

**Comment by ludiccc** [comment]
Full error log:

xxx$ ./Loop 
java.lang.UnsatisfiedLinkError: Unable to load library 'c':
dlopen(libc.dylib, 9): image not found
dlopen(libc.dylib, 9): image not found
Native library (darwin/libc.dylib) not found in resource path (:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gst1-java-core-1.2.0.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gluegen-rt-natives-macosx-universal.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/video.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jogl-all.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gluegen-rt.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/core.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jogl-all-natives-macosx-universal.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jna.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/Loop.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at processing.video.Environment$POSIX.<clinit>(Unknown Source)
	at processing.video.Environment.<clinit>(Unknown Source)
	at processing.video.Video.initImpl(Unknown Source)
	at processing.video.Video.init(Unknown Source)
	at processing.video.Movie.initGStreamer(Unknown Source)
	at processing.video.Movie.<init>(Unknown Source)
	at Loop.setup(Loop.java:35)
	at processing.core.PApplet.handleDraw(PApplet.java:2159)
	at processing.awt.PSurfaceAWT$10.callDraw(PSurfaceAWT.java:1419)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:354)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libc.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 14 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libc.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 14 more
	Suppressed: java.io.IOException: Native library (darwin/libc.dylib) not found in resource path (:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gst1-java-core-1.2.0.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gluegen-rt-natives-macosx-universal.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/video.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jogl-all.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/gluegen-rt.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/core.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jogl-all-natives-macosx-universal.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/jna.jar:/Users/xxx/Development/Processing/Loop/application.macosx/Loop.app/Contents/Java/Loop.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 14 more

**Comment by codeanticode** [comment]
I think this should be opened in the [processing-video repo](https://github.com/processing/processing-video) and sounds like its probably a duplicate of https://github.com/processing/processing-video/issues/188, which I will work on shortly.

**Comment by ludiccc** [comment]
Sorry, I missed the target (I was heading to processing-video repo but got here instead). Before I close this issue, how does this relates to that issue? I didn't find a workaround. I tried to copy a "macos" folder inside the Loop.app but it didn't work. What I find strange is the error
`java.lang.UnsatisfiedLinkError: Unable to load library 'c':
dlopen(libc.dylib, 9): image not found`

**Comment by codeanticode** [comment]
Actually, I'm not sure. I just exported a sketch using the video library on a macOS 11.5.2 machine, and the resulting application works without any issue. I think I need to look into this more closely. What kind of mac are you using, intel or apple silicon?

**Comment by ludiccc** [comment]
Macbook Pro Intel i5.

**Comment by ludiccc** [comment]
I've been digging around it before posting the issue. The only close thing that I found was this release note for Big Sur:

`New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache.`
[https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes](url)

Since the error code shows a dlopen(libc.dylib) call I assume this is note is being taken in account.

**Comment by codeanticode** [comment]
hmm that's strange because it sounds like I'm using the same versions of all relevant software as you do: macOS 11.5.2 , Processing 4.0b1, video library v2.0 (actually, I'm assuming you are using v2 of the video library, is that correct?) and the exported app does not have any problems. If you open the contents of the app package, do you see something like this:

![image](https://user-images.githubusercontent.com/62246/130865024-821ed89b-cb06-4463-8d8c-3d274a226376.png)

**Comment by ludiccc** [comment]
Yes, I also copied the ´macos´folder as is mentioned on the post on processing-ideo:

<img width="801" alt="Captura de pantalla 2021-08-25 a las 18 24 06" src="https://user-images.githubusercontent.com/475563/130866661-2f71f808-6589-48c6-b523-a8e60a563dfa.png">

**Comment by benfry** [comment]
Closing/locking… This is a duplicate of https://github.com/processing/processing-video/issues/188 and the issue belongs in that repo.
