### ISSUE TITLE
PSurface.setAlwaysOnTop() clears Sketch when using OpenGL renderers

### ISSUE THREAD

**Issue by hx2A** [benfry/processing4#261]
When I run the below code using the `P2D` or `P3D` renderers, the Sketch window gets cleared when `surface.setAlwaysOnTop(true);` gets called. 

```
PSurface surface;

void setup() {
  size(200, 200, P2D);
  fill(255);
  background(255, 0, 0);
  surface = getSurface();
}

void draw() {
  rect(mouseX, mouseY, 10, 10);
  if (frameCount % 500 == 0) {
    println("set always on top");
    surface.setAlwaysOnTop(true);
  }
}
```

When I change it to the default renderer, this does not happen. I can reproduce this on Linux, Windows, and OSX.  Calling `surface.setAlwaysOnTop(false);` has the same result.

I looked through the code and I believe the `resize` flag is being set, which triggers Processing to call `background` using the last used background color.

My expectation of this code is that the window would not be cleared when I call `surface.setAlwaysOnTop()`. Is there something about OpenGL windows that I don't know about that makes this necessary?

* Processing version: 4.0b1
* Operating System and OS version: Windows 10, OSX 11.5.2, Linux/Fedora 34

**Comment by hx2A** [comment]
I took another look at the code to see what `setAlwaysOnTop` actually does:

```
@Override
  public void setAlwaysOnTop(final boolean always) {
    display.getEDTUtil().invoke(false, new Runnable() {
      @Override
      public void run() {
        window.setAlwaysOnTop(always);
      }
    });
  }
```

I observe that the similar methods `setTitle` and `setVisible` do not have the same problem. (`setResizable` does, but at least it kind of makes sense there).

Given how simple that code is, the problem is most likely somewhere in `com.jogamp.newt.opengl.GLWindow` and not in Processing. Still, this is causing a problem for me. Any ideas for what can be done about this before I close out this issue?

**Comment by jeremydouglass** [comment]
> Any ideas for what can be done about this

It seems like your use case is to change activate `setAlwaysOnTop()` _after_ the program has been running for a while.

Assuming that the internals of `com.jogamp.newt.opengl.GLWindow` aren't negotiable -- I haven't looked -- then one workaround of the clearing is to cache the pixels buffer and re-apply it. Doing so with an `image()` command is safe even if the pixels buffer size changed -- I'm not clear on if you are resizing as well / at the same time.

Like this (based on your example above):

```
PSurface surface;
PImage pcache;

void setup() {
  size(200, 200, P2D);
  fill(255);
  background(255, 0, 0);
  surface = getSurface();
}

void draw() {
  if (frameCount % 500 == 1 && pcache != null) {
    image(pcache, 0, 0);
  }
  rect(mouseX, mouseY, 10, 10);
  if (frameCount % 500 == 0) {
    pcache = get();
    println("set always on top");
    surface.setAlwaysOnTop(true);
  }
}
```

**Comment by hx2A** [comment]
Thank you for your thoughts. I was hoping there would be other options. I typed up a response but I don't want to annoy the processing 4 team with a discussion in their repo about a different project. Let's continue the conversation [over here](https://github.com/hx2A/py5generator/issues/5).
