### ISSUE TITLE
OpenCV Demos like BrightestPoint fail with NullPointerException

### ISSUE THREAD

**Issue by jpagliaccio** [benfry/processing4#263]
## Description
Running one of the OpenCV demos like BrightestPoint fails with errors. 

## Expected Behavior
The default file "robot_light.jpg" should display with the brightest pixels highlighted. 

## Current Behavior
The default file "robot_light.jpg" is found but never opens. 

**The Console produces:** 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by gab.opencv.OpenCV (file:/C:/Users/jpagliaccio.USNYBLDT042/Documents/sketchbook/libraries/opencv_processing/library/opencv_processing.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of gab.opencv.OpenCV
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
NullPointerException
NullPointerException
NullPointerException

## Steps to Reproduce
1. On Windows 10 
1. Start Procesing 4.0b1 
1. Fresh install of OpenCV for Processing 0.5.4
1. Restart Procesing 4.0b1 
1. Open and run the BrightestPoint example or other OpenCV example.  

* Processing version: 4.0b1 
* Operating System and OS version: Windows 10 
* Other information:  OpenCV for Processing 0.5.4

**Comment by benfry** [comment]
Please contact the author of the OpenCV library. We can't support every library!
