### ISSUE TITLE
Feature Request: Make menubar and scrollbars editable in themes.txt

### ISSUE THREAD

**Issue by nikolas-sturm** [benfry/processing4#265]
## Description
I was able to change almost every part of the program to my desired coloring, except for two elements, the menubar and scrollbars. 
I would love to see these being editable in `themes.txt` if possible.

## Expected Behavior
Have the Menubar and the scrollbars editable.

## Current Behavior
Haven't found any way to edit these, making it look the following:
![image](https://user-images.githubusercontent.com/42775469/133859359-0b78b7b8-0b6f-4757-976a-bbe78366f332.png)

## Your Environment
* Processing version: 4.0b1
* Operating System and OS version: Windows 11 (not a Win 11 issue tho)

**Comment by dzaima** [comment]
Note that there is a lot to theme about the scrollbars - background, thumb style & color, the buttons at the ends (if you still want them), the little corner joining horizontal and vertical together.
[Here](https://github.com/dzaima/processing4/commit/a380747935cdcdd260bb84576f4e87bd65998106#diff-3f2a0fc413a00f62935e301f150ee3d5259ec45f4e467e353dc19a7bccf28eceR1) I wrote some code to make them dark (search more uses of `DarkScrollBarUI` there).

**Comment by benfry** [comment]
This is one of the remaining items in the theming that I've just not had time to finish yet… coming soon, hopefully.

**Comment by benfry** [comment]
Wiring for this is coming together in beta 9.
