### ISSUE TITLE
Khronos GLTF importer for processing.

### ISSUE THREAD

**Issue by TheBricktop** [benfry/processing4#267]
## Description
I think that there should be a way to import and use gltf and glb models in processing as it is a new industry standard for open model exchange.

## Expected Behavior
There could be a wrapper around javagl library called jgltf (https://github.com/javagl/JglTF) that can import and export gltf and glb

## Current Behavior
I think that there is no way to import glb or gltf scenes

## Your Environment

* Processing version: 3, 4
* Operating System and OS version: windows android linux
* Other information:

## Possible Causes / Solutions
There is a javagl library https://github.com/javagl/JglTF and it could be used as a base for importer and exporter.

**Comment by benfry** [comment]
This would make sense as a Contributed Library, but we don't have anyone to maintain it as part of `core` or the default download.
