### ISSUE TITLE
Movie Maker can't find ffmpeg.exe

### ISSUE THREAD

**Issue by Jean-no** [benfry/processing4#268]
## Description
Whenever I try to create a movie using the movie maker tool, it fails, stating that processing is unable to locate ffpmeg.exe... Even though the file exists in the right folder.

![image](https://user-images.githubusercontent.com/5811393/133933142-83bae874-c7f0-4d8e-904f-0ae414554d47.png)

## Expected Behavior
The good behaviour would be that the movie making process succeeds (as it does with Processing 3)

## Current Behavior
It stops even before trying anything, stating a missing file... That is not missing. So it can be a path problem.

## Steps to Reproduce 
1. open movie maker
2. select a folder of the images to convert into a movie
3. try to create the movie

## Your Environment
 
* Processing version: 4.0b1
* Operating System and OS version: Windows 7
* Other information: some people using Windows 10 have the same problem
* forum link: https://discourse.processing.org/t/movie-maker-ffmpeg-exe-not-found/32178/2

**Comment by benfry** [comment]
The workaround is to put Processing in a folder that doesn't have spaces in its name (`Program Files (x86)` is causing the problem here). But it should also be fixable.

**Comment by Jean-no** [comment]
Damn, I'm getting old, why didn't I guess that immediately ?! Thank you !

**Comment by benfry** [comment]
That's ok, Processing is getting old too. It understands. 

Fixed for 4.0 beta 2.
