### ISSUE TITLE
New default font has fewer symbols than in Processing3

### ISSUE THREAD

**Issue by hkiel** [benfry/processing4#269]
## Description
Symbols like these "♦","♥","♠","♣" are no longer displayed, but show up as crossed out rectangle.
This only happens, when changing the font size. Default font size works.

```
textSize(12);
text("♦♥♠♣",width/2,height/2);
```

## Expected Behavior
I guess many applications rely on one or the other special symbol to exist when moving from Processing3 to Processing4.

## Your Environment
* Processing version: 4.0b1
* Operating System and OS version: macOS Mojave (10.14.6)
* Other information:

## Possible Causes / Solutions
Use a font that uses mostly the same symbols.

**Comment by benfry** [comment]
The more symbols that are included, the larger `core.jar` becomes. You can always use a different font!
