### ISSUE TITLE
Stroke overlap image() in P3D

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#27]
When the render is P3D, the stroke() overlap the image, that's not happen in classic renderer and in P2D. that's happen too in P 3.5.3.

<img width="323" alt="Capture d’écran 2019-11-22 à 18 19 43" src="https://user-images.githubusercontent.com/3332269/69446818-869c6880-0d55-11ea-9710-261f0cb11341.png">

```
PGraphics pg;

void setup() {
  size(300,300,P3D); 
  pg = createGraphics(width,height,P3D);
}

void draw() {
  background(75);
  stroke(255);
  strokeWeight(2);
  fill(0);
  ellipse(mouseX,mouseY,100,100);
  
  pg.beginDraw();
  pg.noStroke();
  pg.fill(125);
  pg.beginShape();
  pg.vertex(34,45);
  pg.vertex(width/2,60);
  pg.vertex(width/2,height);
  pg.endShape(CLOSE);
  pg.endDraw();
  image(pg,0,0);
}
```

**Comment by sampottinger** [comment]
Thank you for your help here and elsewhere @StanLepunK! I did some testing with this and want to check... are you seeing the same behavior in Processing 4 and 3 for this sketch?

**Comment by sampottinger** [comment]
I'll let others weigh in on this but I'm not sure if the correct behavior is defined in this case (the painter's algorithm may not have a guaranteed behavior for 2D operations at the same z coordinate when using P3D). So, I'm not sure if there is a correct answer for if the stroke should be drawn above or below your PGraphics in your sketch. That said, Processing does follow defined behavior if you resolve this ambiguity by making the z coordinate explicit:

```
PGraphics pg;

void setup() {
  size(300,300,P3D); 
  pg = createGraphics(width,height,P3D);
}

void draw() {
  background(75);
  stroke(255);
  strokeWeight(2);
  fill(0);
  
  pushMatrix();
  translate(0, 0, 1);
  ellipse(mouseX,mouseY,100,100);
  popMatrix();
  
  pushMatrix();
  translate(0, 0, 2);
  pg.beginDraw();
  pg.noStroke();
  pg.fill(125);
  pg.beginShape();
  pg.vertex(34,45);
  pg.vertex(width/2,60);
  pg.vertex(width/2,height);
  pg.endShape(CLOSE);
  pg.endDraw();
  image(pg,0,0);
  popMatrix();
}
```

I'll let @codeanticode weigh in but I won't take any actions on this currently. Sorry :(

**Comment by knupel** [comment]
With the translate solution the stroke is totaly remove on my machine: MacBoook / OS Mojave

**Comment by sampottinger** [comment]
Oh funky. Dang :( thank you for pointing that out @StanLepunK. The stroke appears if the circle is on top but not on bottom of the PGraphics. Hummm... I can take a look but, if this is JOGL related, @codeanticode, do you think it is worth fixing this or just waiting for the LWJGL-based renderer? It appears this bug impacts both Processing 3 and 4 (the behavior is consistent in this branch and mainline).

**Comment by codeanticode** [comment]
@sampottinger thanks for the heads up. I will look into it.

**Comment by sampottinger** [comment]
Thanks @codeanticode!

**Comment by benfry** [comment]
This is one of the reasons that P2D exists, because we can set internal variables properly so that strokes appear coincident with their shapes. We can't do this by default in P3D, because of the behavior you see here—that the stroke will hover above other shapes. 

Bottom line, if you want real 2D drawing with OpenGL, use P2D or the default renderer, and this example is the reason why.
