### ISSUE TITLE
Processing 4.0b1 for Windows (Python) - My canvas won't pop up on clicking Run.

### ISSUE THREAD

**Issue by zubin-madon** [benfry/processing4#271]
1. I have downloaded Processing 4.0b1 for Windows (Python). 
2. I downloaded the Python Mode for Processing 3 by J Feinberg.
3. I am running in Python mode. I can see my console below, but the canvas refuses to load.
4. Canvas loads when I press run is Java mode.

The code I typed to test:
`def setup():
    size(600, 600)
    background(255)
    

def draw():
    #noFill()
    fill(255, 0, 0)
    strokeWeight(20)
    stroke(0, 255, 0)
    ellipse(mouseX, mouseY, 200, 100)`
![Processing Screenshot](https://user-images.githubusercontent.com/35947376/134395719-c20ba0c6-466d-4a0d-8ac3-8e2505705bbe.png)
Screenshot attached herewith.

**Comment by raghumina** [comment]
I have the same issue on the Mac OS BigSur with Processing 4.0 beta. 
Using 3.5.x resolved this issue for me.

**Comment by benfry** [comment]
Sounds like a problem with Python Mode, you'll need to report it in that repository.
