### ISSUE TITLE
error when calling smooth() on PGraphics 

### ISSUE THREAD

**Issue by grauwald** [benfry/processing4#272]
## Description

When attempting to set `smooth()` on a PGraphics instance an error is thrown.  

## Expected Behavior

The processing JavaDocs show that a PGraphics instance can receive `smooth()`

## Current Behavior

Calling `smooth()` on a `PGraphics` instance throws the following error:

```
Syntax error on token ".", invalid VariableDeclarator
```

## Steps to Reproduce

1. Run the following code 
```
PGraphics gfx;

void setup() {
 
  gfx = createGraphics(width, height);
  gfx.smooth();
}

void draw() {
}
```
2. Behold the error

## Your Environment

 

* Processing version: Processing 4.0b1
* Operating System and OS version: Mac OS X 11.5.1 (20G80)
* Other information:  iMac (Retina 5K, 27-inch, 2019) Radeon Pro 570X 4 GB

## Possible Causes / Solutions

`smooth()` works fine when applied to the top level of the app and seems to apply itself to subsequent `PGraphics` within.  There is some mention that in Processing 3+ that `smooth()` can only be run once during setup.  Perhaps there is a usage issue with `smooth()` and that it should be removed from the `PGraphics` spec.

**Comment by KevinWorkman** [comment]
I noticed the same problem, but with `noSmooth()` instead of `smooth()`.

I filed a bug in the old repo before I realized this new repo existed, maybe it'll help with debugging: https://github.com/processing/processing/issues/6227

**Comment by KevinWorkman** [comment]
Also, I just confirmed that going back to Processing 3 gets rid of the error.

**Comment by benfry** [comment]
@sampottinger is this a preprocessor regression?

**Comment by pavlus** [comment]
Seems to originate here: https://github.com/processing/processing4/blob/5897e7a34b68576ff33bdd46f2e20e48a1f5a289/java/src/processing/mode/java/preproc/PdeParseTreeListener.java#L686

**Comment by sampottinger** [comment]
It might be @benfry ill take a look

**Comment by sampottinger** [comment]
Sorry for the delay @benfry and @pavlus. Please see #288.
