### ISSUE TITLE
Python Mode has disappeared from the contribution manager window

### ISSUE THREAD

**Issue by tabreturn** [benfry/processing4#273]
Python Mode has disappeared from the Contribution Manager window list.

Not sure where to post this (in Processing or Processing4). Of course, Python Mode is for Processing 3, but I suspect that source code isn't the issue.

More info: https://github.com/processing/processing/issues/6226

**Comment by tabreturn** [comment]
It seems Python Mode has is missing in this list: http://download.processing.org/contribs

I assume this is causing the issue? Not sure how the contents of this file are managed?

**Comment by tabreturn** [comment]
I did some digging and found this: https://github.com/processing/processing-website/blob/main/content/contributions/Python_Mode_for_Processing_3.json

I'm assuming this JSON generates the http://download.processing.org/contribs? Looks like the py.processing.org certificate has expired for py.processing.org. Is this causing the problem?

**Comment by HarryJain** [comment]
Yes I noticed this too. The website is also getting blocked on both Safari and Chrome by default!

**Comment by tabreturn** [comment]
I've [reached out](https://github.com/jdf/processing-py-site/issues/204) to the person who controls the server. I'm assuming this isn't a complicated issue to resolve (SSL certificate renewal), so hopefully things are resolved soon.

**Comment by tabreturn** [comment]
Python Mode has reappeared in the Contribution Manager window 😄
