### ISSUE TITLE
path="/Users/fry/coconut/processing4/java/libraries/svg/library/batik-all-1.14.jar"

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#276]
I have the following problem:

`Project 'processing4-svg' is missing required library: '/Users/fry/coconut/processing4/java/libraries/svg/library/batik-all-1.14.jar'`

This comes from the following file: `java/libraries/pdf/.classpath`.

I think changing it to this should be enought: `path="library/batik-all-1.14.jar"`.

But I can't test right now, else I would have made a PR (maybe later...).

**Comment by benfry** [comment]
Now fixed.
