### ISSUE TITLE
IDE auto-formatting confused by method references (40b1)

### ISSUE THREAD

**Issue by MichelBillaud** [benfry/processing4#279]
## Description

The IDE auto-formatting is confused by method references.  Eg

~~~java
  Predicate<Foo> p = Foo::check;
~~~

turns into 

~~~java
::  Predicate<Foo> p = Foocheck;
~~~

## Steps to reproduce

1. Start a new sketch with

~~~java
import java.util.function.Predicate;

class Foo {
  boolean check() {
    return true;
  };
}

void setup() {
  Predicate<Foo> p = Foo::check;
}
~~~

2. `Ctrl+T`

## Environment

* Processing version: 40b1
* Operating System and OS version: Linux Debian 10.10
* Other information:

**Comment by benfry** [comment]
@sampottinger any chance the new preproc might also be able to give us a better formatter?
