### ISSUE TITLE
Cannot use rotateZ() in P3D

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#28]
These bug is still alive 
https://github.com/processing/processing/issues/5770
maybe this pull can be used, say yesss it's my first pull :)
https://github.com/processing/processing/pull/5821

**Comment by sampottinger** [comment]
Thanks @StanLepunK! Thank you for your PR and I think it looks good. Would you like to open a PR against this repo or would you like me to open a PR for you? I can't do PR reviews on the mainline processing repo but I can do PR reviews here.

**Comment by knupel** [comment]
Nice, I try to do that this week, because at this moment i'm like Ben... no time for me :(

**Comment by sampottinger** [comment]
Thanks @StanLepunK!

**Comment by benfry** [comment]
Fix has been merged.
