### ISSUE TITLE
mixing active and static mode throws the "wrong" error

### ISSUE THREAD

**Issue by epar** [benfry/processing4#290]
## Description
In previous versions of Processing, when mixing active and static modes the error Processing would throw was:

**It looks like you're mixing "active" and "static" modes.**

In Processing 4, the error becomes a lot more cryptic:

**Syntax Error - Missing operator, semicolon, or '}' near 'setup'?**

As this is a mistake a lot of first learners make, it would be really helpful to get the old error message back.

## Steps to Reproduce
```
size(100, 100);

void setup() {
  
}
```

**Comment by sampottinger** [comment]
Great suggestion @epar. A PR will be posted shortly.
