### ISSUE TITLE
displayDensity()

### ISSUE THREAD

**Issue by markcosmic** [benfry/processing4#291]
Greetings,
On my 4K display, Processing 4 outputs/println() displayDensity() as 1. Where as, Processing 3 outputs/println() displayDensity() as 2.

**Comment by benfry** [comment]
If you want help, you've gotta help me out and provide the details requested in the text you deleted from the "New Issue" text box.

**Comment by markcosmic** [comment]
benfry, thank you for responding. I'm not sure what you think I deleted. I'm new at reporting bugs. At this time, I still use Processing 3, but every now and then run a sketch through Processing 4. The bug I reported was 2 sentences. The gist is that on a 4K display, Processing 4 displayDensity() result is 1. I don't think that is correct.  Love what you've doing. Let me know if I can help

**Comment by benfry** [comment]
When you press “New Issue,” you should see the text below. Did it not show up? But this is the information needed—for instance, I have no idea what sort of computer you're using, what operating system, what sort of setup you have with your monitors, etc. 

```
<!--- ** For coding questions, please use https://forum.processing.org ** -->
<!--- ** This form is only for bugs in the software & feature requests ** -->

<!--- ** Also be sure to read the troubleshooting page first: ** -->
<!--- ** https://github.com/processing/processing/wiki/Troubleshooting ** -->

<!--- ** Before posting, please search Issues for duplicates  ** --> 

## Description
<!--- Use a title that describes what is happening. -->
<!--- Give a description of the proposed change. -->

## Expected Behavior
<!--- Bug? Tell us what you were expecting. -->
<!--- Improvement? Tell us how you’d like it to work. -->

## Current Behavior
<!--- Explain the difference from current behavior. -->

## Steps to Reproduce
<!--- Provide an unambiguous set of steps to reproduce. -->
<!--- Including code will make it more likely to be fixed. -->
1.
2.
3.

## Your Environment
<!--- Include details about your environment. -->
<!--- Thousands of people use Processing every day and may not have --> 
<!--- this issue, this might give us clues about why you’re seeing it. -->
* Processing version:
* Operating System and OS version:
* Other information:

## Possible Causes / Solutions
<!--- Optionally, ideas on how to implement the change. -->
```

**Comment by markcosmic** [comment]
I now understand. Thank you for the clarification. I opened a new issue
