### ISSUE TITLE
can't open File

### ISSUE THREAD

**Issue by JonLit** [benfry/processing4#292]
## Description

if i try to open a file with File->Open, the Program freezes for a few seconds and then crashes, also a log file is created in the processing directory

## Expected Behavior

i was expecting to have the Dialog to open a file

## Current Behavior

crashes

## Steps to Reproduce

1.get Processing 4.0b2
2.launch it
3.Try to open a File with File->Open

## Your Environment

 

* Processing version: Processing 4.0b2
* Operating System and OS version: Garuda Linux (Arch, 5.14.12-zen1-1-zen)

Other information: Log File: [hs_err_pid54806.log](https://github.com/processing/processing4/files/7371023/hs_err_pid54806.log)

**Comment by benfry** [comment]
That's a hard crash in Java, which is happening outside Processing. 

But I'd try editing `preferences.txt` to set `chooser.files.native = false` (instead of `true`) and see if that at least gives you a workaround.

**Comment by benfry** [comment]
Looks like others were having this problem, so the discussion has moved here: https://github.com/processing/processing4/issues/306
