### ISSUE TITLE
Background Alpha not showing correctly

### ISSUE THREAD

**Issue by dshot92** [benfry/processing4#293]
## Expected Behavior
This is the same code but in p5js, and correctly show the trails of the spheres.
![image](https://user-images.githubusercontent.com/21959185/138175522-425680b7-93d6-4ca0-bd79-dd53a382d7c3.png)

## Current Behavior
Background draw seems to not support the correct alpha value.
This is the processing version
![frame](https://user-images.githubusercontent.com/21959185/138175784-456c7918-9b8f-4276-b1c2-ba7bf8815e0a.png)

## Steps to Reproduce
```Ball[] balls;
int num_balls = 400;
int ballSize = 4;
PImage img;

class Ball {
  PVector pos;
  int size;
  float speed;
  PVector vel;
  color c;

  Ball(int x_, int  y_, int size_) {
    pos = new PVector(x_, y_);
    size = size_;
    speed = random(3, 5);
    vel = PVector.random2D();
    vel.setMag(speed);
    //c = 0;
  }
  void show() {
    c = img.get(floor(pos.x), floor(pos.y));
    fill(c);
    circle(pos.x, pos.y, size * 2);
  }
  void update() {
    pos.add(vel);
    if (
      (pos.x > width -size && vel.x > 0) ||
      (pos.x < size && vel.x < 0)
      ) {
      vel.x *= -1;
    }
    if (
      (pos.y > height - size && vel.y > 0) ||
      (pos.y < size && vel.y < 0)
      ) {
      vel.y *= -1;
    }
  }
}

void  setup() {
  img = loadImage("images/image3.png");
  size(1080, 1080, P3D);

  balls = new Ball[num_balls];

  for (int i = 0; i < num_balls; i++) {
    balls[i] = new Ball(floor(random(width)), floor(random(height)), ballSize);
  }
  noStroke();
}

void  draw() {
  background( 0, 0, 0, 0);
  for (int i = 0; i < balls.length; i++) {
    balls[i].show();
    balls[i].update();
  }
}
```

## Your Environment
* Processing version: 4.0b2
* Operating System and OS version: Windows 10 Pro Version 10.0.19043 Build 19043

**Comment by benfry** [comment]
Not enough code here to diagnose, but almost certainly not a bug, just a difference in behavior. Please use https://discourse.processing.org/ to get help with it.
