### ISSUE TITLE
Processing IDE is pink on Linux (Raspberry Pi 4 Model B)

### ISSUE THREAD

**Issue by danoszz** [benfry/processing4#294]
## Description

After downloading Processing 4 version `4.0b2` on Raspberry Pi 4 Model B, the IDE windows are instantly pink. While it's a beautiful color, it is probably a bug. Version [processing-3.5.3-linux-armv6hf.tgz](https://pi.processing.org/download/) does work. 

![CleanShot 2021-10-21 at 17 02 31](https://user-images.githubusercontent.com/14123926/138356240-d288070a-2646-4e1a-8613-8946f2cdd7de.png)

## Expected Behavior

Launching the IDE with a visible interface, that is not blocked with a pink layer.  

## Current Behavior

The IDE interface will be visible. After testing with other apps and rebooting, Processing was the only one with this issue, unfortunately. 

## Steps to Reproduce

1.  Download [the 4.0b2 Linux release](https://github.com/processing/processing4/releases/download/processing-1277-4.0b2/processing-4.0b2-linux64.tgz) in /Downloads
2. Extract file `sudo tar -xvf processing-4.0b2-linux64.tgz`
3. Navigate to directory `cd processing-4.0b2`
4. Run installer `sh install.sh`
5. Click on icon on desktop OR `sh processing` click `Execute in Terminal`
6. The IDE takes ~30 seconds to load and turns from yellowish into solid pink 

## Your Environment

 

* Processing version: `4.0b2`
* Operating System and OS version: 
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
* Java Version
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Raspbian-2deb10u1)
OpenJDK Server VM (build 11.0.12+7-post-Raspbian-2deb10u1, mixed mode)
```

## Possible Causes / Solutions

* Conflicting graphic files
* Java version or installation type
* Missing drivers
* My inabilities to work with Linux

**Comment by benfry** [comment]
Wow, that's very… pink. 

Not sure what's happening there, though we don't currently have a maintainer for the Pi so I haven't been posting 4.x releases for it yet. Hopefully someone can pick that up for us, or maybe I'll have to once I can get more of the rest of this 4.x stuff sorted out.

**Comment by benfry** [comment]
Can you give it a shot with the new beta that was posted? Should be in much better shape.

**Comment by Buggem** [comment]
I tried 4.0b4 on my raspberry PI 4 (also model b) running Raspian buster, and it works as expected. I don't know for sure but I think either @benfry or the Java 17 upgrade might of fixed it.

**Comment by benfry** [comment]
Thanks; I'll close this one since they were working for me as well before I posted the release.
