### ISSUE TITLE
Please have a Big Sur Icon.

### ISSUE THREAD

**Issue by pouyakary** [benfry/processing4#295]
As you know the Big Sur has iOS style icons. So it would be so nice if you design an icon like this:

![](https://user-images.githubusercontent.com/2157285/138570037-595e96de-8018-4731-9bd3-e720678dd5ef.png)

![](https://user-images.githubusercontent.com/2157285/138599399-0439a776-a729-4615-8380-cc26fe9dc156.png)

Apple has a [design resource](https://developer.apple.com/design/resources/#macos-apps) for Big Sur icons. I masked the icon template with the current processing icon and it looks nice. I think if you design something specially for the mac it'll look much much better and it will be much more nicer if the processing officially get a good icon.

## Your Environment
* Processing version: 4.0b2
* Operating System and OS version: macOS Big Sur 11.6 (20G165)

**Comment by benfry** [comment]
Will be handled as part of https://github.com/processing/processing4/issues/48
