### ISSUE TITLE
Interface problems when moving the window to a monitor with Windows scaling to 125%

### ISSUE THREAD

**Issue by RaitoWolf** [benfry/processing4#296]
## Description
I'm using a 15 inch laptop with a 1080p display that has scaling set to 125% and a 1080p 21.5 inch monitor connected via HDMI which is set to primary screen. The interface on the external monitor looks fine, but when I move the window to the screen with scaling the interface looks a bit pixelated. The typing line does not align with the end of a letter. 

![image](https://user-images.githubusercontent.com/49078961/138588570-d81e25b6-d32a-43fa-bdf9-ad65e80e7fce.png)

When opening a menu or submenu (for example Sketch -> Import library), the list appears way off and not near the arrow.
It only does this after once after  I move the window on the screen with scaling and once after I put it back on the monitor without the scaling.

![5nqXeSVN1Z](https://user-images.githubusercontent.com/49078961/138588753-24eb99f7-9801-47da-bc5a-b8c5d34f1172.png)

![azIaaLrg83](https://user-images.githubusercontent.com/49078961/138588794-f33ab61b-1dc7-411a-980b-b4fd410aa4ee.png)

When scaling the window from the top left corner it does this, but it's older and doesn't bother that much.
![image](https://user-images.githubusercontent.com/49078961/138588955-b9c53f50-e7b8-4592-8692-b4840de75d42.png)

## Expected Behavior
I expect the interface to look good, the typing bar to be at the end of a letter and the menu to appear correctly

## Steps to Reproduce

1. Open Processing, then move the window to another monitor with 125% (or maybe more) Windows scaling.
2. Look at the interface, test menus.
3. Move Processing back to a monitor without scaling and then test the menus.

## Your Environment

 

* Processing version: 4.0b2
* Operating System and OS version: Windows 10 Enterprise LTSC 1809
* Other information:

**Comment by benfry** [comment]
This should be resolved in beta 5, with additional updates coming in beta 6.
