### ISSUE TITLE
Images cannot be preloaded in settings 

### ISSUE THREAD

**Issue by Schnurber** [benfry/processing4#299]
In version 3 it was possible to preload images in settings. In version 4.0 beta 2 this is not possible, the following code leads to a `NullPointerException`. 
```
void settings() {
  PImage tileset = loadImage("img.png");
}
```

**Comment by benfry** [comment]
Adding another hack for a workaround since it's common, but please don't do that. As stated in the reference: https://processing.org/reference/loadImage_.html

> Images cannot be loaded outside setup() unless they're inside a function that's called after setup() has already run.
