### ISSUE TITLE
No PeasyCam in Processing 4?

### ISSUE THREAD

**Issue by airspaced-nk5** [benfry/processing4#300]
I'm unable to find peasy for 3D camera functionality.  In Processing 4, I go to Sketch -> Imort Library -> Add Library and search peasy, finding nothing. I'd like to be able to access through the contribution manager or if not then do so through some alternate means.  Any help is much appreciated, thanks!

**Comment by rsepierre** [comment]
It seems like peasyCam was not upgraded to support processing4. Although the only thing that seems to be missing is a .jar file in the library folder. Also the author's website (at least the part dedicated to peasyCam) seems to be down.

**Comment by arijit4** [comment]
@airspaced-nk5 I just installed the `PeasyCam Library` on my Windows device just by using the steps that you mentioned and that's working fine too. Hope this works for you now as well!

**Comment by rsepierre** [comment]
The repo doesn't provide the compiled library as .jar, but the website is up again and you can download it there now.

**Comment by airspaced-nk5** [comment]
Was just able to download via the contribution manager on my machine; it appears that this issue has been fixed.  Thanks @arijit4 and @rsepierre for looking into this and helping me out!
