### ISSUE TITLE
An issue with the location of the typing cursor

### ISSUE THREAD

**Issue by asankaSovis** [benfry/processing4#302]
## Description

An issue with the location of the typing cursor

## Expected Behavior

The typing cursor must stay on the character

## Current Behavior

Typing cursor lands on unpredicted places

## Steps to Reproduce

1. Open Processing and start typing

## Your Environment

 

* Processing version: Processing 4.0b2
* Operating System and OS version: Windows 11 Home Single Language 21H2
* Other information: Screen Size 1920 x 1080 60Hz, Scale 175%

## Possible Causes / Solutions

Maybe an issue with determining scaling factor of the screen?
![image](https://user-images.githubusercontent.com/46389631/139875798-ed931eaf-38b2-41f0-b679-d5b2bfea288d.png)

**Comment by hkiel** [comment]
I can reproduce this behaviour on different (win) machines. Seems to be a windows-only problem, as it does not happen on macOS.

**Comment by GvBon** [comment]
Win 11 same problem. Makes impossible to do stuff...

**Comment by jaysonpowers-zz** [comment]
I noticed my display scale was set to 125%, the default, when I changed it to 100% this issue resolved itself, but only at that scale. I'm running windows 11 as well.

**Comment by Farbfetzen** [comment]
Looks like a duplicate of #226

**Comment by benfry** [comment]
Closing as duplicate of #226.
