### ISSUE TITLE
Code completion not working on macOS

### ISSUE THREAD

**Issue by vomtee** [benfry/processing4#304]
## Description
Code completion not working

## Expected Behavior
Code completion for previous declared code parts

## Current Behavior
Pressing ctrl+space does nothing

## Steps to Reproduce

1. Open preferences
2. Check completion with Ctrl+space option
3. Click on OK
4. Restart processing (just in case)
5. Try the following code:

void setup() {
   backgrou
} 

10. Hit ctrl+space

## Your Environment
* Processing version: 4.0b2
* Operating System and OS version: macOS Catalina Version 10.15.7

**Comment by Alriceee** [comment]
Have you tried a different version of processing or a different OS?

**Comment by benfry** [comment]
Have you checked Preferences to make sure that it's turned on?

Are you accidentally using Cmd-Space instead of Ctrl-Space?

**Comment by vomtee** [comment]
Hi benfry,
CMD+Space invokes spotlight on my Mac.
So: No I am using CTRL+Space to invoke code completion.
It works with the Processing Alpha Release (4.0a6) but not with 4.0b2 (the latest I tried).

**Comment by tmatinla** [comment]
Works with beta 3 for me (beta 2 does not work)

**Comment by vomtee** [comment]
Yes, with b3 it works again! Thank you! :)

**Comment by benfry** [comment]
Very weird… I wonder if this was a Java problem, because that's the main thing that's changed (going from Java 11 to Java 17) that might have caused this.

**Comment by davantwillert** [comment]
Works properly with beta 4.0b4
