### ISSUE TITLE
Open/Save dialog causes crash on Linux

### ISSUE THREAD

**Issue by manthanabc** [benfry/processing4#306]
## Description
whenever i try to save any sketch it just crashes
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by processing.app.platform.LinuxPlatform (file:/home/manthan/apps/processing-4.0b2/lib/pde.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of processing.app.platform.LinuxPlatform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release


 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f941def412c, pid=11185, tid=12125

 JRE version: OpenJDK Runtime Environment Temurin-11.0.12+7 (11.0.12+7) (build 11.0.12+7)
 Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (11.0.12+7, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
 Problematic frame:
 C  0x00007f941def412c

 Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/manthan/apps/processing-4.0b2/core.11185)

 An error report file with more information is saved as:
 /home/manthan/apps/processing-4.0b2/hs_err_pid11185.log

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
```
## Expected Behavior
it should save the sketch
## Current Behavior
it crashes

## Steps to Reproduce
1.open any sketch 
2.try to save it
3. it crashes

## Your Environment
manjaro xfce latest stable
openjdk 1.8.0_292

processing 4.0b2

**Comment by Alriceee** [comment]
Have you tried installing other versions of jdk? That's what seems to work for me. (Just asking btw.)

**Comment by alovictor** [comment]
I'm having the same problem in the same environment... Any possible solution?

**Comment by Alriceee** [comment]
You might just have to use a different version of processing, if it doesn't work ill dig further into it.

**Comment by manthanabc** [comment]
It works fine in processing 3.

**Comment by Alriceee** [comment]
My ctrl + space works fine. Try reinstalling processing?

EDIT: I'm using processing 4.0b2

**Comment by manthanabc** [comment]
I did try that also i am using it without installing it. like executing after unzipping it.

**Comment by Calendis** [comment]
I have the same crash with Processing 4.0 b2. I cannot use the Open or Save dialogues

JRE: OpenJDK Runtime Environment Temurin-11.0.12+7

Error log:
https://pastebin.com/mqS3Xcrp

(What... whenever I post the log to pastebin it gets removed...)

**Comment by ZapZaperap** [comment]
Had the same problem with OpenJDK. Moving to the Oracle release fixed this.

**Comment by benfry** [comment]
That's a hard crash in Java, which is happening outside Processing (and if it's fixed by using a JDK, it sounds like a JDK problem). 

But you can also try editing `preferences.txt` to set `chooser.files.native = false` (instead of `true`) and see if that at least gives you a workaround. 

The current source for beta 3 is also using a much newer OpenJDK (17) so it may be resolved there too.

**Comment by benfry** [comment]
Tested on Ubuntu 20.04 64-bit (the only supported Linux release) and it's working fine with beta 3, which uses Adoptium OpenJDK 17.

**Comment by benfry** [comment]
…if you still have issues with beta 3, please report.

**Comment by mario6097** [comment]
Tested on each of the alternatives below, and it still crashes

   1          java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64/bin/java)
   2           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.fc35.x86_64/jre/bin/java)
   3           java-latest-openjdk.x86_64 (/usr/lib/jvm/java-17-openjdk-17.0.1.0.12-13.rolling.fc35.x86_64/bin/java)

do I need a different jdk version?

**Comment by benfry** [comment]
How about the JVM that ships with the software?

**Comment by mario6097** [comment]
Hi,
I deleted v. 4.0b2 and installed v. 4.0b3. It seems to work fine (beside a couple of very minor glitches). 
@benfry Anyway, I am not sure what you did mean exactly, is there a way to config Processing to call the JVM which ships with Processing itself?

**Comment by benfry** [comment]
As long as you're using the download we provide (from Github or processing.org/download), it should be using that by default—I was confused that you were reporting about several other JVMs and nothing about the built-in one.
