### ISSUE TITLE
P2D sesize sketch bigger than screen size

### ISSUE THREAD

**Issue by Simmonsstummer** [benfry/processing4#307]
## Description
 P2D resize
Every time i use P2D ti create an image to save, it's impossible to create something bigger than the screen. For example a 2000x2000 pixel image for a 1080x1920 screen. 
The default render it allows bigger sketches but of course the performance are really low.
I tried all the other render and no one works.
I've found an old issue #[3401](https://github.com/processing/processing/issues/3401) and #[3584](https://github.com/processing/processing/issues/3584) but for mac and the second closed.

## Expected Behavior

I think P2D should behave like the default render and let create bigger than screen sketches.

## Current Behavior

Impossible to creare a sketch size bigger than screen size if using P2D or P3D

## Steps to Reproduce

1. create a sketch with P2D and size bigger than the screen
2. try to save or just to show the sketch
3. You will get: "The sketch has been automatically resized to fit the screen resolution"

## Your Environment

 

* Processing version: 4.0b2
* Operating System and OS version: Windows 10 pro 64bit
* Other information:

## Possible Causes / Solutions

??

**Comment by benfry** [comment]
This is described in the reference for the `size()` command: https://processing.org/reference/size_.html

> The maximum width and height is limited by your operating system, and is usually the width and height of your actual screen. On some machines it may simply be the number of pixels on your current screen, meaning that a screen of 800 x 600 could support size(1600, 300), since that is the same number of pixels. This varies widely, so you'll have to try different rendering modes and sizes until you get what you're looking for. If you need something larger, use createGraphics to create a non-visible drawing surface.
