### ISSUE TITLE
System wide installation Linux

### ISSUE THREAD

**Issue by avlapp** [benfry/processing4#308]
## Description
I want to install processing in /opt, for a system wide installation for all users. 

## Expected Behavior
Copy the downloaded folder to /opt as root. Install it as root.
Menu and desktop files are placed in system wide places 
/usr/local/share/applications
/usr/local/share metainfo 
etc.
Symlink from /usr/local/bin to the processing executable file
Sketchbook in the user folder, when the user opens the application.
(NOTE: I may not 100% correct here, but you know what I mean).

Installing via a package manager (apt) or something like snapd would be easiest of course.

## Current Behavior
It saves to .local/share/*
Not system wide.

Here is a guide who tries to help you with installing in /opt, but I think it should be easier then that: http://www.artsnova.com/processing/installing-processing-ubuntu-linux-tutorial.html

## Your Environment
Linux/Debian/Ubuntu

**Comment by avlapp** [comment]
Hm the xdg tool might install system wide. Ok, will explore further, I might be wrong here. Closing for now.

**Comment by avlapp** [comment]
I've doubts about the Processing installation. It's strange that a local installed third party application has files in /usr/share/applications. One would think that belongs in /usr/**local**/share/applications at least. But /opt is probably the right place to install Processing via the install script. 

It seems the xdg tool being used, places the *.desktop file in /usr/share/applications. I start to doubt, whether that tool is designed for third party applications. Maybe it's only made for packages that are packaged for a package manager (like apt).

When installing a third party application in /opt, all the files should go there it seems. If it's placed somewhere else, it should be a symlink to /opt/processing/... probably.

Info:
https://unix.stackexchange.com/questions/196636/system-wide-desktop-file-installation-for-unpackaged-software
https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html

I've reported a similar issue to the Arduino IDE package:
https://github.com/arduino/arduino-ide/issues/641

Note, I'm not a hardcore Unix expert, but locally installed applications shouldn't belong in /usr/share normally I think.

**Comment by avlapp** [comment]
FYI the new install script for the new Arduino IDE script, checks whether the script is run as user or as root. It doesn't seems to use the xdg tools anymore.
https://github.com/arduino/arduino-ide/pull/356/commits/b4db350ffbc80bf42a177a959f120e73c959a2f2

**Comment by avlapp** [comment]
FYI: the tool desktop-file-install can specify a directory, while xdg-desktop-menu seems to use defaults for user and root.

**Comment by benfry** [comment]
I think the problem may be with the directions you linked to, not Processing—the software works just fine if installed at `/opt/processing`. Just untar it and move the directory to opt and you should be fine.

**Comment by benfry** [comment]
No response; closing.

**Comment by avlapp** [comment]
> I think the problem may be with the directions you linked to.

I don't understand what you mean by this comment, how your comment is exactly related to the issue. In reality there is not much of an issue here probably, just that I doubt whether it is done correctly.

One odd thing I'm experiencing is that when both Arduino and Processing are installed in /opt, Arduino is using the Processing icon. Could be related, I'll explore further. 


This is the install script I use:

* untar
sudo tar zxvf "$download_destination/$processing_file" -C "$processing_destination" || exit 1 

* Install

sudo "$processing_destination/./$app_name-$tag_name/install.sh" || exit 1

https://github.com/avlap/linux-mint-djog/blob/develop/4_install_processing3_stable_ubuntu_djog
