### ISSUE TITLE
Code completion is not working on 4.0b2 macOS

### ISSUE THREAD

**Issue by adon0828** [benfry/processing4#309]
## Description
Code completion is not working on 4.0b2 macOS for me
but It work on 3.5.4 ver

## Expected Behavior
type ctrl + space should happen

## Current Behavior
nothing happen on 4.0b2 , but 3.5.4 is fine

## Your Environment

 

* Processing version: 4.0b2
* Operating System and OS version: OS Monterey 12.0.1
* Other information: Apple M1

**Comment by Alriceee** [comment]
Have you tried using Catalina? Just asking.

**Comment by davantwillert** [comment]
I use Monterey and have the same problem. Unfortunately I cannot go back to Catalina as this update was enforced by my organisation.

**Comment by benfry** [comment]
Have you checked Preferences to make sure that it's turned on?

**Comment by benfry** [comment]
Closing since we have a duplicate at https://github.com/processing/processing4/issues/309
