### ISSUE TITLE
Improved zoom on windows

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#31]
Right now display scaling on Windows 10 causes poor automatic zooming through Swing. This makes the interface appear pixelated and the custom swing elements (primarily JEditTextArea) do not calculate x positions for the caret correctly. After https://github.com/processing/processing4/pull/30, automatic swing zooming will be disabled. While this improves the experience for windows users that have display scaling enabled, this is a poor accessibility experience. I would like to re-enable automatic zoom on Windows and, ideally, extend zoom into native swing elements like the menu bar as well. However, as described in #30, we will need a new way to detect display scaling.

**Comment by sampottinger** [comment]
Hey @benfry, I saw your comment on #30:

> So if I understand this correctly, it's a step backwards and things look worse, but at least it fixes the cursor placement issues?

Here's is where things are at:

|                   | Prior to #30 without display scaling | Prior to #30 with display scaling | After #30 without display scaling | After #30 with display scaling                                                          |
|-------------------|--------------------------------------|-----------------------------------|---------------------------|---------------------------------------------------------------------------------|
| Editor apperance  | ✓                                    | Pixelated                         | ✓                         | ✓                                                                               |
| Cursor placement  | ✓                                    | Incorrect                         | ✓                         | ✓                                                                               |
| UI Size           | ✓                                    | ✓                                 | ✓                         | The scaling does not impact size unless set manually in Processing preferences. |
| Sketch size       | ✓                                    | ✓                                 | ✓                         | ✓                                                                               |
| Sketch appearance | ✓                                    | Not zoomed                         | ✓                         | Not zoomed                                                                       |

Note that this is all referring to windows display scaling and not the zoom in Processing preferences. This changed in Java 11 because of automatic sizing introduced by [JEP 263](https://openjdk.java.net/jeps/263) for Windows.

I am continuing to work on this here inside this bug. Ideally, we would handle the sizing ourselves but the old WindowsPlatform code to detect DPI no longer works under Java 11.

(Update: it looks like sketches are rendering OK but they are not scaled)

**Comment by sampottinger** [comment]
This is effectively a continuation of #21 but, now that #30 has merged, Processing is _usable_ on Windows with display scaling enabled.

**Comment by sampottinger** [comment]
An update on this... It looks like one cannot get to the display scaling via GraphicsConfiguration or the sun.java2d system properties. We might have to use JNA.

**Comment by benfry** [comment]
Bummer; hoped this stuff was gonna get easier with 11+.

**Comment by sampottinger** [comment]
@benfry - same :(

Alright, I might have a solution at https://github.com/processing/processing4/tree/jna_windows_scaling. Hoping to do just a little more testing though...

**Comment by sampottinger** [comment]
I actually could use a little help in testing this. @kllsamui (or other Windows members of the community) - would you be willing to give https://github.com/processing/processing4/tree/jna_windows_scaling a shot? If needed, I can make a build available for you.

**Comment by kllsamui** [comment]
yes, happy to test, please link to build and detail test procedure ( ? change windows settings ? processing settings ?)

**Comment by Volts-s** [comment]
Hi all, I would be happy to help out with testing this or anything else.  I have a Windows 10 desktop and a MacBook Pro with retina display.  I'm not set up to build Processing at the moment.

**Comment by sampottinger** [comment]
Hey there! Very sorry for the delay. Please see https://github.com/sampottinger/processing4/releases/tag/v4.0-alpha-jna-scale. This is provided under the usual license: https://github.com/processing/processing4/blob/master/LICENSE.md. Please follow the following:

 - Start processing
 - Go to processing settings and ensure automatic scaling is on (File > Preferences)
 - Close processing
 - Enable display scaling at 125% (Start > Settings > System > Display)
 - Start processing and note if the interface looks pixelated.
 - Type a long line of text like the following: `aslidfjaoisfdjaioncasldijadlsfkjasdlfjaoicnasodifjsdalfj`. Please record if the cursor is aligned with the text correctly at the end of the line.
 - Close Processing
 - Reset display scaling to 100% (Start > Settings > System > Display)
 - Start processing and note if the interface looks pixelated.
 - Type a long line of text like the following: `aslidfjaoisfdjaioncasldijadlsfkjasdlfjaoicnasodifjsdalfj`. Please record if the cursor is aligned with the text correctly at the end of the line.

Please let me know how that goes and thanks!

**Comment by kllsamui** [comment]
-0- repeat ( old system i call here 4.0 c )

![p4_c_cursorproblem](https://user-images.githubusercontent.com/19226581/71495351-000d0680-2880-11ea-8f8c-d449944209d6.png)

_ download / test 4.0 d scale test
-1- got a problem about a 3rd party library i test / but not have that problem with p 3.5.3

![p4_scale_0](https://user-images.githubusercontent.com/19226581/71495391-1d41d500-2880-11ea-9c83-d8faa0bfdeb7.png)

after deleted that library

-2- win scale 125%

![p4_scale_1](https://user-images.githubusercontent.com/19226581/71495447-6f82f600-2880-11ea-9f01-f3bbb0250338.png)

OK

030 win scale 100%


![p4_scale_2](https://user-images.githubusercontent.com/19226581/71495473-8e818800-2880-11ea-8a4c-2428946a48d8.png)

OK

( i did not play with the processing scaling, only windows, was this correct? )

looks like you solved it
THANK YOU VERY MUCH

**Comment by Volts-s** [comment]
This looks good to my eyes.

Scaling 125 % --------------------
![jna_windows_scaling_125_percent](https://user-images.githubusercontent.com/28009043/71523918-7a9a4e00-28a1-11ea-95fe-0291b52fdda7.png)

Scaling 100 % ------------------
![jna_windows_scaling_100_percent](https://user-images.githubusercontent.com/28009043/71523935-9d2c6700-28a1-11ea-9563-af4e54351f0d.png)

Many thanks to you and Ben Fry for your work on Processing 4.

**Comment by sampottinger** [comment]
Fantastic thank you @Volts-s and @kllsamui! I'll update the PR and get this in.

**Comment by kllsamui** [comment]
can you make a version for RPI?

i would love to compile and run it on/for the Raspberry Pi ( RPI 3B+ hardware for now )

++ and also do it for the several video libraries 
like today buster update breaks my last GLVideo repair 

and the newest RPI buster
works with the https://github.com/processing/processing-video/releases/tag/r6-v2.0-beta4 only
 ( works on RPI 3 and RPI4 different regarding USB video )
but not at all with contribution manager / video / glvideo / 

BUT i would need someone to talk me through.
