### ISSUE TITLE
Support for multiple GL windows with context sharing

### ISSUE THREAD

**Issue by codeanticode** [benfry/processing4#312]
Currently, multiple windows can be created from a Processing sketch, but when using the GL renderer, they do not share the GL context. This means, in particular, that GL resources cannot be shared among the windows, which would the default assumption when creating multiple windows in the first place.

JOGL has introduced some new APIs to enable context sharing between multiple GLWindows:

https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/GLSharedContextSetter.html

GL object synchronization seems to be an issue, specially on Mac:

https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/GLSharedContextSetter.html#synchronization

**Comment by benfry** [comment]
This checks out with the version I'd been hacking on, so I'm merging https://github.com/processing/processing4/pull/313 for beta 3 so we can shake out any potential issues. 

We can keep this open until we're comfortable that it's resolved properly.

**Comment by benfry** [comment]
Fully incorporated for 4.0 beta 3.
