### ISSUE TITLE
Have you tried using Catalina? Just asking.

### ISSUE THREAD

**Issue by mrbbp** [benfry/processing4#315]
YEP, it does not work on Catalina.

_Originally posted by @Alriceee in https://github.com/processing/processing4/issues/309#issuecomment-981856763_

**Comment by benfry** [comment]
Processing 4.0b2 was developed primarily on a machine running Catalina, so yes, I've tried using it there. 

And the next beta is being developed on Catalina, Big Sur, and Monterey machines.
