### ISSUE TITLE
Problem with function size(int arg, int arg) in Class

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#317]
When the function `void size(int arg, int arg)` is used with two arguments in `Class` that's cause a syntax problem when this function is call directly in `void setup()`

Processing 4.0.2b / OS Monterey

Code to reproduce:
```
Truc truc = new Truc();
void setup() {
  size(200,200);
  truc.size(1,1); // problem >>> error à "."
  // func();
}

void draw() {
  truc.size(1,1); // no problem
}

void func() {
  truc.size(1,1); // no problem
}

class Truc {
  void size(int x, int y) {
  }
}
```

**Comment by ritikranjan12** [comment]
Hello, @StanLepunK are you still working on this. I have the answer of this problem,Can i make a Pull Request for the same?

**Comment by knupel** [comment]
@ritikranjan12 sure make a pull request for this problem, because is not my problem, it's a problem for all people on a same configuration of code. So if your fix can help all people GOGOGO make a pull request !

**Comment by ritikranjan12** [comment]
@StanLepunK I am a beginner can you help me to locate this code sample in the project?I can't found it.....or I just make a simple documentation for the above problem?

**Comment by knupel** [comment]
@ritikranjan12 Are youbeginner in Processing or in Java. For you're fix are you build a new Processing from branch with your fix from Processing 4 core ? See https://github.com/processing/processing4/blob/master/build/README.md 
So if you've do that, that's great. After that you can create a pull request from your work branch. 
For the other side I don't know where is exactly the bug to fix, because me too I'm not an expert @benfry add the bug in the Preprocessor... i know just that.

**Comment by tmatinla** [comment]
Cannot reproduce this with 4.0 beta 3 (it does happen with beta 2)
