### ISSUE TITLE
Typing Cursor off by a Character

### ISSUE THREAD

**Issue by Bozo-Cake** [benfry/processing4#318]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version: 4.0b2
* Operating System and OS version: Windows 10 build 19043
* Other information: Opened a Simple Processing Display example from my class files.

**Comment by davantwillert** [comment]
I have the same problem when editing on high resolution screens, both on MacOS and WIn10.
I tried to use File > preferences> interface Scale automatic, and not automatic and 150% as 200% was far too large.

In the 150% the character off by one or two depending where you are on the screen

This is on an updated MacOS Monterey 12.1 and an updated Windows 10 on a MS Surface 7

**Comment by benfry** [comment]
Duplicates of https://github.com/processing/processing4/issues/226 and/or https://github.com/processing/processing4/issues/194
