### ISSUE TITLE
FullScreen in Settings() on MacOS produces strange output surface (initially invisible)

### ISSUE THREAD

**Issue by davantwillert** [benfry/processing4#321]
## Description

I had some troubles with a program using both settings and setup and ran into a bunch of issues. I tried to simplify then as much as possible. When I run the next program, I do not get any output. I also reverted back to 3.5.4 but no luck there either.

```
void settings() {
    fullScreen( P2D, 1 );

    //pixelDensity( 2 );
}

void draw() {
    background( 128, 0, 128 );
}
```

## Expected Behavior

I expect to see a full screen app starting

## Current Behavior

Processing start to run and I see some activity but no output screen
It works on Windows.
![Screenshot 2021-12-20 at 22 38 46](https://user-images.githubusercontent.com/19726596/146837013-3560191c-a747-40dd-bcbc-9403a6ffe91e.png)

## Steps to Reproduce

1. I run the above program
2. If I disconnect the monitor and reconnect it, I see a purple surface on the monitor (, main screen, screen 1 in Processing)
3. I also tried with fullScreen( P2D ) and it did not work either. It works when I go to the FX2D renderer, both on 3.5.4 and 4.0b2

## Your Environment

 

* Processing version: 4.0b2
* Operating System and OS version: MacOS Monterey, 
* Other information: Sketch is supposed to run on Screen 2 in preferences
* It is a Macbook pro 2020 with Intel Core i7

**Comment by benfry** [comment]
Try toggling System Preferences → Mission Control → Displays have separate Spaces and see if that helps. 

It should have warned you about that in the console, is there no message there?

**Comment by benfry** [comment]
I think this was actually https://github.com/processing/processing4/issues/352, which is now resolved.
