### ISSUE TITLE
Feature request: add keyboard short cut to switch tabs

### ISSUE THREAD

**Issue by hkiel** [benfry/processing4#323]
## Description
Make it possible to switch tabs using CTRL+1 .. CTRL+9 for the first nine tabs. Maybe also add some other short cut to go to tab left or right of current tab.
This makes it easier to navigate the code using keyboard only.

**Comment by benfry** [comment]
Switching tabs is already implemented:
<img width="193" alt="Screen Shot 2022-01-10 at 6 27 42 PM" src="https://user-images.githubusercontent.com/1623101/148854725-ed47a7b0-b1cd-422a-a734-afad3526a580.png">

No plans to add ctrl+1 through ctrl+9 at the moment.
