### ISSUE TITLE
relying on default charset to be consistent across instances

### ISSUE THREAD

**Issue by ratchetfreak** [benfry/processing4#336]
https://github.com/processing/processing/blob/a6a86250ffa4041b7d77fbb66dc02e78360c64f0/java/libraries/net/src/processing/net/Client.java#L718-L720

java.lang.String.getBytes() relies on the default charset which is not necessarily consistent between instances. This should be fixed to a portable standard charset

```
  public String readString() {
    byte b[] = readBytes();
    if (b == null) return null;
    return new String(b, StandardCharset.UTF_8); // or whatever charset you want to fix it to
  }

  public void write(String data) {
    write(data.getBytes(StandardCharset.UTF_8)); // must match readString
  }
```

**Comment by dzaima** [comment]
Note that [Java 18 defaults to UTF-8](https://openjdk.java.net/jeps/400), so it's not that far away from when this won't be a problem anymore, and gives a good reason to change things in the meantime.

**Comment by benfry** [comment]
Good point, will go with that.

**Comment by benfry** [comment]
Changed for 4.0 beta 3 with https://github.com/processing/processing4/commit/aab8d8fa50ef48115b5d226d48ed311f2196753c
