### ISSUE TITLE
Problème éditeur : curseur mal positionné, difficulté de modification d'un source

### ISSUE THREAD

**Issue by gcaussy** [benfry/processing4#337]
## Steps to Reproduce

1.
2.
3.

## Your Environment

Windows10
processing-4.0b2
 

* Processing version:
* 
* Operating System and OS version:
* Other information:

## Possible Causes / Solutions

Pas de problème avec la version 3

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing4/issues/226
