### ISSUE TITLE
System.out and System.err collision causing deadlock

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#338]
Report for stdout/stderr collisions causing an error: 

> I linked to the start of the important changes in the `app/src/processing/app/ui/EditorConsole.java` file, but the links can be buggy; [link to final file](https://github.com/dzaima/processing4/blob/27601ab4a395a4a9f4a980b758b590a12a0905c9/app/src/processing/app/ui/EditorConsole.java#L315-L384). (I had to squash the files when the processing 4 history was rewritten to remove large files; probably could've avoided doing that, but didn't bother). `for (int i = 0; i < 10000; i++) { println("out"); System.err.println("err"); }` quickly results in some `java.util.EmptyStackException`s being thrown and running being broken.

_Originally posted by @dzaima in https://github.com/processing/processing/issues/6230#issuecomment-1010020856_

**Comment by benfry** [comment]
@dzaima does that code actually contain a fix? (From your earlier message it sounded like it was a failed attempt.)

**Comment by dzaima** [comment]
I've ran it in an infinite loop for a couple minutes and it hasn't broken (whereas previously it fails in less than a second), so.. probably.

**Comment by dzaima** [comment]
(also, [previous discussion](https://github.com/processing/processing/issues/5775) and [another one](https://github.com/processing/processing/issues/5714))

**Comment by benfry** [comment]
That still caused the problem for me, but I've just checked in a fix that works (at least on this end). With any luck, it should be resolved for 4.0 beta 3.

**Comment by dzaima** [comment]
Can confirm that fix works for me!

**Comment by benfry** [comment]
Thanks for checking, and for the links to those other reports.
