### ISSUE TITLE
Processing 4 displayDensity() on a 4k display result is incorrect

### ISSUE THREAD

**Issue by markcosmic** [benfry/processing4#339]
## Expected Behavior

in using displayDensity() on my 4K display, I was expecting the results to be the same as when I use it in Processing 3
## Current Behavior

in using displayDensity() on my 4K display, the result is "1"
## Steps to Reproduce

1. println(displayDensity());
2.
3.

## Your Environment

 

* Processing version: Processing 4
* Operating System and OS version: window 10 pro 21h1
* Other information: Using an Asus ZenBook UX581GV.308

**Comment by mrbbp** [comment]
Does it suppose to print 2?
what is your width in fullscreen()?

**Comment by markcosmic** [comment]
my screen width is 3840.
in processing 3 I get a 2 result
in processing 4 I get a 1 result

**Comment by benfry** [comment]
Ok, confirmed… Was thinking something has just changed in Java 17 on Windows, but when using Export to Application, `displayDensity()` is returning 2 again. (So I'm looking into it further.)

On the plus side, even when this happens, you're getting the full resolution—it's just that it's not doing the automatic 2x handling for you.

**Comment by benfry** [comment]
Ok, found and fixed. The workaround for older setups was still in place. 4.0 beta 4 will have the fix.
