### ISSUE TITLE
fullScreen() not working on a second display with P2D or P3D

### ISSUE THREAD

**Issue by mrbbp** [benfry/processing4#352]
## Description
`fullScreen(P3D, 2);`  or `fullScreen(P2D, 2);`

if no renderer declared, it's impossible to use "texture"
```
void setup() {
  img = loadImage("img.png");
}

void draw() {
  texture(img);
}
```
error said `texture() is not available with this renderer.`

## Expected Behavior
Should  open fullScreen on second monitor (a 4K display)

## Current Behavior
 Open fullScreen on first monitor
Can't test P3D renderre on second monitor.

## Steps to Reproduce

1. Connect a second monitor to Mac
2. add `fullScreen(P3D, 2);` in sketch's setup()
3. run sketch

## Your Environment

 

* Processing version: 4b3
* Operating System and OS version: MacOS Catalina 10.15.7
* Other information:
iMac 4K 2019 + Samsung 4K TV

## Possible Causes / Solutions

`fullScreen(2);` works produce fullscreen on second monitor.

**Comment by mrbbp** [comment]
Is it possible to change/force renderer after `fullScreen(2)`?

**Comment by benfry** [comment]
Changing the bug title for clarity—so it only breaks when you include `P2D` or `P3D`, correct? That is, `fullScreen(2)` opens on the second display, but doesn't let you use `texture()`?

**Comment by mrbbp** [comment]
> Changing the bug title for clarity—so it only breaks when you include `P2D` or `P3D`, correct? That is, `fullScreen(2)` opens on the second display, but doesn't let you use `texture()`?

Yes that's right.
`fullscreen(2)` open on the second display but have a message about unable to use texture() (and there no texture on my shape)

**Comment by knupel** [comment]
For me when `texture()`is used on Apple MacBook Pro 2018 / OS Monterey.

```
PImage img;
void setup() {
  size(300,300,P3D); // work
  // size(300,300,P2D); // work
  // size(300,300); // display texture() is not available with this renderer
  // fullScreen(2,P2D); // display texture() is not available with this renderer
  // fullScreen(2,P3D); // display texture() is not available with this renderer
  // fullScreen(1,P2D); // display texture() is not available with this renderer
  // fullScreen(1,P3D); // display texture() is not available with this renderer
  // fullScreen(1); // display texture() is not available with this renderer
  // fullScreen(2); // display texture() is not available with this renderer
  // fullScreen(); // display texture() is not available with this renderer
  img = loadImage("BancPublic.jpg");
  texture(img);
}
```

The bug is close with `box()` function, except that's work fine when there is no choice for the screen.
```
void setup() {
  // fullScreen(P3D); // work
  // fullScreen(1, P3D); // box() is not available with this renderer.
  fullScreen(2, P3D); // box() is not available with this renderer.
  
}
void draw() {
  box(200);
}
```

**Comment by benfry** [comment]
@sampottinger Could this be a preprocessor problem? That `fullScreen()` isn't being properly pulled into `settings()`?

**Comment by sampottinger** [comment]
Will look into it thanks @benfry

**Comment by sampottinger** [comment]
Hello all! It appears that the preproc is only bringing in the first arg in rewrite. Just added failing test and will fix.

**Comment by benfry** [comment]
Thanks; just merged that in for beta 5.
