### ISSUE TITLE
Arduino IDE uses Processing IDE's icon when both are installed

### ISSUE THREAD

**Issue by autive42** [benfry/processing4#354]
Expected Behavior:
When only arduino IDE is installed, the software shows up in the menu with the correct icon and when opened shows the correct icon on the panel.

After installing processing, this stops working correctly. The correct icon still shows up in the menu and can be pinned to the panel, but upon opening, opens with processing's desktop icon. The program otherwise works correctly. However, right clicking on the icon and selecting new window will open processing.

[Images](https://imgur.com/a/CZM23Aq)

OS and software:
Linux Mint 20.1
Arduino IDE 1.8.19
Processing 4.0

**Comment by benfry** [comment]
That sounds like an Arduino bug… I can't control what they do with our code.

**Comment by autive42** [comment]
Thanks anyway. I've more or less bypassed it now anyway, I just ran the uninstall script for processing and just manually added a symlink to the executable in /usr/local/bin as well as a barebones xdg .desktop entry and it didn't conflict anymore. Hopefully this comment will help if anyone has the same problem.

Also, thanks for what you guys do. The people who mantain projects like these are the heroes of the software community.
