### ISSUE TITLE
pi.processing.org: download (curl install-arm.sh) goes to 404

### ISSUE THREAD

**Issue by Sciss** [benfry/processing4#356]
Hello. I'm trying to install Processing (4, or otherwise 3) on a Pi 4B:

https://pi.processing.org/download/

The URL shown there (install on existing OS), https://processing.org/download/install-arm.sh , does not exit.

**Comment by benfry** [comment]
Ok, fixed the download link. Unfortunately we don't have a maintainer for RPi at the moment so there's nobody to keep this up to date.

**Comment by Sciss** [comment]
thanks. FTR - the tar.gz worked fine!

**Comment by benfry** [comment]
Great, thanks for letting me know.
