### ISSUE TITLE
Add the ability to specify the settings folder so that Processing can be portable

### ISSUE THREAD

**Issue by SebCanet** [benfry/processing4#362]
Hi, I'm working in schools and I would to use a portable version, usable on USB stick. Also because there are securities, and as I work in different school there are different securities. On Processing3 I didn't find all the option I could find in Processing2 preferences to make quite portable (because it still write in c:\Users\AppDatat\etc

Thanks a lot for helping me.

**Comment by SebCanet** [comment]
Hi,
in fact your solution is only for settings folder. In second time, launch Processing, it will create new files in this setting folder. Open "preferences.txt" and change line 79 "sketchbook.path.four".

**Comment by benfry** [comment]
You can set that by modifying `defaults.txt`. 

The original issue here was that it wasn't possible to override the settings path because it used a native location, and is checked before `preferences.txt` (and `defaults.txt`) are loaded.

**Comment by benfry** [comment]
Added documentation about these features here: https://github.com/processing/processing4/wiki/Preferences#sketchbook-and-settings-location
