### ISSUE TITLE
Error in internal utility function to invert scaling 

### ISSUE THREAD

**Issue by codeanticode** [benfry/processing4#366]
The function invScale() for 2D matrices is implemented incorrectly, with the 1/y term in the wrong place:

https://github.com/processing/processing4/blob/master/core/src/processing/opengl/PGraphicsOpenGL.java#L3876

**Comment by codeanticode** [comment]
Fixed with commit https://github.com/processing/processing4/pull/367/commits/6a1c8bc033ed711e66265450f761a484f8125087, part of this [PR](https://github.com/processing/processing4/pull/367).

**Comment by benfry** [comment]
Now merged for 4.0 beta 4.
