### ISSUE TITLE
Missing support for multi-line string text blocks

### ISSUE THREAD

**Issue by scudly** [benfry/processing4#371]
Java versions 15+ support multi-line strings in the form of text blocks delineated by three double-quotes:

String foo = """
some text
some more text
""";

The linux 4b3 install includes openjdk 17.0.1 2021-10-19, but the above code still generates a syntax error in the IDE.

Text blocks would be a very convenient way to include small shaders without having to resort to a separate external editor, though, granted, they won't have any syntax highlighting or automated formatting.

**Comment by benfry** [comment]
Yeah, was reading about these earlier today. There's a chance we may bounce back to JDK 11 since it seems to be more widely supported, but we'll keep this one in mind if we stick with Java 17. This is a really useful feature for plenty of work that I do as well so I can understand its importance.
