### ISSUE TITLE
Difference between macos-aarch64 and macos-x64

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#373]
Just for information, what the difference between this two new version ? There is one for apple M1.
Because for a novice user is not obvious. After little research, I think the user of Apple M1 must use macos-aarch64, but not sure. 
I just download yet and test it.
Maybe for the next release is better use name like `macos-intel` and `macos-m1` to render the choice easy for what downloading.

**Comment by benfry** [comment]
The download link on the site will be clearer, but as noted in the release notes, we don't recommend using the M1 release because it's not ready yet. The Github links are for people who want to use a pre-release and understand what it is.
