### ISSUE TITLE
Processing sketches initially use default Java “Duke” icon on Linux

### ISSUE THREAD

**Issue by Buggem** [benfry/processing4#377]
## Description

In the taskbar, the processing logo (when open) is a midget penguin holding something.

The name of the app on the taskbar is processing-core-papplet

I'm guessing that this weird penguin icon is the default icon for Java apps that don't have a icon.

I tested (coded my own java jframe) and figured out that the penguin is the icon for Java apps that don't have an icon.

The icon does appear eventually if you wait a while.

## Expected Behavior

Processing logo shows up in taskbar as expected.

## Current Behavior

The taskbar currently displays a penguin holding something.

![Screenshot from 2022-01-28 16-18-21](https://user-images.githubusercontent.com/66670928/151491651-4390082e-08e1-4858-981b-9e6c19f02808.png)

If you hover over the penguin it will say processing-core-papplet.

I guess it fixed with the upgrade to Java 17, but why did this happen?

## Steps to Reproduce

1. Install Ubuntu 18.04.6 LTS on any device.
2. Get the Processing 4.0 b2 tgz and install.
3. Open Processing 4.0b2.

## Your Environment

 

* Processing version: 4.0b2 (fine in 4.0b4)
* Operating System and OS version: Ubuntu 18.04.6
* Other information: Eventually changes to correct logo.

## Possible Causes / Solutions

Works in 4.0b4.

**Comment by benfry** [comment]
If it changes to the correct icon eventually, I think it's out of our control. All we can do is ask the OS/Window Manager to use the correct icon; we don't have any control over when it happens.

**Comment by Buggem** [comment]
Yeah, I think this is a Java issue since I tested it in 4.0b4 and it is working normally (icon appears).

**Comment by benfry** [comment]
Ok, hopefully future Java updates will improve the behavior.
