### ISSUE TITLE
Scaling and AA Issue with Canvas

### ISSUE THREAD

**Issue by pigsteel** [benfry/processing4#378]
## Description

Following b3 (specifically the scaling fixes for windows 10 and 11) the canvas size multiplies by scaling rather than staying at its specified size. Have not noticed any anti-aliasing problems related to this on windows 10 but on windows 11 (on any anti aliasing/smoothing settings) sprites and images are blocky and pixelated

Switching back to b2 fixes canvas

## Expected Behavior

Canvas should follow pixel-measured size defined in size setting

## Current Behavior

Does not do this, multiplies by windows Scale setting and creates anti aliasing issues & pixelation

## Steps to Reproduce

1. Should happen on any windows device running b3 or b4

## Your Environment

 

* Processing version: 4.0b4, 4.0b3
* Operating System and OS version: Windows 11 64-bit 21H2
* Other information: Scaled to 125% (Default)

**Comment by pigsteel** [comment]
![image](https://user-images.githubusercontent.com/43256029/151568619-52348eb0-e8ec-4101-ad6a-b8e77dcc64b7.png)
Pixelated shapes on canvas (Windows 11)

**Comment by pigsteel** [comment]
![image](https://user-images.githubusercontent.com/43256029/151568883-8a1b76f2-bd85-48ca-86c2-2466d927d5a7.png)
Jagged edges on canvas sprite

**Comment by pigsteel** [comment]
![image](https://user-images.githubusercontent.com/43256029/151569718-3700bf0c-ea57-44f9-86c3-12a803773d6e.png)
Expected behaviour in processing b2 (Much smaller window)

**Comment by benfry** [comment]
Beta 4 should now be doing the correct thing… scaling up a sketch if you haven't specified `pixelDensity()`, just like it does on macOS. Check what `displayDensity()` is returning for you (hopefully 2), and if you want to use the 2x version of things, call `pixelDensity(displayDensity())`.

**Comment by pigsteel** [comment]
I'll check. I remember briefly experimenting with those settings and it not fixing anything but I might be wrong

**Comment by pigsteel** [comment]
Oh you said "now" my mistake

**Comment by pigsteel** [comment]
Display density returned 1. Messed around with pixel density to no avail

**Comment by Omnificator** [comment]
I have the same issue on Windows 10, FullHD, scaled to 125%. 
I've tried to override high DPI settings for the editor, java.exe and javaw.exe, with no result. The sketch window remains upscaled and pixelised. displayDensity() is 1.
It is actual for Processing 4.0b5, not for 4.0b3 (unfortunalely I can't return to 4.0b3 because of Windows Defender caution).
```
size(400, 400);
for(int d = 360; d >= 40; d -= 40) {
  circle(200, 200, d);
}
```
Here is the output:
![aa](https://user-images.githubusercontent.com/81038457/152737935-ba532da8-25df-448d-89a7-42dc0e74ed2a.png)

**Comment by benfry** [comment]
Yuck, ok—will have to check into it further. We're not doing any scaling, certainly, it's just that we have to figure out what Windows is doing to be “smart” and shut it off.

**Comment by benfry** [comment]
Ok, sorted out for beta 6. The solution is to detect the current Windows scaling (difficult, requires native code) and then override it to either 1x or 2x based on what's likely to work best in the situation. 

Longer explanations of all of it: https://github.com/processing/processing4/tree/master/build/windows/fenster
