### ISSUE TITLE
Trojan Virus warning in windows defender 

### ISSUE THREAD

**Issue by ElbaMlad** [benfry/processing4#379]
## Description

I am unable to open Processing 4 B4 as windows defender is telling me that there is a trojan virus in the program 

![image](https://user-images.githubusercontent.com/91426175/151569854-3282223e-5106-475c-9cba-795958d9aaa1.png)

## Expected Behavior

Processing opens

## Current Behavior

Processing does not open and windows defender says that there is a virus 

## Steps to Reproduce

 1. Happens on Processing 4 B4

## Your Environment

 

Edition	Windows 11 Home
Version	21H2
Installed on	‎23/‎10/‎2021
OS build	22000.434

## Possible Causes / Solutions

Windows defender

**Comment by benfry** [comment]
Yeah, it's not a trojan. If you can submit it to Microsoft as a false alarm, that'd be great. Unfortunately this happens every few releases. I've tried going through their channels to report this and get help, but have never had any luck.

**Comment by knupel** [comment]
hi @voieducode have any people connection to Microsoft can work on this bug ?

**Comment by benfry** [comment]
Another one from @prisonerjohn… I'd be more concerned if Defender could decide *which* virus or Trojan that Processing is supposedly harboring.

![threat2](https://user-images.githubusercontent.com/1623101/151675549-3863397b-ad39-4dfb-a11a-afe3e6a9cffd.png)

**Comment by benfry** [comment]
Another one from @prisonerjohn… I'd be more concerned if Defender could decide *which* virus or Trojan that Processing is supposedly harboring.

![threat2](https://user-images.githubusercontent.com/1623101/151675549-3863397b-ad39-4dfb-a11a-afe3e6a9cffd.png)

**Comment by benfry** [comment]
Microsoft has updated their definitions to no longer mark it as malware, in maximally passive aggressive fashion:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"

So we're ok “At this time” but apparently it could *later* meet their criteria for “malware or potentially unwanted applications.” It's a shame they can't just say “sorry for the trouble, further investigation shows no malware, and we've updated the definitions.”

**Comment by knupel** [comment]
@benfry, my friend @voieducode know people work as Program Manager in Windows Defender at Microsoft, he had sent a message to this person to talk about this problem. I hope this person can make something To Processing Trojan became a Processing Spartan Hero !!!!

**Comment by voieducode** [comment]
Hi there, as advised by the Defender team, to avoid future false alarm, please do the following:

1. Go to https://aka.ms/wdsi
2. Select "Submit files"
3. Select "Submit file as Software Developer"

This will trigger a process that should avoid a repeat of this issue.

**Comment by benfry** [comment]
Thanks, but I now have to do that each time I make a release? What a frustrating waste of my time.

**Comment by voieducode** [comment]
I don’t know if it’s a one time thing, let me ask.

**Comment by voieducode** [comment]
The reality is more nuanced as explained at
https://www.microsoft.com/security/blog/2018/08/16/partnering-with-the-industry-to-minimize-false-positives/

I know you would prefer not to have to do this, but there is at least a
path for future mitigation.

**Comment by benfry** [comment]
Got it; thanks.

**Comment by Omnificator** [comment]
After some hours of undisturbed working in 4.0b5, I've got that TrojanDownloader alarm ...
I tried to submit core.jar to Microsoft. Their scanner checked only 200 classes and rejected the rest of the archive.
I would be glad to know which of class files has triggered an alarm.
