### ISSUE TITLE
Keys repeat does not work in P3D mode

### ISSUE THREAD

**Issue by vomtee** [benfry/processing4#380]
## Description
When pressing and holding a key in P3D mode it won't repeat.
This holds true for alphanumeric keys and control keys (e.g. cursor keys)

## Expected Behaviour
When pressing and holding a key in P3D mode it should repeat.
This should function for alphanumeric keys and control keys (e.g. cursor keys)

## Steps to Reproduce
1. Start this

```
void setup() {
  size(200, 200, P3D); // line 2
  //size(200, 200);       // line 3
}

void draw(){

}

void keyPressed(){
  println("pressed: " + keyCode);
}

void keyReleased(){
  println("released: " + keyCode);
}
```

2. Press "x" or a cursor key
3. No key repetition
3. comment line 2 and uncomment line 3
4.  Press "x" or a cursor key
5. Key repetition works fine.

## Your Environment
* Processing version: from 3.x to 4b3
* Operating System and OS version: macOS Catalina 10.15.7
* Other information: Intel CPU

**Comment by jaegonlee** [comment]
Key repeat is disabled by default(P2D, P3D). https://github.com/processing/processing/issues/1622
You can enable or disable:
`hint(ENABLE_KEY_REPEAT)` / `hint(DISABLE_KEY_REPEAT)`

**Comment by benfry** [comment]
@REAS looks like we neglected to document this in 3.x and should add it to the `hint()` docs as well as keyPressed/Released. Or with the current reference system, can I just add those edits in the source?

**Comment by vomtee** [comment]
Thank you for the information @jaegonlee and @benfry!
I will give hint() a try. :)
