### ISSUE TITLE
Cursor loses its position in editor using Source Code Pro font

### ISSUE THREAD

**Issue by bitshapesoft** [benfry/processing4#390]
## Description
At certain editor font sizes (like 14, 24, 36), the cursor will not position itself correctly at the right character in a line of text. It gradually falls behind, as if its spacing is less than the actual character spacing.

This seems to only be happening with Source Code Pro font. Andale Mono, Menlo, and other fonts don't seem to have the issue.

## Expected Behavior
The cursor stays at the end of the text line while writing.

## Current Behavior
The cursor gradually falls behind when using Source Code Pro at various font sizes.

## Steps to Reproduce
1. Set the editor font to Source Code Pro, size 14
2. Type a line of code, watching the cursor position fall behind

## Your Environment
* Processing version: 4.0b4
* Operating System and OS version: macOS 12.1 (21C52)
* Other information: M1 Macbook Pro

**Comment by dzaima** [comment]
[duplicate](https://github.com/processing/processing4/issues/194), which is (hopefully) fixed for the upcoming beta 5.

**Comment by benfry** [comment]
Stay tuned for beta 5… In the meantime, most other font options should work fine.
