### ISSUE TITLE
Something broke with the security algorithms (SMTP)

### ISSUE THREAD

**Issue by sgeigers** [benfry/processing4#391]
## Description
An API for Gmail that used to work in older versions (until 3.5.4) gives an error.
The example code can be found [here](https://forum.processing.org/one/topic/javamail.html) (jmlatour' s adaptation to Shiffman's code).
The code works as is on 3.5.4
On 4.0.b1, it gives an error:

```
javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	java.net.SocketException: java.security.NoSuchAlgorithmException: Default SSLContext not available

```
but - taking the file java\conf\java.security from 3.5.4 made it work.

on 4.0.b4, it gave the same error as above, but (just for checking) taking all the java folder from 4.0.b1 made it work (so I assume the problem came with the transition to JDK17)

I am sorry for not using correct terms - this is really out of my comfort zone (though I did learn a lot about security in java these past few days). Feel free to re-post with the correct terms and delete this issue (or give a hint about a simple solution, if there is one?)

## Expected Behavior
Sending email through gmail API should probably work as in previous versions

## Current Behavior
error:
java.net.SocketException: java.security.NoSuchAlgorithmException: Default SSLContext not available

## Steps to Reproduce
Just use the linked code with 4.0.b4 (I expect it to be the same on b3 - didn't check)

## Your Environment
Windows10 PC

## Possible Causes / Solutions
Wish I knew...

**Comment by benfry** [comment]
Yeah, this would be something out of our control—i.e. a change in the default SSL handling in Java 17. Not a Processing bug, it would just be that the library you're using needs to be updated.
