### ISSUE TITLE
PDF / SVG export has zero width, zero height

### ISSUE THREAD

**Issue by dannyneil** [benfry/processing4#396]
## Description
When exporting the examples from either the PDF (https://processing.org/reference/libraries/pdf/index.html) or SVG (https://processing.org/reference/libraries/svg/index.html) library examples, no content is rendered.  Upon inspecting the source of the SVG, the width and height of the SVG is set to zero.  Manually setting the width and height to the canvas size in the SVG source allows the SVG to be rendered correctly.

Example output:
```
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.0//EN'
          'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" style="fill-opacity:1; color-rendering:auto; color-interpolation:auto; text-rendering:auto; stroke:black; stroke-linecap:square; stroke-miterlimit:10; shape-rendering:auto; stroke-opacity:1; fill:black; stroke-dasharray:none; font-weight:normal; stroke-width:1; font-family:'Dialog'; font-style:normal; stroke-linejoin:miter; font-size:12px; stroke-dashoffset:0; image-rendering:auto;" width="0" height="0" xmlns="http://www.w3.org/2000/svg"
><!--Generated by the Batik Graphics2D SVG Generator--><defs id="genericDefs"
  /><g
  ><g
    ><line y2="400" style="fill:none;" x1="0" x2="200" y1="0"
    /></g
  ></g
></svg
>
```
Note the width and height attributes on the `svg` tag, second and third from the end.

## Expected Behavior
Expected that exporting to an SVG would create an SVG that displays the content that was rendered from the canvas.

## Current Behavior
Currently, nothing is rendered when viewing the SVG (in Chrome / Gapplin / Inkscape).

## Steps to Reproduce

1. Run the SVG example:
```
import processing.svg.*;

void setup() {
  size(400, 400);
  noLoop();
  beginRecord(SVG, "filename.svg");
}

void draw() {
  // Draw something good here
  line(0, 0, width/2, height);

  endRecord();
}
```
2. Open the output `filename.svg`.
3. Note that nothing is rendered; inspect the SVG in text and note the width and height are zero.

To fix, manually edit the SVG such that `width="400" height="400"`, and note that it is rendered correctly.

## Your Environment
* Processing version: 4.0b5
* Operating System and OS version: macOS Big Sur, 11.5.2
* Other information: Macbook Pro, Retina, 15", Mid-2015

## Possible Causes / Solutions
Perhaps the canvas size is not being passed to Batik correctly?

**Comment by benfry** [comment]
Yeah, sorry—already fixed for the next beta, just haven't had a chance to post an update: https://github.com/processing/processing4/issues/395
