### ISSUE TITLE
multi-line strings do not terminate properly

### ISSUE THREAD

**Issue by scudly** [benfry/processing4#398]
If you attempt to create a pair of multi-line strings, they are both merged into one string:

```
String foo = """
hi
bye
""";

String bar = """
wee
woo
""";

println( foo );

```
generates

```
hi
bye
""";

String bar = """
wee
woo

```

and the variable "bar" does not exist.

The expected behavior is that foo and bar should each be a double-line string.  "foo" should terminate with the """ line immediately below "bye".  Multi-line strings should terminate at the first line that contains """.

**Comment by sampottinger** [comment]
😑

**Comment by sampottinger** [comment]
Sorry about that @benfry - the rule there was unhelpfully greedy. I’ll fix.

**Comment by sampottinger** [comment]
Just confirming that #400 will fix... Apologies...

<img width="812" alt="Screen Shot 2022-02-10 at 8 45 46 AM" src="https://user-images.githubusercontent.com/110391/153455187-90c0f935-6d0d-490a-b521-82237d3ac368.png">
