### ISSUE TITLE
textMode(SHAPE) performance

### ISSUE THREAD

**Issue by luca-panjer** [benfry/processing4#399]
## Description
Are there any plans on increasing the performance on textMode(SHAPE)?
I don't know if this is possible, but it would be very useful. Text in my application looks extremely pretty with this textmode, but the performance drops to below 10FPS... When I turn off the shape textmode, I achieve more than 100FPS.

I am using the P2D renderer.

**Comment by benfry** [comment]
No plans at the moment, but even without me doing it, or someone else making a patch, you could hack it together… there's a `getShape()` method in `PFont` that you could use to get characters as they're used and lay them out in lines by making your own `text()` function. And as long as those are used with a renderer like P2D or P3D, they should be cached and run fairly quickly. If that sounds too difficult, you might see if someone on the forum can help you through it.
