### ISSUE TITLE
windows defender detected Trojan downloader

### ISSUE THREAD

**Issue by jSdCool** [benfry/processing4#405]
## Description
when extracting the contents of the zip file that I downloaded from processing.org windows defender sent a notification saying: 
Threats found

Detected: TrojanDownloader:java/OpenConnection.PM
Affected Items: processing-4.0b5\core\library\core.jar
threat level severe 

## Expected Behavior
there not to be a virus in processing

## Current Behavior
windows defender deletes the file to protect the computer

## Steps to Reproduce

1.download the most recent version of processing 
2.extract it
3.scan core.jar with windows defender if that doesn't pop up any results automatically

## Your Environment

 

* Processing version: 4.0b5 
* Operating System and OS version: windows 10 20H2
* Other information:

**Comment by benfry** [comment]
Yeah, sorry; it's just a false positive. This happens with every other release or so. For instance: https://github.com/processing/processing4/issues/379

I'm posting beta 6 soon, so I wonder bother dealing with Microsoft on this one, but when I do the next release I'll submit core.jar to Microsoft preemptively so we don't run into this.
