### ISSUE TITLE
PGraphics antialiasing does not seem to work on raspbian

### ISSUE THREAD

**Issue by luca-panjer** [benfry/processing4#411]
## Description
When drawing a shape off screen using PGraphics, it is nice, smooth and antialiased on windows but not when running (exported) on a raspberry pi. Keep in mind, this is **not** processing for pi, this is an application that has been built to an artifact using Intellij IDEA (single compiled jar file) and is being run on the raspberry pi.

## Expected Behavior
I'd expect the shape to be smooth on the pi as well.

## Current Behavior
The shape is not smooth

## Steps to Reproduce
The sketch is made of two files, the main sketch file and the goldencircle (the actual shape)
Both files are here and when combined will produce the result I am describing.

[Main sketch](https://gist.github.com/TGlev/4454b1330a5f8fad0f04f301a2a2dfa8)
[GoldenCircle](https://gist.github.com/TGlev/1c1902784db23e09414e4895b6699b93)

## Your Environment
* Processing version: 4.0b6
* Operating System and OS version: Windows 10, latest update for development (looks good here), raspberry pi 3b+ with latest raspbian and openjdk version "11.0.12" 2021-07-20

## Possible Causes / Solutions
You can make the shape look the same on windows, by replacing the circle.smooth(8); with circle.noSmooth();.
Then they will look bad on both windows and raspbian.
I have tried this with processing 3.5.4 as well, and that has the same result.

**Comment by benfry** [comment]
Does it work when exported directly from Processing 4, especially when the JDK is included? OpenJDK 11 isn't even supported for Processing 4, so I have no idea how that would work.

**Comment by luca-panjer** [comment]
Directly exporting from processing 4 does not fix the problem, gives the same result. It seems like including the JDK only works when exporting the windows version, not the linux 32 bit version.

I tried installing JDK17 on my raspberry pi but it seems like I need the 64 bit os version for that.

**Comment by benfry** [comment]
Ok, set up an SD card with a clean installation of 2022-01-28-raspios-bullseye-armhf on a Pi 4 plugged into an HDMI display and it's working fine. It's possible that the 4 is capable of doing it and the 3B is not, but I'm guessing it's more to do with any other video/display settings you might have in place (i.e. kernel drivers for your display of choice, etc). If it can't get the necessary bit depth, results may be weird.

Here's a test sketch:

```processing
background(255);
for (int i = 0; i < 10; i++) {
  line(random(width), random(height), random(width), random(height));
}
//saveFrame("issue_0411.png");
//exit();
```

Here's the output:

![issue_0411](https://user-images.githubusercontent.com/1623101/154162621-1e2caf85-e01d-4b29-9b85-0dee05a8f869.png)

And here it is running live:

![IMG_4538_half](https://user-images.githubusercontent.com/1623101/154162744-f5340b92-7008-4a60-899f-2b8d8b825340.jpeg)

JDK 17 does not require a 64-bit OS. The 32-bit version of Processing for Pi includes JDK 17 in the download.
