### ISSUE TITLE
You must first install tweak Mode to use this sketch.

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#415]
Processing 4.0b6
OSX

I wanted to open an old sketch which gave me:

> You must first install tweak Mode to use this sketch.

<img width="584" alt="Screenshot 2022-02-17 at 14 33 36" src="https://user-images.githubusercontent.com/738650/154492567-72f6dea8-a9be-45fd-b106-70d3d85a55dc.png">

But since tweak mode is included now, this is not possible.

**Comment by benfry** [comment]
Remove the `sketch.properties` file from the sketch. I'll have to add something to handle this particular case, but that's the fix in the meantime. 

The issue here is that prior to beta 6, `sketch.properties` wasn't being read correctly, so we never ran into it.

**Comment by benfry** [comment]
Workaround added for these 2.x sketches in 4.0 beta 7.
