### ISSUE TITLE
P 4.06b says it has a trojan downloader.....

### ISSUE THREAD

**Issue by x13420x** [benfry/processing4#419]
when extracting P 4.06b says it has a trojan downloader..... by windows defender on Windows 8.1
should I just ignore this......seems like this shouldnt happen......
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by benfry** [comment]
It's a false positive. I've just reported it to Microsoft. Hopefully they'll remove it from the list soon.

Used to happen randomly, seems to be happening more frequently these days: https://github.com/processing/processing4/issues?q=is%3Aissue+sort%3Aupdated-desc+defender+is%3Aclosed
