### ISSUE TITLE
Doesn't install on Windows 10

### ISSUE THREAD

**Issue by ghost** [benfry/processing4#420]
## Description
 Processing doesn't install on Windows 10.
* Processing version: 4.0b6 for Windows 10
* Operating System and OS version: Windows 10 Pro

I have downloaded it several times, extracted the folder and even moved it to the folder of "Program files" and then clicked on the application. Also I clicked on the Java application and both didn't get installed.

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for general troubleshooting questions, especially when it's something like Processing not starting up properly.
