### ISSUE TITLE
Windows Defender protected your PC. (by stopping my favorite coding languages IDE from running!)

### ISSUE THREAD

**Issue by Buggem** [benfry/processing4#421]
## Description

In Windows, clicking processing.exe results in: Windows Defender Protected your PC. (of course they say protected, they want everyone to think they are the best)
Unrecognised app: processing.exe
Publisher: Unknown
And there is only one button (don't run) but if you click "More options" (or something worded similarly) you can select "Run anyway". This is minor, but the thing is that it opens up every time you open the app. So a minor problem --- it doesn't stop the program from running or anything --- but it should be fixed for convenience for Windows users.

By the way, thanks for all your hard work on Processing, It is my favorite coding language and IDE works like a charm on Linux Ubuntu.

## Expected Behavior

Processing.exe opens as usual.

## Current Behavior

Windows Defender thinks there might be a "Threat" to the system if this file is opened.

## Steps to Reproduce

1. Install processing one of the versions listed in environment.
2. Extract the files from the zip, into a folder.
3. Open processing.exe. (not tested with processing-java.exe, I don't have java on windows)

## Your Environment

 

* Processing version: Tested on 4.0 b3 + 4.0 b5
* Operating System and OS version: Tested on Windows 10 and Windows 10 Education
* Other information: One thing - this is not is the trojan virus error that has like 3 posts about it. Windows just doesn't trust it for a start and the error window didn't say anything about it being a trojan. Windows just considered it a "Threat", well, whatever their definition of "Threat" actually is.

## Possible Causes / Solutions

Maybe create a optional .msi or .exe installer -- those need authentication, so it may trust you then rather than just a raw .exe executable.

**Comment by benfry** [comment]
It's a false positive. I reported it to Microsoft five days ago for #419 and here's their reply:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.

Aside from these more esoteric instructions, I'd first try just running Windows Update and rebooting.
