### ISSUE TITLE
Python Mode not running

### ISSUE THREAD

**Issue by tellts** [benfry/processing4#423]
https://imgbox.com/8qgmqENH

https://imgbox.com/DlICUXDk

Downloaded the distribution kit today. Unpacked in Windows 10 Russian version. I downloaded the extension for Python and for creating Gooey. After I saw that it didn't work, I installed two other versions of java:
1. jre-8u321-windows-x64.exe
2. jdk-17.0.2_windows-x64_bin.exe
But it did not help.
Also I was not able to copy the text of the error messages. It is copied, but whitespace is inserted into the text editor instead.

```
C:\Users\admin>java -version
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

C:\Users\admin>java -version
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing))
```

**Comment by tellts** [comment]
[3.5.4 screnshot](https://imgbox.com/LIOtsZZk)

**Comment by benfry** [comment]
Duplicate of https://github.com/processing/processing4/issues/409
