### ISSUE TITLE
Request : Code folding in the editor

### ISSUE THREAD

**Issue by arijit4** [benfry/processing4#426]
Sometimes, it's very annoying, having a large code base, to scroll through all the code and forgetting what I was looking for

**Comment by benfry** [comment]
If it's “annoying” then you should probably be using a full IDE. The PDE is meant for smaller/simpler projects. It's straightforward to use the software in IntelliJ or Eclipse.

Any work on code folding would just be a new editor, which is time best spent on first [implementing a Language Server](https://github.com/processing/processing4/issues/117) and starting fresh with a new IDE.

I've done extensive work on replacing the current text editor, but it would break far too many things (all Modes and Tools, for instance). More details here: https://github.com/processing/processing4/blob/master/app/src/processing/app/syntax/README.md

**Comment by knupel** [comment]
@[arijit4](https://github.com/arijit4) If you don't want use Ecclipse or IntelliJ, you can code with [sublim text](https://github.com/b-g/processing-sublime) or [VS code](https://marketplace.visualstudio.com/items?itemName=Tobiah.language-pde) that's very nice too and easy to use with huge code and navigate between tab.
