### ISSUE TITLE
filter() incompatible with high pixel density on P2D and P3D

### ISSUE THREAD

**Issue by HectorCarral** [benfry/processing4#429]
## Description

Using `filter()` (for example, `filter(GRAY)`, `filter(INVERT)`) in combination with a higher pixel density (set for example with `pixelDensity(displayDensity())`) behaves weirdly when using P2D or P3D.

## Expected Behavior

The filter would be applied with P2D/P3D and high pixel density in the same way as with the default renderer or with default pixel density.

## Current Behavior

The frame is drawn zoomed in on the top left corner. If the default renderer is used, everything works as expected. If no higher pixel density is used, everything works as expected. Interestingly, if we use `saveFrame()`, the saved image looks fine even though it is rendered wrong in Processing. Therefore, I'm attaching here screenshots instead of saved frames.

Default renderer or default pixel density:
<img width="612" alt="Captura de pantalla 2022-03-02 a las 12 37 44" src="https://user-images.githubusercontent.com/26223377/156354763-cbc3bd0c-3d32-4091-a080-8a4b2ba1fab1.png">

High pixel density and P2D/P3D:
<img width="612" alt="Captura de pantalla 2022-03-02 a las 12 37 31" src="https://user-images.githubusercontent.com/26223377/156354788-ee29341c-0573-4a29-be90-9cdbb664328e.png">

## Steps to Reproduce

1. Set P2D or P3D as the renderer.
2. Set a high pixel density.
3. Use `filter()`.

```
void setup() {
  size(500, 500, P3D);
  pixelDensity(displayDensity());
  rectMode(CENTER);
  noLoop();
  
  background(0);
  noStroke();
  fill(255, 0, 0);
}

void draw() {
  rect(width*0.5, height*0.5, width*0.5, height*0.5);
  filter(GRAY);
}
```

## Your Environment

 

* Processing version: Processing 4.0b6 (x64)
* Operating System and OS version: macOS 12.2.1
* Other information: Apple M1 chip

**Comment by codeanticode** [comment]
@benfry just came across this, my quick take on how to fix it is in this PR https://github.com/processing/processing4/issues/429 but I may be missing something.

**Comment by codeanticode** [comment]
I went through the [filter examples](https://processing.org/reference/filter_.html) in the reference, even tried a few more involved cases (rendering into a PGraphics and then applying the filter on the PGraphics object), and so far so good!

**Comment by benfry** [comment]
Ok, shall I merge or are you still checking?

**Comment by codeanticode** [comment]
I'm done checking, you can merge.
