### ISSUE TITLE
core.jar gets flagged by Windows Defender

### ISSUE THREAD

**Issue by EinsMalte** [benfry/processing4#437]
Windows Defender flags `core.jar`

Expected behavior:
Not getting flagged by Windows Defender

Current behavior:
`Core.jar` gets flagged as `TrojanDownloader:Java/OpenConnection.PM`

Reproduction:
Download processing 4 (Windows 64 Bit)

Windows 10: Home Edition
Processing Version 4.03b3

Solution:
Telling Windows Defender to do nothing.

**Comment by benfry** [comment]
Not a virus, see: https://github.com/processing/processing4/issues?q=is%3Aissue+sort%3Aupdated-desc+defender

But you should use the most recent release, since I've been manually submitting the last several to Microsoft so they don't get flagged. It's possible that beta 3 wasn't one of them.
