### ISSUE TITLE
Sketch does not always close on escape key until window clic event received

### ISSUE THREAD

**Issue by yblake** [benfry/processing4#439]
## Description
When running a sketch in fullscreen mode, pressing `escape` key does'nt always close window at first attempt. 

## Expected Behavior
Always close sketch window at first `escape` key press

## Current Behavior
About 50% of the times I run the sketch, `escape` key do not close sketch window. 
After doing a left clic on the screen, and then pressing escape key does correctly close the window.

## Steps to Reproduce
```
void setup() {
  
  cursor(CROSS);
  strokeWeight(0);
  fullScreen();
}

void draw() {
  
  background(240);
  
  fill(255);
  rect(0, 0, width, height);
  
  fill(0xff777777);
  textAlign(CENTER, CENTER);
  textSize(32);
  text(mouseX + ", " + mouseY, width/2, height/2);
}
```
## Your Environment
* Processing version: 4.0b7
* Operating System and OS version: Windows 10 Pro 21H2

**Comment by benfry** [comment]
Not sure there's much we can do here… If it responds after a click, that means the window didn't have focus. We can only request focus (which we do, and which is why it works most of the time) but it's up to the OS whether the window is focused or not.

**Comment by yblake** [comment]
I saw that in [How to Use the Focus Subsystem](https://docs.oracle.com/javase/tutorial/uiswing/misc/focus.html)
"*Exactly how a window gains the focus depends on the windowing system. There is no foolproof way, across all platforms, to ensure that a window gains the focus. On some operating systems, such as Microsoft Windows, the front window usually becomes the focused window. In these cases, the [Window.toFront](https://docs.oracle.com/javase/8/docs/api/java/awt/Window.html#toFront--) method moves the window to the front, thereby giving it the focus. However, on other operating systems, such as Solaris™ Operating System, the window manager may choose the focused window based on cursor position, and in these cases the behavior of the Window.toFront method is different.*"

I'm running on Windows. If `Window.toFront` method is already called in FullScreen mode, seems there is no much  more that can be done as you said...
