### ISSUE TITLE
frame rate drops when drawing large images with scale()

### ISSUE THREAD

**Issue by batroost** [benfry/processing4#443]
I'm working on an update to a simulation project - https://play.google.com/store/apps/details?id=processing.test.portsim_2_0a&hl=en_GB&gl=US - containing roughly 9000 lines of code. Up until now I've been scaling the display within teh code by using a floating value to hold a scaling factor and then multiplying all co-ordinates by this value whenever the display is addressed.

I was keen to try the new Ratio feature, as this would simplify the Java Mode code, bringing it closer to my Android Mode version. I included the windowRatio command, and set my scaling factor to one. There is a single mouseX, mouseY call that was also changed to the new rmouseX etc.

Everything works fine _except that the framerate drops from ~45 fps to just 2fps._

Has anyone else seen a similar framerate reduction when using this new feature, or know what might have caused it? It's a large program so any clue would be helpful.

Thanks

Batroost

Running on: Windows 11, Java mode in Processing4 4.07b. Java, latest Java installed.

**Comment by benfry** [comment]
That's extremely odd… the `windowRatio()` code is very simple (half a dozen lines, tops?) and I've used alternate versions of it in other projects for years. Are you sure it's that code?

This is all it's doing: 

```
    if (windowRatio) {
      float aspectH = width / (float) rwidth;
      float aspectV = height / (float) rheight;
      ratioScale = min(aspectH, aspectV);
      ratioTop = (height - ratioScale* rheight) / 2;
      ratioLeft = (width - ratioScale* rwidth) / 2;
      translate(ratioLeft, ratioTop);
      scale(ratioScale);
    }
```

One other possibility is you might be playing with other settings (any `hint()` options?) that could be affecting rendering, so as soon as you're scaling, you're triggering that behavior.

One way to debug would be doing `translate()` and `scale()` with arbitrary values (to mimic what this does) and see if your frame rate drops.

**Comment by batroost** [comment]
Ben,Thank you for the detailed reply, that's very much appreciated. I'll have a go at the code later with that in mind and let you know how I get on.
Cheers,
Batroost

**Comment by batroost** [comment]
OK, I've given it a try with a simple test. See what you make of this example:

```
// Scaling Test
PImage foreground,background;

void setup() {
  size(1600, 1080);
  // Images are 1600x1080 png files
  background = loadImage("Graphics/Background.png");
  foreground = loadImage("Graphics/Foreground.png");
}

void draw() {
  scale(2);  
  image(background, 0, 0);
  image(foreground, 0, 0);
}

void mouseClicked(){
  println("Frame rate",float(1000*frameCount)/float(millis()));
}
```
As written I achieve a framerate of 3 to 5 fps. If I comment-out the scale command it jumps to ~50fps. I've tried with BMP files instead of PNGs and get the same result. If I take out the image() calls the framerate jumps back up to 50+. So it seems like it's an interaction between the scale() and image() commands that's causing the slowdown?

Do you see the same effect?

Thanks for spending your time on this,

Batroost

**Comment by benfry** [comment]
Hm, wonder if this is just the performance problems of the Java2D renderer… Have you tried with `P2D` or the JavaFX renderer?

**Comment by batroost** [comment]
Thanks. That's something I hadn't thought of trying. 

On this test script the P2D gives ~16fps, JavaFX gives ~60fps. So a big improvement on the Java2D. 

However, each throws up immediate errors when I try to use them on the big project. For example, the JavaFX gives:
```
handleDraw() called before finishing
Could not run the sketch (Target VM failed to initialize).
For more information, read Help ? Troubleshooting.
```
The P2D errors are longer, but begin with:
```
RunnableTask.run(): A caught exception occured on thread main-Display-.windows_nil-1-EDT-1: RunnableTask[enqueued true[executed false, flushed false, thread[0x3954a5c0, main-Display-.windows_nil-1-EDT-1]], tTotal 0 ms, tExec 0 ms, tQueue 0 ms, attachment null, throwable java.lang.RuntimeException: Waited 5000ms for: <778d924a, 6d2de9b5>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>]
java.lang.RuntimeException: Waited 5000ms for: <778d924a, 6d2de9b5>[count 3, qsz 0, owner <main-FPSAWTAnimator#00-Timer0>] - <main-Display-.windows_nil-1-EDT-1>
```
I don't know enough about Java to know if this gives a clue to the problems. It's not a disaster as I can carry on with in-code scaling if need be. It looks clumsy but it still works.

**Comment by batroost** [comment]
Thinking about this I guess the big difference is that in my manual method, although every call to the screen is scaled in the code (e.g. by multiplying the coordinates by a floating value), the images are only resized _once_ for a given display size, then displayed each frame in the same resized form. In using Scale(), the images have to be resized every frame(?), so it's bound to take longer.

**Comment by benfry** [comment]
Possible; though `scale()` should be very fast when rendering to the screen. Though I think you may be hitting a limitation with your hardware: OpenGL should be able to do this at 60fps, but not if you don't have hardware that can handle that. Also, your images are a lot of memory to move around (width x height x 4 = number of bytes) so it may just be an issue with the images themselves. 

But drawing a scaled image should be very fast, as long as you're not using `tint()` or something else that's altering the image pixel data on each frame, in which case it'll be re-binding the texture (in OpenGL) and redoing all the pixels (in Java2D) on each frame.
