### ISSUE TITLE
IDE treats {} brackets as code when they're inside a String, char or comment.

### ISSUE THREAD

**Issue by rotgutcoma** [benfry/processing4#444]
When putting a { or a } on a comment, String, or char, the IDE complains of a missing bracket.
The program compiles fine when this happens, but it prevents most other errors from showing up, making it annoying to debug other code, and it's very hard to spot when the project is large.

![image](https://user-images.githubusercontent.com/53107421/157735119-1308c65c-1721-477f-8c41-5ef58c4bd4ce.png)
![image](https://user-images.githubusercontent.com/53107421/157735571-fa86dd78-71f9-4580-9432-158f713be45c.png)
If it helps, this is Processing 4.0b6 and I'm on Windows 10.

**Comment by sampottinger** [comment]
Will take a look thanks @velaachlorine!

**Comment by benfry** [comment]
Should be resolved in beta 9 which will have the fix from Sam.
