### ISSUE TITLE
Error during download and install of Python Mode for Processing 3

### ISSUE THREAD

**Issue by daNewGuy** [benfry/processing4#445]
Brand new user and programmer here! Hi everyone! Tried the troubleshooting guide and looking up existing issues first - I'm so sorry if this is already resolved... I'll attempt to provide as many details below as possible. Thank you **so much** in advance for your time and attention!

## Description
Unable to add Python mode - receiving this error message when I select (then click Install) 'Python Mode for Processing 3' by Jonathan Feinberg... 

"Error during download and install of Python Mode for Processing 3."

## Steps to Reproduce
1.Launch Processing
2.At the top right corner, click the "Java" button
3.Select "Add Mode" in the drop down
4.Select "Python Mode for Processing 3" & click "Install

## Your Environment
* Processing version: 3.5.3
* Operating System and OS version: Windows 7 XP1
* Other information: **Work Laptop**

## Possible Causes / Solutions
This is a work laptop, I suspect the root cause may be networking. 

Is there a way to manually download and install Python mode?

**Comment by pacien** [comment]
I'm facing the same issue with Processing 3.5.3 on NixOS (unstable channel).
The same error appears when attempting to download any other library, tool, example or mode.

It is nevertheless possible to download and install those manually by finding the URL of the appropriate ZIP file in the [contribs db](http://download.processing.org/contribs), extracting it and putting the content in the appropriate folder in ~/sketchbook.

**Comment by villares** [comment]
To manually download and install Python Mode:
Download from: http://py.processing.org/3/PythonMode.zip
Unzip, and copy `PythonMode` into: `User/Documents/Processing/modes/`
(on *nix it's `user/sketchbook/modes/`)

**Comment by maxdevjs** [comment]
@pacien , how did you get Processing to work on NixOS?

**Comment by pacien** [comment]
> @pacien , how did you get Processing to work on NixOS?

I just used the package: https://nixos.org/nixos/packages.html?attr=processing

**Comment by maxdevjs** [comment]
Thank you @pacien . I guess you are on NixOS 19.09 channel... I am still on 19.03 and seems that the Processing package is still the broken one. If so, I should migrate to 19.09, right?

**Comment by pacien** [comment]
> Thank you @pacien . I guess you are on NixOS 19.09 channel... I am still on 19.03 and seems that the Processing package is still the broken one. If so, I should migrate to 19.09, right?

Indeed, it works fine on 19.09 and the unstable channel, besides the downloading problem in the contribution manager as described in this issue.

**Comment by maxdevjs** [comment]
Thank you again, @pacien , now it works. And, in fact, I was able to install from Processing itself only the `Extended Code Completion` tool.

**Comment by benfry** [comment]
Please give this a try with Processing 3.5.4 once it's available. With any luck there should be more detail about what failed (a stack trace) in the console when this happens.

**Comment by benfry** [comment]
3.5.4 is now available here: https://github.com/processing/processing/releases/tag/processing-0270-3.5.4

Please try it out and let me know what happens so we can get this resolved.
