### ISSUE TITLE
Add the contributing process and policy to the contributing file

### ISSUE THREAD

**Issue by arnoudvanderleer** [benfry/processing4#451]
The `CONTRIBUTING.md` file does an awesome job at showing people all the resources that they can go to.
However, a policy on what kind of contributions are accepted (bugfixes and "missing core features") and what kind of contributions would not be welcome (new features, refactorings), and why (something about maintainability) is not mentioned.

From [the response to this pull request](https://github.com/processing/processing4/pull/422), it appears that new features are usually not accepted straightaway, but should be added to a library, until they prove to be so central to the functionality of Processing that they should be added to the core. It would be good to explicitly state such things in the contributing file, to set expectations straight.

A policy of "add an issue for a new feature, before you implement it" probably won't harm anyone and will make sure that there is room for discussion before any code is written.

**Comment by arnoudvanderleer** [comment]
If I have time, I will make a draft for this in the near future if that is okay. Are there any things I should include in that?

**Comment by benfry** [comment]
Lots more details now added: https://github.com/processing/processing4/blob/master/CONTRIBUTING.md

**Comment by arnoudvanderleer** [comment]
Thanks! This adds a lot of useful information!
