### ISSUE TITLE
README.md in build gives intructions for JDK 11 while project requires JDK 17

### ISSUE THREAD

**Issue by toshan-luktuke** [benfry/processing4#453]
## Description

The current README in build that gives instructions for building Processing 4 all links to the JDK 11 release of Open-JDK, whereas the project currently uses JDK 17.
## Expected Behavior

README should have instructions to install JDK 17.

## Your Environment

 

* Processing version: Processing 4.0 beta 7
* Operating System and OS version: Windows 10
* Other information:

## Possible Causes / Solutions

Change the README in build so that it suggests the required version

**Comment by benfry** [comment]
Was waiting until we were sure about the move to 11. With 17 now available via `apt` on Raspberry Pi, we're safe to make the switch.
