### ISSUE TITLE
Fix new java features

### ISSUE THREAD

**Issue by Robocraft999** [benfry/processing4#455]
## Description
Many of the new features from java 8 to java 17 (See here: [https://ondro.inginea.eu/index.php/new-features-in-java-versions-since-java-8/]()) are not usable in Processing because it thinks you made a syntax error if you try to use them.

## Expected Behavior
You can use the features.

## Current Behavior
Processing throws a syntax error although it should work.

## Steps to Reproduce
1. Try to use this #428 or this `record Point(int x, int y) { }` for example in Processing

## Your Environment
* Processing version: 4.0b7
* Operating System and OS version: (on this laptop:) Windows 7 Professional 64 bit last version (should be same result on Windows 10)

## Possible Causes / Solutions
I think that's because Processing's error system doesn't know the new syntax and therefore doesn't allow you to run the code even though it actually works.

**Comment by benfry** [comment]
If there's a feature you'd like to see, please file an issue for it, as seen in #428. At the moment nobody has time to just sit down and implement “everything,” so at least this can help us prioritize, and maybe someone can help contribute that particular fix.
