### ISSUE TITLE
Constants defined in tab not initialized when accessed from outside a function in the main tab.

### ISSUE THREAD

**Issue by damellis** [benfry/processing4#463]
## Description
It appears that constants that are defined in a secondary tab of the sketch aren't yet defined when they are accessed from a function or constructor call from outside a function in the main tab. Instead, I get 0 for an int constant and null for a String constant.

## Expected Behavior
I would expect the actual value of the constant to be used.

## Current Behavior
Currently, the default value of the constant is used. If I move the constant definition into the main tab, the problem goes away. Same if I call the function from inside a function in the main tab.

## Steps to Reproduce
Main tab code:

```
int f = foo();
String s = str();

void setup()
{
  print(f);
  println(foo());
  print(s);
  println(str());
}
```

Secondary tab code:

```
int FOO = 1;
String STR = "abc";

int foo() { return FOO; }
String str() { return STR; }
```

Output:

```
01
nullabc
```

## Your Environment
* Processing version: 4.0b7
* Operating System and OS version: macOS 10.14.6

## Possible Causes / Solutions
Maybe there's some pre-processing happening on the tabs that hasn't taken effect yet when calling functions outside of a function?

**Comment by dzaima** [comment]
This is regular java behavior - variables are evaluated in the order of appearance, regardless of whether or not they're constants or more complicated expressions. Processing internally concatenates all your files together, with the main tab being the first, so the following reproduces your problem too:
```java
int f = foo();
String s = str();

int FOO = 1;
String STR = "abc";

int foo() { return FOO; }
String str() { return STR; }

void setup() {
  print(f);
  println(foo());
  print(s);
  println(str());
}
```

For an example of why ordering is needed, see this code:
```java
int fooVar = foo();
int barVar = bar();
int foo() { return barVar; }
int bar() { return fooVar; }
```
It's valid code, and doesn't do anything wrong in any single part that'd be reasonably detectable, so it must do something. Seeing uninitialized variables is what the designers of Java decided for it to do.

**Comment by damellis** [comment]
Huh, fascinating! Thanks for the fast, thorough response.
