### ISSUE TITLE
BUG: Processing on 4K Windows is Broken

### ISSUE THREAD

**Issue by BrendaEM** [benfry/processing4#464]
Hi,

Processing sketches seem not fixable using the usual Windows 10 high-dpi compatibility fixes.
Perhaps I am setting the wrong thing, but...

I have a 4K monitor.
I have Windows 10, patched, current video drivers.

I need the sketch to run pixel-to-pixel with no scaling.
Windows keeps pixel-scaling my sketches and turning the result into crap.
Normal comparability techniques on processing.exe seem to have no effect.
Should I be adjusting java or something else, somewhere?

Given that the screenshot is 4K, as you can see the window is supposed to be 1280x720. Obviously it has been scaled, and badly.

(Thank you for reading this far.)

![Scaling](https://user-images.githubusercontent.com/20957198/161395424-c6498ef0-602d-4df3-bf61-8b664467c14f.jpg)

**Comment by dzaima** [comment]
AFAICT you need to add `pixelDensity(displayDensity());` in setup/settings to disable automatic scaling.

If that doesn't work, showing your `setup` code (or `settings` if you use that) would be useful for whoever knows more than me about this.

**Comment by BrendaEM** [comment]
Dzaima,

Thanks for the reply, but that doesn't work. Settings will accept it, but it seems to make no change.

_It's a bug. Processing is broken on machines with 4K monitors transportability._

**Comment by benfry** [comment]
The “badly” part likely has more to do with the rest of your code—i.e. if you're using `pixelDensity()` properly, you may be using `createFont()` with OpenGL and the size is small, so the output is pixelated. 

But what you're looking for is to *disable* the way that Windows handles hi-res displays and scaling. This would mean sketches going back to being too small on high resolution screens, which most users would be unhappy with. There isn't a way to do that from inside the PDE, but you could use another IDE and mess with the `-Dsun.java2d.uiScale.enabled` setting when running the sketch to get the result that you want.
