### ISSUE TITLE
Running processing-java with ssh on Rpi4

### ISSUE THREAD

**Issue by Taxicletter** [benfry/processing4#466]
Hi,

I have Processing 4 on Rasp Pi 4 (with full desktop). I can run the sketch from the terminal with: processing-java --sketch=path-to-sketch --present.
If I login from my macbook with ssh as pi and run exactly the same command, I get this error:
```
Cannot run sketch without a display. Read this for possible solutions:
https://github.com/processing/processing/wiki/Running-without-a-Display
Finished.
```
I also tried with DISPLAY=:0 before that command and that gave the same error.

**Comment by benfry** [comment]
Are you using `ssh -Y` so that X is forwarded properly?

**Comment by Taxicletter** [comment]
Thank you Ben, I didn't know about ssh -Y (I'm a beginner since a long time :-) ).
I tried and it doesn't give an error, but it hangs in that command, without anything happening.

**Comment by benfry** [comment]
Have you installed X on your machine? For instance, on macOS you need to install https://www.xquartz.org/

**Comment by Taxicletter** [comment]
I hadn't that installed. I don't understand though, I thought that if I logged in from my mac, that using the terminal is like using the terminal on the target machine, my Raspberry Pi in this case.

I installed X like you said, and then the sketch runs in X on my mac, but that's not what I want. I want it to run on the Pi, but controlled from my mac.

So I can project visuals, processing sketches, with my Pi and a beamer, and switch the sketches from my mac.

**Comment by benfry** [comment]
Sure, that's a different thing. But this is a better discussion for the forum, since it's not a Processing issue. In fact it's more of a general Linux/window manager question—how to start an app from SSH but have it show up on an attached display.
