### ISSUE TITLE
PGraphics SVG and the <g> or group tag

### ISSUE THREAD

**Issue by SleepyBrett** [benfry/processing4#467]
## Description
Because the documentation on this general feature is quite incomplete/confusing I'm unsure if this is a feature request or just a documentation fail.

Ultimately I would like, while using the svg output detailed here https://processing.org/reference/libraries/svg/index.html to place lines into the SVG in groups which when annotated properly will show up in inkscape as layers.

## Expected Behavior
When you create a new layer in inkscape and place some objects in it and save to svg, when you inspect that in a text editor you will find something to the effect of:

```
<g inkscape:label="999 registration" inkscape:groupmode="layer" id="registration" sodipodi:insensitive="true" >
<line x1="0.00" y1="20.00" x2="540.00" y2="20.00" style="fill:none;stroke:black;stroke-width:0.5;"/>
</g>
```

I would like to be able to add these groups/layers programatically. This would require a method to create the group with some kind of freeform ability to add these namespaced attributes/values (inkscape:label, inkscape:groupmode).

## Current Behavior
It's unclear to me if the current rederer has a feature for this or not.

## Steps to Reproduce
Given that this is a feature request there are no reproducable steps.

## Your Environment

 

* Processing version: 4.0b7
* Operating System and OS version: osx 12.3.x
* Other information:

**Comment by benfry** [comment]
Nah, the feature isn't available. We don't have a way to specify layers or groups in the API at the moment.
