### ISSUE TITLE
preprocess() should return PreprocessorResult object

### ISSUE THREAD

**Issue by codeanticode** [benfry/processing4#469]
Currently, the preprocess() method in JavaBuild [returns](https://github.com/processing/processing4/blob/master/java/src/processing/mode/java/JavaBuild.java#L382) a string value containing the class name of the sketch, that is queried from the PreprocessorResult object created inside the method. However, it might be better it if preprocess just returns the PreprocessorResult object, which contains additional useful information such as the sketch's renderer.

**Comment by benfry** [comment]
#470 now incorporated for 4.0b8.
