### ISSUE TITLE
Streamlining the JDK downloader

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#47]
Did some work in https://github.com/processing/processing4/commit/1ff826b843fa8df1b7c9d561d4614484f232b8b3 to clear out parts of the Downloader that won't be used… I'm not interested in supporting JDK 8 downloads or Oracle downloads, so that removes some complexity. 

Wanted to go a little further but wanted confirmation from @sampottinger before doing so: 

* I think we can get rid of cookie support, right? That's only used by Oracle? 
* Do we need both `version` and `train`? 
* If the JRE is truly gone in 11, I'll remove all JRE support, since it seems to just alias to JDK

With all that cleared out, that code should be a lot more readable.

**Comment by sampottinger** [comment]
Hey! Thanks for cleaning up in there. As you can tell, I didn't revisit it after we decided to cut JDK 8. 

> I think we can get rid of cookie support, right? That's only used by Oracle?

I believe so.

> Do we need both version and train?

I would still hold on to train. If you want to fix to a version of java, you'll need the train.major.minor+build (the latest JDK is `jdk-11.0.6+10`).

> If the JRE is truly gone in 11, I'll remove all JRE support, since it seems to just alias to JDK

Sounds good. To be fair, we can "[make our own JRE](https://openjdk.java.net/jeps/282)" to reduce the build size but [there is no official JRE anymore](https://openjdk.java.net/jeps/220).

**Comment by benfry** [comment]
Yeah, not interested in maintaining a custom JRE to save a few (or many MB)… Too many vectors of badness to be opened up with that. I'll give it another whack.

**Comment by benfry** [comment]
Things now cleared out to reflect our current simpler constraints.
