### ISSUE TITLE
Vertical Scroll Bar In IDE Editor Is Just a Thin Line

### ISSUE THREAD

**Issue by billv923** [benfry/processing4#473]
In your latest 4.0 beta releases (4.0b6 & 4.0b7) I noticed that the vertical scroll bar on the right side of the editor is just a thin horizontal line making it difficult to click on with the mouse. Version 3.5.4 didn’t have this problem.

**Comment by benfry** [comment]
Can you share a screenshot? What OS are you using?

**Comment by billv923** [comment]
Ben,
Please see attached screenshot. I am using Windows 10 OS.

Thanks.
Bill van Leeuwen
![Vert_Scroll_Bar_Screenshot](https://user-images.githubusercontent.com/102330834/164789168-b2239092-e41b-4ce7-ac77-02ad43960de7.PNG)

**Comment by benfry** [comment]
Nothing attached; you may need to use the site rather than replying to the email.

**Comment by ExpandingS** [comment]
The bar is resized based on how many lines there are, what was the behavior in 3.5.4? Perhaps a solution could be to increase the minimum size of the bar?

**Comment by benfry** [comment]
How many lines is that file @billv923? 

I believe the scroll bars have always been proportional @ExpandingS, but yeah, it sounds like we need a minimum size.

**Comment by benfry** [comment]
All set for 4.0 beta 8, thanks for the report.

**Comment by billv923** [comment]
Ben,
The file has 1592 lines of code. In version 3.5.4 the scroll bar for the same size file was significantly larger. Setting a minimum size would be great.

Thanks.
Bill
