### ISSUE TITLE
Update graphics and visual design elements for 4.x

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#48]
Things may still say Processing 3, and use its color scheme. We'll be updating that before the release.

**Comment by urbanskimichal** [comment]
Is it already designed and needs to be implemented or this task is about proposing a design? If the latter - what elements exactly?

**Comment by benfry** [comment]
This is just a note that they'll need to be swapped out before launch.

As for the design, it's the one thing that *does not* actually need additional volunteer help.

**Comment by pr1metine** [comment]
Hi guys,
Are you talking about the PDE? In that case, I'd like to propose a complete overhaul of it. Maybe we replace it with a [Language Server](https://microsoft.github.io/language-server-protocol) Plugin e. g. for [VS Code](https://github.com/microsoft/vscode) or ship a [Theia](https://github.com/theia-ide/theia) application with Processing.

**Comment by benfry** [comment]
That's a separate discussion, see here: https://github.com/processing/processing/issues/5423

**Comment by benfry** [comment]
(Locking this since the issue can be read too broadly and to avoid this turning into a general discussion about the UI of the PDE.)

**Comment by benfry** [comment]
4.0 alpha 6 introduces a new color set *that is not final*. You can also set your own colors and styles [here](https://github.com/processing/processing4/wiki/Themes). We're working on ways to make theming more personal and customizable (without having to mess with `theme.txt`), but more on that later.

**Comment by benfry** [comment]
4.0 beta 3 lands the first (major) round of the theming changes. Read more about it in the release notes or at https://github.com/processing/processing4/wiki/Themes.

It also has an updated application icon, which is better than the previous but:
* May not yet be final – it's a version of the official logo that's been tweaked for the small size and icon usage
* Is using the “Big Sur” style, even for Windows and Linux releases – not ideal, but also unlikely that we'll have time to maintain separate icons for each platform. I don't personally like the Big Sur style, but it's probably the best of several bad options.

Themes are still incomplete: 
* The editor “tokens” (what colors text in code) are not yet implemented properly relative to the overall theme. They're just using the old defaults.
* We'd like to somehow incorporate the generative theme engine we're using for the set of 16 into the software itself, so that folks can pick their own starting colors, accents, and styles.
* The Editor Console needs a custom scroll bar
* The Contribution Manager hasn't been redone
* The debug window hasn't been touched

We also may or may not redo the standard application windows to follow the theme. On the plus side, Java UIs look awful and this would bring some consistency (and hopefully elegance) to the mess. On the minus side, it's a ton of time and effort that might be better directed elsewhere.

**Comment by benfry** [comment]
The next release (4.0 beta 9) will have major improvements to the visual design of the UI. Themes are now working across the places mentioned in the previous comment. Remaining items: 

* The debug window has not been updated
* Now that the theme work is in place, it's time to tweak some of the sizing/layout issues in parts of the UI (tab sizes, some button placement, etc)
* Whatever we want to do (or not) with the Welcome screen

And to reiterate: the goal for 4.0 is to have the best possible version of the way the PDE currently operates. We're not looking for a major redesign/rethink at this point because I don't have the time for it. And before that work, my priority is to first package the code for a Language Server implementation (see https://github.com/processing/processing4/issues/117) so that the guts would be more usable with other editors (VS Code, Atom, whatever) and then we'd have the room to build something (probably Theia-based) as a replacement PDE.

**Comment by benfry** [comment]
Major visual changes will be in place with the 4.0 beta 9 release. There's still some minor things (the Welcome screen decision) but the major elements are now in place in the source (with a few things still being worked on as we head into the beta 9 release in the next day or two or seven).
