### ISSUE TITLE
NoClassDefFoundError: com/formdev/flatlaf/FlatLaf

### ISSUE THREAD

**Issue by rupeshkumar22** [benfry/processing4#485]
## Description
First I downloaded the processing4 master zip file directly and executed git init. After building with `cd build`, I imported the project to eclipse and set the base class in run configurations. When I run it along with Android Mode (via VM arguments) or without Android Mode, I see this error.

## Expected Behavior
I remember no such issue faced on the earlier version of Processsing4.

## Current Behavior
Sharing a snapshot of the issue on running the app -
![Capture](https://user-images.githubusercontent.com/46577873/167476767-a937581d-a828-4510-80a7-ce95cb569aa6.PNG)

## Your Environment
java -version
openjdk version "17.0.1" 2021-10-19
**OS-** Windows 10

## Possible Causes / Solutions
I can see the jar at the `/app/lib/flatlaf.jar` location. Seems that some classpath variables need to be declared. Or maybe I need to use java 17.0.2.

**Comment by benfry** [comment]
If you're building with Eclipse, you'll have to add that .jar file. Eclipse isn't supported; just use `ant run` from inside the `build` folder for the supported way to build/run the software from the repo.

**Comment by rupeshkumar22** [comment]
@benfry adding jar in build path resolved it. thanks! I need to use eclipse for adding Android Mode's VM Arguments. `ant run` also works well.
