### ISSUE TITLE
pixelDensity() not working in Windows applications

### ISSUE THREAD

**Issue by dgray001** [benfry/processing4#487]
seems very similar to https://github.com/processing/processing/issues/5414

## Description
Scales to window scaling (default 125%).
When I run `displayDensity()` it returns 1
If I run `pixelDensity(1)` or `pixelDensity(displayDensity())` I get the error:
`Display -1 does not exist, returning 1 for displayDensity(-1)`

## Expected Behavior
Sketch to scale with Windows scale

## Current Behavior
Sketch scales to 125% to what it should be

## Steps to Reproduce
1. Set Windows scale to anything not 100%
2. Use processing 4

## Your Environment
* Processing version: 4.0b8 (also tried 4.0b6 with same behavior)
* Operating System and OS version: Windows 11
* Other information: Brand new workstation with clean install of windows/processing
* EDIT: I'm using javafx not sure if that makes a difference

## Possible Causes / Solutions
_This only happens in processing4; when I run on processing3 there is no issue._

**Comment by benfry** [comment]
Just ran into something similar while trying this with `fullScreen()` on macOS, but with any luck, it should fix the issue for Windows as well. The fix will be in 4.0.2 when released.

**Comment by benfry** [comment]
Meant to tag this from this commit: https://github.com/processing/processing4/commit/b0cd253dad0faa67261bf3e2d8929c5243b5ee96
