### ISSUE TITLE
Export Application gives java.lang.ClassNotFoundException: --full-screen error

### ISSUE THREAD

**Issue by dantepfer** [benfry/processing4#488]
## Description
Using Processing 4.0 beta 8, on Intel Mac (MacBook Pro 2019), Montery 12.4, Exported Applications fail with the following error:
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: --full-screen
	at processing.core.PApplet.runSketch(PApplet.java:10397)
	at processing.core.PApplet.main(PApplet.java:10187)
	at Particles.main(Particles.java:148)
Caused by: java.lang.ClassNotFoundException: --full-screen
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at processing.core.PApplet.runSketch(PApplet.java:10390)
```
This is true even for sketches that are not running full screen, and occurs whether or not Java is embedded.

## Steps to Reproduce
1. open Particles example
2. export application
3. try running exported application, it will silently fail
4. control-click on exported application, go to contents > MacOS > Particles, open Particles
5. app will fail with the above error in terminal

 

* Processing version: 4.0 beta 8
* Operating System and OS version: MacOS 12.4
* Computer: MacBook Pro (16-inch, 2019)

**Comment by clankill3r** [comment]
I tried to reproduce on OSX 10.15.7, but on this OS I can run the exported application. Only the present mode is not working, it's always windowed.

**Comment by benfry** [comment]
I'm seeing what @clankill3r is seeing. 

@dantepfer you might check whether there's an old version of core.jar somewhere in your path. 

@sampottinger it looks like this has been broken since alpha 1, which suggests there might be a regression in the preprocessor, because it's no longer inserting the lines into the source during the build to properly run things in “present” mode.

**Comment by sampottinger** [comment]
I’ll take a look!

Thanks,
Sam

**Comment by benfry** [comment]
Awesome thank you Sam.
