### ISSUE TITLE
The render window is scaled improperly in Python mode when Windows display scale is set to greater than 100%

### ISSUE THREAD

**Issue by Metamere** [benfry/processing4#489]
In Python mode, the render window, but not the image resolution, is scaled up to match the Windows display scale, making things very jagged. When I switch it to 100% scale, It renders the same as Java mode. Save() creates the image properly. To test, just set the Windows display scale to 150% like I do for my 2560x1440 display. The image below compares the render windows for Python and Java modes, with the code used included below it. I searched for duplicates of this issue, and asked for help in the forums and in a Discord group, so I believe this is a bug. 

I am using version 4.08 beta, on Windows 10.
I also tested it in version 3.5 and it had the same issue.

![python java comparison](https://user-images.githubusercontent.com/62861841/169632622-34793bbd-92a0-4e59-9b33-2302b50890fc.jpg)

Here is the code for the Python test:

def setup():
    size(300,300)
    background(255)
    draw_shape()
    save("Python_test.tif")
    
def draw_shape():
    line(0, 0, width, height)
    translate(width*.5,height*.5)
    rotate(radians(45))
    fill(0)
    rectMode(CENTER)
    rect(0,0,100,100)

And here is the code for the Java test:

void setup(){
    size(300,300);
    background(255);
    draw_shape();
    save("Java_test.tif");
}
void draw_shape(){
    line(0, 0, width, height);
    translate(width*.5,height*.5);
    rotate(radians(45));
    fill(0);
    rectMode(CENTER);
    rect(0,0,100,100);
}

**Comment by benfry** [comment]
If it's working correctly in Java Mode, then it's a problem with Python Mode, unfortunately. You'd need to file a bug report there.

**Comment by Metamere** [comment]
@benfry, Thanks, but I can't find where you are referring to. Would you please send me a link?

**Comment by dzaima** [comment]
@Metamere https://github.com/jdf/Processing.py-Bugs/issues would be where to report bugs with the python mode.
