### ISSUE TITLE
Serial.list() on Linux support broken

### ISSUE THREAD

**Issue by dattasaurabh82** [benfry/processing4#490]
## Description
`Serial.list()` on Linux (test environment info below) doesn’t seem to work. 
Tried on Ubuntu and it spits only 1 port where as `ls /dev/tty*` gives me (of course) all the serial ports. 

## Expected Behavior
`Serial.list()` should spit out an `Array `all the ports available. 
A result very similar to `ls /dev/tty*` is expected!

## Current Behavior
`Serial.list()` doesn't list all the serial ports, just one.  

## Steps to Reproduce
**Sketch to try for checking:**
```
import processing.serial.*;
void setup(){
  printArray(Serial.list());
}
void draw(){
}
```

## My Environment
**OS:** Ubuntu 22.04 LTS x86_64
**Kernel:** 5.17.8-051708-generic
**Processing IDE version:** 4.0b8

## Possible Causes / Solutions
Unknown!

**Comment by benfry** [comment]
This is a better question for the forum, because it's more about troubleshooting what's happening on your machine: https://discourse.processing.org/
