### ISSUE TITLE
Code completion with dropdown menu does not work for v4.0b5, v4.0b6, v4.0b7, and v4.0b8

### ISSUE THREAD

**Issue by resources1256** [benfry/processing4#491]
## Description

Code completion with dropdown menu does not work for v4.0b5, v4.0b6, v4.0b7, and v4.0b8

## Expected Behavior

Dropdown with code completion suggestions should appear. This works in v4.0b3 and v4.0b4. Does anybody have the same behavior?

## Steps to Reproduce

"Code completion with Ctrl+Space" in File>Preferences is checked.
pdex.completion=true and pdex.completion.trigger=true are set in preferences.txt as described in [#363 ](https://github.com/jdf/processing.py/issues/363)
Path to preferences.txt can be found in File>Preferences .

## Your Environment
 

* Processing version: v4.0b3, v4.0b4, v4.0b5, v4.0b6, v4.0b7, and v4.0b8
* Operating System and OS version: Win10 (64x)
* Other information:

**Comment by clankill3r** [comment]
Also broken for OSX (tested with ) v4.0b8

**Comment by JonaNorman** [comment]
Also broken for OSX (tested with ) v4.0b8,but  work in v4.0b4

**Comment by benfry** [comment]
Yeah, bumped into this the other day. Thanks for checking the other versions, @resources1256, I'll have to look into what changed between beta 4 and 5 (or someone else can do the same in the meantime…)

**Comment by benfry** [comment]
@sampottinger Used `git bisect` to track this down to https://github.com/processing/processing4/commit/0f9b290398aac86ef56fe3c4e9c3ff88fdd53466 

Specifically, it's the changes in the `Processing.g4` file that are causing it to stop working. Thoughts?

**Comment by benfry** [comment]
Ok, turning off the mixed mode warning that caused the issue; that's now being tracked here: https://github.com/processing/processing4/issues/519

But auto-complete will be fixed for beta 9.
