### ISSUE TITLE
McAfee reports processsing-4.0b8\processing-java.exe as Artemis!A9B99C1E128F Trojan

### ISSUE THREAD

**Issue by majedhaj** [benfry/processing4#494]
## Steps to Reproduce

1. Download the Zip file processing-4.0b8-windows-x64.zip
2. Unzip the zip file
3. scan the unzipped folder using McAfee Endpoint Security V10.7
4. McAfee scans 37519 files and reports only the file processing-java.exe as Trojan of type Artemis!A9BooC1E128F and delete it.
5. When checking that type of Trojan, it seems it's associated with the Ransomware attack.

## Your Environment

 

* Processing version: 4.0b8
* Operating System and OS version: Windows 10
* Other information:

**Comment by benfry** [comment]
It's not a virus or trojan. We've already had it submitted to Microsoft's threat folks and they've cleared it. Sorry that McAfee is flagging it like this…
