### ISSUE TITLE
beginContour and endContour do not work when used within a PShape declaraion

### ISSUE THREAD

**Issue by ksymeon** [benfry/processing4#506]
## Description
Using the example from https://processing.org/reference/beginContour_.html, I tried to declare the shape within a variable using `createShape()`  aligned with the instructions in https://processing.org/tutorials/pshape.

## Expected Behavior
It appears that the `beginContour()` when called within a `PShape` does not "close" the outer path, and the `endContour()` does not close the inner path, resulting in a very different behavior that when used outside of a `PShape` context.

## Current Behavior
See expected behavior and screenshot below:
![processing_bug_report](https://user-images.githubusercontent.com/831087/175791763-cb810f15-5b21-4a5c-8137-1184685c5b17.png)

## Steps to Reproduce
Please look at the code below, section 1 is taken from the reference example for `beginContour()`
```
void setup() {
  size(800, 800);
}

void draw() {  
  // 1. WORKS. Normal drawing, example from:
  // https://processing.org/reference/beginContour_.html  
  translate(200, 200);
  stroke(255, 0, 0);
  fill(120);
  
  beginShape();
  // Exterior part of shape, clockwise winding
  vertex(-160, -160);
  vertex(160, -160);
  vertex(160, 160);
  vertex(-160, 160);
  // Interior part of shape, counter-clockwise winding
  beginContour();
  vertex(-80, -80);
  vertex(-80, 80);
  vertex(80, 80);
  vertex(80, -80);
  endContour();
  endShape(CLOSE);
  
  // 2. BROKEN. Create a variable and a shape
  PShape s = createShape();
  s.beginShape();
  
  // have to declare those after beginShape() otherwise they don't use the current context.
  s.stroke(255, 0, 0);
  s.fill(120);
  
  // Exterior part of shape, clockwise winding
  s.vertex(-160, -160);
  s.vertex(160, -160);
  s.vertex(160, 160);
  s.vertex(-160, 160);
  // Interior part of shape, counter-clockwise winding
  s.beginContour();
  s.vertex(-80, -80);
  s.vertex(-80, 80);
  s.vertex(80, 80);
  s.vertex(80, -80);
  s.endContour();
  s.endShape(CLOSE);
  
  // Draw - very different output!! 
  // beginContour doesn't seem to close the first path, and seems to join back to the beginning of the interior
  // part of the shape. 
  // endContour again doesn't finish the contour and as a result the endShape() seems to return to the beginning
  // of the outer shape to close the path.
  translate(0, 400);
  shape(s);
}
```

## Your Environment

 

* Processing version: `4.0b8`
* Operating System and OS version: `Windows 10 Pro - 21H2`
* Other information: `3x 4K monitors, Core i9-10900K, RTX 2070s, 64GB RAM`

## Possible Causes / Solutions
It looks like the issue is also ongoing in Processing 3, I found this very similar report:  
https://github.com/processing/processing4/issues/643

- There is a proposed hack there, but haven't tried it on 4.0b8

**Comment by benfry** [comment]
Ok, thanks for letting me know. I've moved over that other issue and we can close this as a duplicate: https://github.com/processing/processing4/issues/643 (this one will still be linked if we need it for reference).
