### ISSUE TITLE
Windows 11 - WSL2 - Using Linux Ubuntu

### ISSUE THREAD

**Issue by dantearaujo1** [benfry/processing4#508]
## Description
Writing a simple program with setup(){size(600,600);} using processing-java command inside terminal makes my window size not be correct.

## Expected Behavior
Window with width and height == then the value placed at size function()

## Current Behavior
Window width and height lesser then the values inside size() function, it needs to manually resize

## Steps to Reproduce
Windows 11 - WSL2 - Ubuntu 20.04 LTS - install processing and write a simple file then use it with processing-java command

## Your Environment

 

* Processing version: 4.0 - Processing 1284
* Operating System and OS version: Windows 11
* Other information:
* WSL2 - Linux Ubuntu 20.04 LTS

**Comment by benfry** [comment]
Sorry, Linux under WSL on Windows 11 isn't a supported platform. There's just no way I have time to track that down.
