### ISSUE TITLE
Could not Run the Sketch error

### ISSUE THREAD

**Issue by 0xinit** [benfry/processing4#511]
## Your Environment

 

* Processing version:  4.0b8
* Operating System and OS version: Ubuntu 22.04
* Other information: Im just new to processing, Idk if I have all the dependencies or not? I am currently using jdk 17.03. Is there anything else that I need?

## Possible Causes / Solutions

![image](https://user-images.githubusercontent.com/28729137/179449948-2f4cc870-156b-4d09-9a54-6e5359415f6b.png)

**Comment by benfry** [comment]
Are you running on an ARM version of Linux? Because that's the version you've downloaded, which may be the cause of the problem if you're on an Intel machine.

You should just be able to type `./processing` inside the folder after you've extracted it, so in your case:

```
cd ~/Downloads/processing-4.0b8-linux-arm64/processing-4.0b8
./processing
```

**Comment by benfry** [comment]
But beyond that, the forum is a better place for troubleshooting/getting started questions: https://discourse.processing.org/
