### ISSUE TITLE
Fix vertical placement of top elements in the Manager window

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#520]
Too much space below the search field, should be the same as above the field. The space above may need to be a pixel or two higher:

<img width="862" alt="screenshot" src="https://user-images.githubusercontent.com/1623101/182044231-3bee3f20-ea39-4c37-a50e-9000a397de0a.png">

The upper area is also larger for the “Libraries” tab, presumably because of the vertical height of the dropdown. But that needs to be fixed (maybe the drop down has extra space that needs to be removed?) so the UI doesn't jiggle as you move between tabs.

**Comment by benfry** [comment]
Code is here: https://github.com/processing/processing4/blob/main/app/src/processing/app/contrib/ContributionTab.java

**Comment by LesleyWagner** [comment]
I made a pull request for this issue #539. Here is a screen capture of the solution https://user-images.githubusercontent.com/33584486/185764011-82daad14-0f60-4500-9ae0-de824df54847.mp4
Let me know if anything must be changed.

P.S. This is my first pull request on an open source project.

**Comment by benfry** [comment]
Awesome! Nice work. Now integrated for 4.0.2; thanks for looking into it!
