### ISSUE TITLE
Export Application displays "Unable to load Java Runtime Environment" on Apple Silicon M1

### ISSUE THREAD

**Issue by mroxfordyazuka** [benfry/processing4#526]
Platform: macOS Monterey 12.4 Apple M1.
Issue Description: Export Application displays "Unable to load Java Runtime Environment" error after attempting to run application
The Fix/Solution: Show package contents and navigate to contents/macOS, launch app and will run successfully
Step to Reproduce: Export app on m1 Mac and select include java runtime. 

Additional details reported in official forums:
https://discourse.processing.org/t/macos-exported-application-unable-to-load-java-runtime-environment/38136/5

**Comment by benfry** [comment]
This should already be fixed in 4.0 beta 9, which is arriving shortly. But let us know how it goes.
