### ISSUE TITLE
Changing into p5.js mode gives an error

### ISSUE THREAD

**Issue by chrleon** [benfry/processing4#530]
## Description

Changing from Java to p5.js gives an error
![image](https://user-images.githubusercontent.com/347919/183658918-2c55a929-62a2-4f09-9dbe-f0f3c78a4067.png)

## Steps to Reproduce

1. open Processing 4.0 (released 9. august)
2. Change mode from Java to p5.js
3. Read error message

## Your Environment

 

* Processing version: 4.0 
* Operating System and OS version: MacOS 12.3.1
* Other information: Just got the downlaod from [github](https://github.com/processing/processing4/releases/tag/processing-1285-4.0)

**Comment by benfry** [comment]
Noooo! Let me see what's going on…

**Comment by benfry** [comment]
Damn, and it was in a line of code that wasn't strictly necessary, but added to be helpful for debugging. Unfortunately, it was a little too sensitive. 

Are you on an Intel or Apple Silicon Mac? 

I'll push out a 4.0.1 release later today; thanks for the report!

**Comment by chrleon** [comment]
Intel. Insane turnaround speed! Impressive :D

**Comment by benfry** [comment]
:) 

Here's a temporary build for Intel with the fix: https://download.processing.org/processing-220809a-macos-x64.zip

Just waiting a little bit to see if anything else major pops up…

**Comment by chrleon** [comment]
Works on my machine :)

**Comment by benfry** [comment]
Great, thanks.

**Comment by benfry** [comment]
4.0.1 now posted: https://github.com/processing/processing4/releases/
