### ISSUE TITLE
`height` includes titlebar height on Linux

### ISSUE THREAD

**Issue by QazCetelic** [benfry/processing4#533]
## Description
Currently, the `height` variable includes the titlebar height. This is inconvenient when trying to fit a graphics in the display because the height has to be manually corrected.

## Expected Behavior
The titlebar height is excluded from the `height` variable.

## Steps to Reproduce
1. Set size
2. Use `height`

## Your Environment
* Processing version: 4.0b8
* Operating System and OS version: Fedora Linux 36
* Other information: I'm using the KDE Plasma desktop environment.

## Possible Causes / Solutions
Either exclude the titlebar height, or if this is already meant to happen, make it work on all platforms.

**Comment by benfry** [comment]
This is because of your window manager and out of our control, unfortunately.

Meaning that depending on what WM you use, you'll get different results, and we can't control what the WM tells us.

**Comment by QazCetelic** [comment]
I'm assuming JavaFX is used from the README, if so can't you get the height using `int contentHeight = (int) (stage.getScene().getHeight() * stage.getRenderScaleY());`? This would mean that the output is consistent with every WM.

The `stage.getRenderScaleY()` is required to adjust the size to display scaling.
