### ISSUE TITLE
Universal 2 Build App Bundle of Processing 4

### ISSUE THREAD

**Issue by Cpuroast** [benfry/processing4#536]
## Description
Currently there's an app bundle for macOS running on Intel 64-bit and one for Apple Silicon available to download.

It would be ideal and desired to merge these 2 into a Universal 2 app bundle which would run on both platforms.
This helps remove confusion amongst user, simplifies app deployment in lab environments and is all around a better solution than having individual builds for each.  

Since the introduction of Apple Silicon macs back in November 2020, most projects/applications have migrated to Universal app bundles rather than having separate ones.

## Expected Behavior
Create a Universal 2 app bundle and offer it for download, replacing the discrete versions.

## Current Behavior
Separate Intel vs Apple Silicon app bundles are available

## Your Environment
* Processing version: 4.0.1
* Operating System and OS version: Big Sur and Monterey

**Comment by clankill3r** [comment]
If I'm not mistaken, this will require both the JDK for x64 and for arm64, which will almost double the size of the processing download.

**Comment by Cpuroast** [comment]
Processing 4.0.1
Intel 452.3MB, 222MB Compressed
Apple Silicon 360.8MB, 203.9MB Compressed

At worst, the combined size would be 786.1MB, 425.9MB Compressed

It will most likely be less than that because of shared resources.

**Comment by clankill3r** [comment]
I did a diff check on both the JDK's that come with two versions that come with processing.
Around 75% of the files are different, and this makes up for so much of the size that it in my opinion it would not even be worth to merge the JDK's (let alone I would not know how).

The largest file is `/Contents/Home/lib/modules` which is 128mb's.

So in my opinion it is not worth making an universal app.

**Comment by benfry** [comment]
Correct, this is why I didn't make a universal version; it would just be over a hundred megabytes of simply duplicated files. It's not fun to choose a version, but the extra effort to make a universal build, only to double the download size, isn't a good use of my time or everyone's limited disk space.
