### ISSUE TITLE
Please make Processing available to develop directly in Eclipse/IntelliJ.

### ISSUE THREAD

**Issue by eGit** [benfry/processing4#538]
Is there a simple Gradle script or some other best-practice on how to set up a standalone project of Processing (with all dependencies) in Eclipse or IntelliJ. PDE is not for everyone.

**Comment by benfry** [comment]
It'd be great if someone could write an updated tutorial about this, but I have enough on my plate supporting the core, the libraries, the PDE, and everything else, and can't add supporting everyone who wants to use IntelliJ or Eclipse. Most of those users should be able to figure it out themselves anyway.
