### ISSUE TITLE
Method commented out in Sketch class (sketch.java)

### ISSUE THREAD

**Issue by ghost** [benfry/processing4#545]
The method `getCodeIndex(SketchCode who)` (sketch.java lines 1772 - 1781) has been commented out in P4. 

It was available in P3 but this change means that the 'GUI Builder Tool' no longer works in P4.

Is this a permanent change or is  it likely to be reinstated on the next release?

**Comment by RavenDevil** [comment]
I would like to be able to use GUI Builder with Processing 4, pls.

**Comment by mematron** [comment]
I need this to work again!

**Comment by vyPal** [comment]
Someone pls fix this

**Comment by benfry** [comment]
Oh yuck, that was an undocumented function that wasn't used anywhere else. I'll just have to bring it back for 4.0.2.
