### ISSUE TITLE
Hey, how about a flathub release?

### ISSUE THREAD

**Issue by SeitzB** [benfry/processing4#547]
## Description
The Processing Version on flathub is some version of 3.5.4 from 2 Years ago

## Expected Behavior
It would be very nice to have an up to date Version
I'd publish the one I quickly threw together, but I wanted to ask for Permission of the devs first

**Comment by TomLarrow** [comment]
Agreed, it would be helpful for more users if the Flatpack version was up to date

**Comment by benfry** [comment]
That wasn't posted by me, I'm sorry it's there and causing confusion. If possible, someone should request its removal.

Unfortunately with already releasing simultaneously across six platforms, I don't have time in the foreseeable future to add a Flathub release to that.
