### ISSUE TITLE
Translation to Catalan

### ISSUE THREAD

**Issue by trikaphundo** [benfry/processing4#550]
Hello, I am planning on translating Processing to Catalan. I think I am aware of all the necessary steps to translate Processing. I am outlining them down below so that

1. Anyone can tell me whether I am missing something.
2. Offer a guide for future translators.

As far as I have been able to find out, by searching this repository, the steps to translate Processing are these

- Clone the Processing4 repository to your local machine.
- Create a copy of the [`PDE.properties`](https://github.com/processing/processing4/blob/22987414f8a7ec1c9a78d56f25734acc70eda45d/build/shared/lib/languages/PDE.properties) file, name it `PDE_xx.properties`, and translate its content to your language (Catalan in my case). Where xx is the [two-letter language code](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes); in my case `ca`, thus in my case the file's name is `PDE_ca.properties`.
- Add the language code to the file of supported languages [`languages.txt`](https://github.com/processing/processing4/blob/22987414f8a7ec1c9a78d56f25734acc70eda45d/build/shared/lib/languages/languages.txt).
- Let the [Language class](https://github.com/processing/processing4/blob/22987414f8a7ec1c9a78d56f25734acc70eda45d/app/src/processing/app/Language.java#L88) know the language code for your language.
- Build Processing (see [README](https://github.com/processing/processing4/blob/main/build/README.md) file) to test the translation and make sure everything is ok.

Edit: It seems some work has been done in Processing 4 ([version 4.0 beta 5](https://github.com/processing/processing4/blob/main/build/shared/revisions.md) actually) to allow the translation of contributed modes (see [issue #236](https://github.com/processing/processing4/issues/236)). But at the time of writing this text, no `mode.properties` file is yet available in the [language directory](https://github.com/processing/processing4/tree/main/build/shared/lib/languages), as the Language class [method responsible](https://github.com/processing/processing4/blob/f1a825aff8a63a24b1c7b40165a0c5032075c737/app/src/processing/app/Language.java#L272) for it requires. Maybe it is still a work in progress.

Edit2: I finished the translation 2 days ago and now I am trying to have it reviewed by some peers.

**Comment by benfry** [comment]
Yes, the documentation for the process was at https://github.com/processing/processing/wiki/Localization

…and I've just added a new version for 4.0 here: https://github.com/processing/processing4/wiki/Translations

Thanks for the new translation!

**Comment by trikaphundo** [comment]
> Yes, the documentation for the process was at https://github.com/processing/processing/wiki/Localization
> 
> …and I've just added a new version for 4.0 here: https://github.com/processing/processing4/wiki/Translations
> 
> Thanks for the new translation!

I see; that explains why I didn't manage to find any information on translating the application: I searched this repository (processing4) not the older one (processing).

Glad to help :)
