### ISSUE TITLE
Errors in the Spanish translation

### ISSUE THREAD

**Issue by trikaphundo** [benfry/processing4#552]
The Spanish translation has some errors, to name a few:

- Some tooltips in the Preferences dialog show just a "\\" character.
- At times, the information shown in editor's status bar, when continous error checking is enabled, is phrased in an unnatural way.
- There are a few inconsistencies, such as translating the word "bitmap" and, right in the next sentence, not translating it.
- There are some parts of the interface that are not translated.

The last point is, in part, because [PDE_es.properties](https://github.com/processing/processing4/blob/main/build/shared/lib/languages/PDE_es.properties) is not up-to-date with some changes introduced in the original [PDE.properties](https://github.com/processing/processing4/blob/main/build/shared/lib/languages/PDE.properties), such as addition of new strings.

I am fixing these all, and issuing a PR soon. Whoever wants to make to participate or review the changes, is welcome to do so :).

Edit: The translation is already done; I am trying to have it reviewed.

**Comment by SableRaf** [comment]
Thanks for all your great contributions Daniel! 🤗
