### ISSUE TITLE
NullPointerException without any reason

### ISSUE THREAD

**Issue by jqqdb** [benfry/processing4#558]
## Description
Random NullPointerException with graphics instructions such as text(), line(), ellipse(), ONLY during program startup (NEVER later). Parameters well initialized. Second attempt ALWAYS without exception : try {text(String, int, int);} catch (NullPointerException e) {text(String, int, int);} 

## Expected Behavior
Probable bug : no reason for exception then no exception with exactly the same instruction twice !?

## Current Behavior

This problem seems to appear randomly, but never immediatly after Processing ide startup.

## Steps to Reproduce

// object attributes : String m_texte, int m_xDeb, int m_yDeb correctly initialized
text(m_texte, m_xDeb, m_yDeb);
// ints nombre, x, y correctly initialized
text(nombre, x, y);
// Most of the time no exception. Sometimes 1 or more exceptions with instructions text() or ellipse(), 2nd call (try/catch same instruction) is ok.

## Your Environment
Windows, Raspbian (same  problem)
 

* Processing version:4.0.1b
* Operating System and OS version: W8.1 / Raspbian exactly same problem
* Other information:
Program with many enum {} sets and many variables initializations.

**Comment by benfry** [comment]
Almost certainly a bug in your code, I'd recommend getting some help from the forum: https://discourse.processing.org/
