### ISSUE TITLE
Installing Processing on Ubuntu??

### ISSUE THREAD

**Issue by christophersatch** [benfry/processing4#561]
## Description

I have a HP Envy Laptop with Ubuntu installed. I downloaded the Linux 64 bit Processing newest version. When I went to click the run file, a folder popped up saying:
!/bin/sh

# This script runs Processing, using the JRE in the Processing
# installation directory.

# If your system needs a different version of Java than what's included
# in the download, replace the 'java' folder with the contents of a new
# OpenJDK (Java 11 only), or create a symlink named "java" in the
# Processing installation directory that points to the JRE home directory.

# Thanks to Ferdinand Kasper for this build script. [fry]

# JARs required from JDK (anywhere in/below the JDK home directory)
JDKLIBS="rt.jar"

# Set this to non-zero for logging
LOGGING=0

# Logs name and value of a variable to stdout if LOGGING is non-zero.
# Expects the variable name as parameter $1.

**Comment by SableRaf** [comment]
Hi Christopher. This repository is for issues related to the development of Processing itself. For this type of questions I would recommend posting on the forum 👉 https://discourse.processing.org/
