### ISSUE TITLE
Attempt to run with multiprocessing

### ISSUE THREAD

**Issue by inapeace0** [benfry/processing4#562]
**I’ve developed a python script to run processing-java command with multiprocessing pool.**

— Python Script—

> from multiprocessing import Pool
> def func(meta):
> …
> os.system(“./processing/processing-java --sketch="” + cwd + “/oscilloscope/" --run " + str(meta) + "
> mint”)
> …
> pool = Pool()
> pool.map(func, range(len(metadata)))

**At first, I see the generating starts well at first and some complete video files come out, but all processes are slept, and the video files never come out anymore at some point.**

![image](https://user-images.githubusercontent.com/87882515/192390071-264cfff8-f7bf-42d7-b1df-1187d9b3ee20.png)

**Comment by benfry** [comment]
This isn't a bug; it's better as a discussion on the forum: https://discourse.processing.org/
