### ISSUE TITLE
Process managers not working - pm2, nssm, etc.

### ISSUE THREAD

**Issue by renaudfv** [benfry/processing4#563]
Hey! 

I'm looking at running exported sketches using process managers on windows.
No options I tried work, that is on multiple PCS, using different sketches (event provided examples).

More details [here](https://discourse.processing.org/t/process-managers-how-to-run-an-exported-sketch-for-ever/39004)

**Comment by benfry** [comment]
This is more suitable as a forum discussion; this isn't a Processing bug.

**Comment by renaudfv** [comment]
Fair, but it's kinda linked to how Processing spawn's processes.
Here's the [Discourse thread](https://discourse.processing.org/t/process-managers-how-to-run-an-exported-sketch-for-ever/39004/2) if anyone want to add details.
