### ISSUE TITLE
Contrast Themes for Proccessing 4

### ISSUE THREAD

**Issue by potatochipsnotincluded** [benfry/processing4#569]
Hello, you know how the p5.js web editor has contrast mode. I think there should be a contrast theme for Proccessing 4.

**Comment by SableRaf** [comment]
Hi @thecodingcookery I agree :) Would this be something you could see yourself helping with?

For reference, here's the README on custom themes: https://github.com/processing/processing4/wiki/Themes

**Comment by potatochipsnotincluded** [comment]
I can not Proccessing 4 will not run on my computer, I can only run Proccessing 3 on my Mac. So, I can not work on this.

**Comment by benfry** [comment]
This would be a helpful contribution; if someone would like to develop one, we can see about including it.
