### ISSUE TITLE
a line with beginShape and endShape does not draw in P2D

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#573]
If you draw something with only two vertices in P2D, then nothing is drawn.
Apparently this is rather old, I just tested in processing 2.2.1 and it is already in there.
Uncomment the commented line and something will be drawn.

```java
void setup() {
  size(600, 600, P2D);
}

void draw() {
   background(255);
   
   strokeWeight(10);
   stroke(0);
   noFill();
   
   beginShape();
   vertex(0, 0);
   vertex(mouseX, mouseY);
//   vertex(mouseX, mouseY+1);
   endShape();
}
```

**Comment by hkiel** [comment]
`beginShape()` is an alias for `beginShape(POLYGON)`

Try yourcode with `beginShape(LINES)` and you see the line. Though I tend to accept that a `polygon with two points` is a line, especially because if you start the sketch in JAVA2D mode (instead of P2D) you also see that line.

**Comment by clankill3r** [comment]
Damn, can't believe I didn't think of that. Maybe it should be good to check if the `vertexCount` or whatever it was `== 2` and if so change mode to LINES if it was POLYGON?

**Comment by benfry** [comment]
Closing since it's not a bug / working as documented.

**Comment by hkiel** [comment]
Not really a bug, but still we have different behaviour for the same code depending on the mode! (JAVA2D draws a line, P2D draws nothing)
