### ISSUE TITLE
Entire PDE Window Goes White

### ISSUE THREAD

**Issue by REAS** [benfry/processing4#576]
I have a report from a student who said "the entire window goes white" and they lost their work. Window 10. I'm sorry that I don't have more information. I wasn't able to find similar reports yet.

**Comment by REAS** [comment]
Maybe related, an error message pops up from time to time "OpenJDK Binary Not Responding"

**Comment by benfry** [comment]
Hard to debug this one without more information. With any luck, their work should still be in their Windows temporary folder if something drastic happens like this.
