### ISSUE TITLE
“pixelDensity() cannot be used here” in static mode sketches (regression from 3.x)

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#58]
A sketch with nothing but this code worked in 3.x:

```processing
pixelDensity(displayDensity());
```

But now throws an error saying `pixelDensity() cannot be used here`, presumably because the preprocessor isn't correctly pulling the method out to place it inside `settings()` behind the scenes.

**Comment by sampottinger** [comment]
I can take this @benfry

**Comment by sampottinger** [comment]
@benfry, sorry I missed that. I have a resolution for this at #60.

**Comment by benfry** [comment]
Thanks for the quick fix.
