### ISSUE TITLE
Can't restart Processing 4 because of read/write permissions for the modes folder

### ISSUE THREAD

**Issue by SmantikVJ** [benfry/processing4#581]
Hi!
I have an issue with Processing

**Description**
I have installed Processing 4.0.1. When I close the program and restart again, it shows me this error message:

![error](https://user-images.githubusercontent.com/46849400/197497193-e0103693-ef5a-43d4-98d0-3120a825803a.png)

I have changed permission for /Documents/Processing/modes folder, allowing to everybody to write and read, but it doesn't work.

After trying different things, I have found a way to make it work:

1. Uninstall Processing.
2. Delete /Documents/Processing folder.
3. Install Processing.
4. Run Processing - it says to me that there is no /Documents/Processing folder, so it's going to create it.
5. While running Processing, I go and change permission allowing to everybody write and read to /Documents/Processing folder. I do the same with every folder that is contained in it.
6. Now, I can close Processing and restarting with no problem.

I have opened this issue as @SableRaf told me. I think that it's a good idea because, if you fix it, some users will not have this problem.

**My Environment**
* Processing version: 4.0.1
* Operating System and OS version: macOS Big Sur

**Possible  Solution**
Can't you modify /Processing folder permission when Processing creates them?

Thanks.

**Comment by SmantikVJ** [comment]
The method that I described above is not working today. The window of the image attached appears again and Processing doesn't start.
It's frustrating.

**Comment by benfry** [comment]
How did you install Processing? Is it installed as a different user, or have you changed the permissions in any way?

In a Terminal, can you enter:

```
cd ~/Documents
ls -l | grep Processing
```
and paste the result here? 

Also, this one:

```
cd ~/Documents/Processing
ls -l
```

It shouldn't really be possible for you to run an app that creates folders that you don't have permissions to, because when you run Processing, it has the same permissions as you do. So we need to figure out what's happening with that.

And this is on a personal machine, right? Just one OS or are there multiple partitions?

**Comment by SmantikVJ** [comment]
Hi, @benfry.
I installed Processing as administrator. I work with my laptop as administrator everytime, so I run Processing as such.
After I installed it, I changed permission for /Documents/Processing folder, allowing to everybody to write and read. I did the same for every subfolder that it contains.

Terminal results for first command:
<img width="475" alt="Captura de pantalla 2022-11-07 a las 10 23 30" src="https://user-images.githubusercontent.com/46849400/200274315-5981e3c8-f1d1-4683-9285-08b35d4763e3.png">

Terminal results for second command:
<img width="724" alt="Captura de pantalla 2022-11-07 a las 10 23 59" src="https://user-images.githubusercontent.com/46849400/200274422-55330dab-d3fa-4ba2-8118-f0c54676bea4.png">

In this personal machine are two partitions: the first one contains High Sierra macOS 10.13.6 (I use it for 32 bits applications). Later, I installed Big Sur macOS (now is 11.5.2 version) for some applications that require a higher OS, and it is used generally.

Thanks.

**Comment by SmantikVJ** [comment]
Hi.
I think I have found the solution.
I have gone to Security & privacy, I have entered user administrator username / Password to unlock the editing screen and inside Privacy tab I have selected "Documents & folders" and let Processing to access (tick was deactivated before). I did the same selecting "Total access to disk".
Now, the window "We're on the wrong foot" does not appear (I didn't have to reinstall Processing).

Thanks, @benfry . With your comment you gave me a clue.

**Comment by benfry** [comment]
You shouldn't have to enable full disk access to use Processing. However, it sounds like an “allow Processing to access your Documents folder?” prompt was shown earlier and you didn't allow access, which later locked you out. Is that possible?

**Comment by SmantikVJ** [comment]
Allowing only Documents folder is enough. I tried.
Thanks again.

**Comment by benfry** [comment]
Confirmed that this is what happens when you click “Don't Allow” here: 
<img width="372" alt="Screen Shot 2022-11-24 at 4 45 26 PM" src="https://user-images.githubusercontent.com/1623101/203866879-801bd860-0173-459e-b19a-2751842fff01.png">

**Comment by benfry** [comment]
Added additional warning detail about how to reset permissions for 4.0.2.
