### ISSUE TITLE
📢 Calling translators and proofreaders for Processing Community Survey 📊

### ISSUE THREAD

**Issue by SableRaf** [benfry/processing4#583]
Hi everyone, 

Processing needs your help! 🙏

This is a call for translators and proofreaders for the upcoming Processing Community survey (note: this survey will be separate from the [p5.js contributor survey](https://github.com/processing/p5.js/issues/5831)). The survey is about 34 questions long and mostly consists of multiple choice questions. We are aiming to launch it early November.

We are seeking contributors who are fluent in the following languages (Arabic, Chinese, French, Japanese, Hindi, Korean, Portuguese, Russian, Spanish, Turkish, and Vietnamese). You can contribute either as a translator or a proofreader. 

Please reply below if you are willing and able to help! 💜 Also include an email (or your preferred way for me to get in touch) and I will reach out with instructions on how to proceed.

Note: The timeline we’re working with at the moment is very tight so we are not looking to add additional translations beyond the languages listed here.

Thanks!

🐦 Raphaël de Courville, Processing Community Lead Fellow

_Huge thanks to @limzykenneth whose p5.js contributor survey call for translators heavily inspired this one_

---

| Language | Translator                | Proofreader                | Completion |
| -------- | ------------------------- |------------------------- |------------------------- |
| Arabic | @Sillenaj          | @AhmadMoussa        | ![](https://geps.dev/progress/100) |
| Chinese | @jsyeh         | Haowen        | ![](https://geps.dev/progress/100) |
| French | @SableRaf         | @tepat @LoubiTek       | ![](https://geps.dev/progress/100) |
| Hindi | @Veer0x1         | @anusha-exe        | ![](https://geps.dev/progress/100) |
| Japanese | @3ru         | @deconbatch        | ![](https://geps.dev/progress/100) |
| Korean | Suhyun         | @achimkoh        | ![](https://geps.dev/progress/100) |
| Brazilian Portuguese | @arthurrlima         | @monstrim        | ![](https://geps.dev/progress/100) |
| Russian | @Lileinit         | @bymaer        | ![](https://geps.dev/progress/100) |
| Spanish | @MiguelElizalde         | @SmantikVJ        | ![](https://geps.dev/progress/100) |
| Turkish | @hyesmo         | @bedirxanugur        | ![](https://geps.dev/progress/100) |
| Vietnamese | @cuongleqq         |  @Iu1yota7h       | ![](https://geps.dev/progress/100) |

_1 Oct. 2022:  For legibility, translated but not proof-read is now shown as 50% instead of 90%_

🔴 Contact made
🟠 Translation complete
🟢 Translation and proof-reading complete

Last Updated: November 8th at 21:13 CET

**Comment by hyesmo** [comment]
i volunteer to do the turkish translation. you can reach me out on [hyesmo@gmail.com](mailto:hyesmo@gmail.com)

**Comment by Nancy-Chauhan** [comment]
I can do the Hindi translation. You can reach me at nancychn1@gmail.com or https://twitter.com/_nancychauhan

**Comment by arthurrlima** [comment]
Brazilian-pt native here! I'd gladly help with translation. you can reach me @icecodepics on twitter or arl3@cin.ufpe.br

**Comment by SableRaf** [comment]
Thanks! I added you three to the list. I'll be in touch :)

**Comment by Veer0x1** [comment]
I would love to do Hindi translations for you. You can reach me at balveer.singhrao.eee21@itbhu.ac.in or https://twitter.com/Balveerrajput56

**Comment by 3ru** [comment]
Hi, I can help with Japanese translation and proofreading.
You can reach me at Ryuyxx[at]gmail.com

**Comment by MiguelElizalde** [comment]
I can help with the Spanish one! hi@elizaldemiguel.com

**Comment by Sillenaj** [comment]
Hi 👋 I would like to help with Arabic Translation please contact me on sillen@sillen.xyz

**Comment by hamoid** [comment]
Hola :) I can help proofreading Spanish (but only next week). You can contact me in Telegram/Signal/CCB chat/e-mail... any channel is ok.

**Comment by SableRaf** [comment]
Hi everyone and thanks again for offering your help 😊

I've sent e-mails out to @Nancy-Chauhan @3ru @arthurrlima @MiguelElizalde @hyesmo and @Sillenaj. If you haven't received them please check your spam filter 👀

We still need more translators and proofreaders so if you know someone who could help with translation/proofreading in your language (or one of the other languages), please share this page with them 🙏

**Comment by SmantikVJ** [comment]
Hi. I can help with spanish proofreading if there's no one to do it. smantic@hotmail.com

**Comment by jsyeh** [comment]
I can do the traditional Chinese Translation.
ps. I did some translation in my GitHub
https://github.com/jsyeh/PDE_zh.properties

jsyeh@mail.mcu.edu.tw
jsyeh.org@gmail.com

**Comment by deconbatch** [comment]
I would like to help with Japanese translation and proofreading.
deconbatch@gmail.com

**Comment by hyesmo** [comment]
> Hi everyone and thanks again for offering your help 😊
> 
> I've sent e-mails out to @Nancy-Chauhan @3ru @arthurrlima @MiguelElizalde @hyesmo and @Sillenaj. If you haven't received them please check your spam filter 👀
> 
> We still need more translators and proofreaders so if you know someone who could help with translation/proofreading in your language (or one of the other languages), please share this page with them 🙏

Hi, I still didn't receive the mail. Checked spam folder too.

**Comment by tepat** [comment]
Hi, I can help with proofreading on French translation !
You can contact me at tepath[at]gmail.com

**Comment by ghost** [comment]
Hi! Native Russian speaker here, could do a translation one.
lelidisworld@gmail.com

Telegram - @Lileinit

**Comment by SableRaf** [comment]
Emails sent to @tepat @Lileinit and @deconbatch (sent by @3ru directly) . Check your spam folder if you haven't received anything 👻

**Comment by bedirxanugur** [comment]
Hi! I would like to help with Turkish translation and proofreading.
bedirxn[at]gmail.com

**Comment by achimkoh** [comment]
i can proofread korean on weekends. achim.koh@gmail.com

**Comment by bymaer** [comment]
Hi! I’m native Russian speaker, I can proofread this

t.me/bymaer

**Comment by onix** [comment]
Hi! Can translate into Ukrainian, vadimnekhai at gmail.com

**Comment by pkvl** [comment]
Hi! I'm a native Ukrainian speaker, can proofread this: anroypaul at gmail.com

**Comment by LoubiTek** [comment]
Im French ! :)

**Comment by cuongleqq** [comment]
I am a native Vietnamese speaker. I can translate this. cuongleqq at gmail.com

**Comment by SableRaf** [comment]
E-mails sent to @tepat @cuongleqq @LoubiTek. Please check your spam folder if you haven't received it 📬

**Comment by SableRaf** [comment]
Email sent to @Veer0x1 too 👀

**Comment by Iu1yota7h** [comment]
Can you send an email to tranngocha2005@gmail.com and michael@bitmark.com for the Vietnamese version?

**Comment by SableRaf** [comment]
Note: I updated the progress bars to make them more legible. Translated but not proof-read is now shown as 50% instead of 90%

**Comment by monstrim** [comment]
Brazilian, available for proofreading :) I'm on twitter and gmail on the same handle as here

**Comment by SableRaf** [comment]
Hi @monstrim I sent you an e-mail. Check your spam filter if you didn't receive it :)

**Comment by SableRaf** [comment]
All translations are now complete! Thanks a lot to all of you for your help 🥰
