### ISSUE TITLE
Library version number parsing does not ignore comments

### ISSUE THREAD

**Issue by prisonerjohn** [benfry/processing4#586]
## Description

Processing 4 Contribution Manager appears to include `# comments`  in the property values, which causes number parsing for `version` value to fail.

It looks like maybe this was already reported in #553 but it was closed for inactivity.

## Expected Behavior

If the properties file includes a line like:
```
version = 12  # This must be parsable as an int
```
The parser should ignore the `#` and everything after it when retrieving the value.

Processing 3.5.4 appears to do this correctly.

![image](https://user-images.githubusercontent.com/119702/199068709-861af808-d8ea-4f94-aedd-5035591af34b.png)

## Current Behavior
Processing 4.0.1 includes comments in the library `prettyVersion` and complains about "The version number for “XXX” is not a number."

![image](https://user-images.githubusercontent.com/119702/199068877-01a040b8-9592-4012-a6a6-230b3ebf02d6.png)

## Steps to Reproduce

1. Open the Processing Contribution Manager
2. Try to download the library `nub` or `websockets`

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: Windows 11
* Other information:

**Comment by benfry** [comment]
Ah, that makes more sense than the report in #553. Should be straightforward to fix.

**Comment by benfry** [comment]
Fixed for 4.0.2. The problem was that in-line comments (versus comments starting at the beginning of a line) were disabled so that it was possible to parse hex colors from settings files. (Otherwise, a hex color just looks like a comment.) Split the two cases and we should be all set.
