### ISSUE TITLE
Weird behavior Closing and reopening SerialPort in Windows. Bug?

### ISSUE THREAD

**Issue by PAk-CatchFire** [benfry/processing4#588]
Hello I am trying to close and reopening a serial port in Windows ( CP210x driver) and it is not possible.

Iam using the following code:
` serial.clear();

      serial.stop();

      serial = new Serial(this, serialPort, BaudRate);`

and the stop is done correctly, because if I try to reopen then the port with an external application it works, but processing is unable to open it again.

Processing will never recover communications again, since after closing the port and reopening the serial.available() is zero.

Do you experience the same?

**Comment by benfry** [comment]
This is a better question for the forum: https://discourse.processing.org/
