### ISSUE TITLE
No offline documentation

### ISSUE THREAD

**Issue by ukrustacean** [benfry/processing4#589]
## Description

There is neither offline reference documentation distributed with IDE nor any obvious and easy way to download one. That creates big difficulties when dealing with regular power outages.

## Expected Behavior

Menu -> `Help` -> `Reference` in IDE must open bundled offline documentation (in any common format, HTML or PDF, for example) same way it was in Processing 3.x IDE.

## Current Behavior

Menu -> `Help` -> `Reference` in IDE opens links to https://processing.org/reference

## Steps to Reproduce

1. Open IDE
2. Click `Help`
3. Click `Reference` in dropdown menu

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: Manjaro Linux, x86_64 GNU/Linux 5.15.76
* Other information: None

## Possible Causes / Solutions

If there is no possibility to bundle documentation with IDE, it is possible to overcome this in two ways:
1) Add `Download` button on https://processing.org/reference with already prebundled documentation available.
2) Add instruction to build it yourself somewhere on main site.

**Comment by benfry** [comment]
Yeah, sorry, totally agree: https://github.com/processing/processing4/issues/524

**Comment by benfry** [comment]
Partially resolved with 4.1 (not posted yet but arriving soon) https://github.com/processing/processing4/issues/524#issuecomment-1328233261
