### ISSUE TITLE
response (i cant talk in #565 - its locked)

### ISSUE THREAD

**Issue by Matto58** [benfry/processing4#590]
> Not stupid at all—that should be working without you having to save the theme file explicitly like that.
> Is there something that might be resetting your preferences file when you restart? i.e. is this a public or school lab machine?

_Originally posted by @benfry in https://github.com/processing/processing4/issues/565#issuecomment-1303966011_

its my own computer that i had for years now that i use for my personal stuff

**Comment by benfry** [comment]
Sorry about that! Thought I'd unlocked the issue. Following up there…
