### ISSUE TITLE
Feature request: adding "template" functionality so the the IDE never opens "blank".

### ISSUE THREAD

**Issue by Pomax** [benfry/processing4#593]
## Description

Right now, the IDE will always open on a blank file, but it would be super useful if there was a templates dir that Processing looked in, in order to prefill the IDE when it's started, similar to DAW software, or closer to Processing, how the Arduino IDE has "examples" (but better, because examples are a step too far in this case).

For example, there could be `Processing/templates` dir with an `empty` dir in that just has a single, empy, (read-only) .pde file, as well as a `minimal` dir that has a single `.pde` file with content like:

```
void setup() {
  size(100, 100);
  // build out your initial setup here!
}

void draw() {
  // start writing!
}
```

as well as an IDE preferences option for which template to always start up with, set to `empty` by default, scanning the `templates` dir on startup so that folks can also add their own template code to use. That way, folks can simply put code they use in almost all their sketches in a sensibly named dir inside Processing/templates, update the IDE settings to say to use that dir as its default template, and thus solve a problem that some folks know they have, but many folks don't even realize they want solved =)

The IDE could then also have a second "new" option under the file menu called "new from template" that expands into the list of possible templates to pick from (similar to "open recent"), so that people can simply get to "the thing they want to do" rather than having to spend time and effort getting set up before they can start creating the graphics they wanted/needed to.

(and possibly some `.mode` file or something that tells Processing that it's a java, or python, or etc. project? But that's more a nice-to-have on top of the huge improvement just having templates would be)

**Comment by benfry** [comment]
Basic template support has been in place since Processing 3.2:
https://github.com/processing/processing/wiki/Templates

**Comment by Pomax** [comment]
Sorry - yes, but that's very basic support, this is more about getting "real" templates, with as many per mode as users need (because they write different types of sketches), with normal UI for "new from template" etc.  Right now Processing supports "template", not "templates" =)
