### ISSUE TITLE
command clicking on a variable name freezes processing

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#595]
processing 4.0.1
osx 15.7.1

If you [command] + [click] on `chars` processing will freeze:

```java
void test_hslab() {
  char[] chars = {'H', 'S', 'L', 'A', 'B'};
}

void test_hslab_2() {
  char[] chars = {'•', 'H', 'S', 'L', 'A', 'B'};
}
```

This is related to the usage window, if you delete the second function for example you get:

<img width="298" alt="Screenshot 2022-11-10 at 15 29 29" src="https://user-images.githubusercontent.com/738650/201118408-19b18e47-ef58-44ab-9902-895d13dbd5c9.png">

**Comment by benfry** [comment]
Hm, that's working for me. Is this different from #527 and #551 or just a problem with the “Usage” window?

**Comment by clankill3r** [comment]
Probably the same, I asked the guy from the OP in #527 if the freeze happens for him with this code.

**Comment by benfry** [comment]
Gonna close this as duplicate of #527 for now.
