### ISSUE TITLE
Sketches not running PROCESSING

### ISSUE THREAD

**Issue by JulietaDallaPozza** [benfry/processing4#598]
Hey guys,

I'm an absolute noob here so please forgive me if I'm asking a stupid question. I just decided to jump into processing and this is really frustrating for me.

I opened the first example of arrays from the library and when I try to hit run I get no result. Not receiving any error in the console ev seems to work fine but not a window pop up
Theres just no response.

Any help please??

**Comment by dkgrieshammer** [comment]
Hey, pls share your System details & Code;

**Comment by JulietaDallaPozza** [comment]
its with any code... nothing happens, no sketch show up
not error nothing

**Comment by JulietaDallaPozza** [comment]
Thank you for your help :):):)

**Comment by dkgrieshammer** [comment]
Which System are you on, Win or Mac and which Version? You're using Processing 4.0.1 I suppose?

**Comment by JulietaDallaPozza** [comment]
Yes, catalina and 4.0.1

**Comment by Jean-no** [comment]
You should better tell that on the forum in order to get help : [https://discourse.processing.org/](https://discourse.processing.org/)

**Comment by JulietaDallaPozza** [comment]
Yes i did, but did not receive any answer unfortunately

**Comment by Jean-no** [comment]
I don't see the topic. Where is it ? I'd be glad to help, but this thread should be closed, it's not the good place.

**Comment by dkgrieshammer** [comment]
Depends, if it's a bug it could live here; but since there is no details and no code, this seems to be more a support related question on getting started so maybe discourse it the place to take it.

**Comment by benfry** [comment]
Yes, please use the forum for these questions: https://discourse.processing.org/
