### ISSUE TITLE
cleaning up build/macosx/jdk-0u1.tgz and build/macosx/jdk-11.0.1+13/

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#6]
The current build creates two files not covered by `.gitignore` that we should sort out. 

	build/macosx/jdk-0u1.tgz
	build/macosx/jdk-11.0.1+13/

The first one looks like it's using and old `substring()` call to clean up the name of the downloaded JDK… It should be something like `jdk-11.04.tgz` or whatever the syntax is nowadays. 

For the second, do we need this temp folder kept around? In the past we built the app and then have the JDK embedded there… second copy in the repo is another 200 MB (plus another 100MB for JavaFX). 

Same goes with naming for JFX bits… Something like `javafx-11.0.2.zip` should work, and if we need the folder there, keeping the same name.

**Comment by sampottinger** [comment]
Hey @benfry! I attempted to resolve this with #12. Can I close this issue or is there more you want to tackle? Thanks!

**Comment by benfry** [comment]
All set; thanks.
