### ISSUE TITLE
Application exported in a wrong folder

### ISSUE THREAD

**Issue by Jean-no** [benfry/processing4#601]
## Description
Sometimes, when exporting an application, the files are not created in the right sketch folder but in another folder.

## Expected Behavior
The application folders should be exported in the sketch folder of the current program

## Current Behavior
The application folders are created in the sketch folder of another program (wich has once been opened in the same session, I guess it means that the path is wrongfully remembered)

## Steps to Reproduce
I don't now if it cas easely be reproduced, but it happened to me more than once. I fist I thought the app wasn't created at all, but once I noticed it was just made in a wrong place.
1. work on a first program
2. work on a second program
3. export the second program as application (with Java embed)
4. see that the export can't be found in the right folder

## Your Environment

 

* Processing version: 4.01
* Operating System and OS version: Kubuntu 20.04 with Plasma 5.18.8
* Other information: I also have path-related issues when loading a csv file. There are no spaces in the path.

## Possible Causes / Solutions
It seems to me that the path of a formerly opened sketch was kept and used for the current sketch at the moment of the export.

**Comment by Sachin-2206** [comment]
@Jean-no Hello Sir, I want to contribute in this issue. Can you please tell me about this more?

**Comment by Jean-no** [comment]
Hi ! I can't really tell you more, I will try to pay attention next time I perform an app export (I didn't notice the same thing lately)

**Comment by benfry** [comment]
Can anyone else confirm that this is happening? I haven't seen anything like it and haven't been able to reproduce the behavior.

**Comment by benfry** [comment]
Just ran into what's happening here… Will be fixed for 4.1.4 or 4.2 (whatever release comes after 4.1.3).
