### ISSUE TITLE
RotatingArcs in 3D doesn't display any error but window is not visible.

### ISSUE THREAD

**Issue by ghost** [benfry/processing4#603]
## Current Behavior

Java runs but no visible output 

## Steps to Reproduce

1. Open the Rotating Arcs in 3D example
2.
3.

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: macOS Ventura 13.0.1
* Other information: Apple M1

**Comment by ghost** [comment]
possible cause P3D incompatible with Ventura

**Comment by benfry** [comment]
Assuming this is a duplicate of https://github.com/processing/processing4/issues/544
