### ISSUE TITLE
Extreme slow performance of image() on Apple Silicon Mac (Ventura) using standard renderer

### ISSUE THREAD

**Issue by rapatski** [benfry/processing4#604]
## Description
When using the standard renderer, rendering an image on my current Mac (Apple Silicon M1 Max, macOS Ventura) has extreme impact on performance (4FPS for fullscreen on the 5K display). Stretching the image using the width/height params of image() seems to be quite a hefty hit also, but this may be normal and I never noticed.
Switching the renderer to P2D using the GLProfile.initSingleton() workaround on Ventura gives a more expected 600-700fps.

## Expected Behavior
I expect performance of the standard renderer to be more on par with that of the P2D renderer.

## Steps to Reproduce

1. Set up sketch using size() not specifying a renderer
2. Load image in setup()
3. Render image using image() in draw()
4. Notice frame rate drop

## Example Sketch

```
import com.jogamp.opengl.GLProfile;
{
  GLProfile.initSingleton();
}

PImage img;

void setup()
{
  //size(1650, 900);  // 4 fps
  fullScreen();     // 4 fps
  //fullScreen(P2D);  // 600-700 fps
  
  pixelDensity(displayDensity()); // compounds the issue, but by 50% as expected
  
  /*
   load image
   dimensions or format do not matter; 
   256x256px or 4K image give the same fps results
   jpg or png same results
  */
  img = loadImage("test.png"); 
  
  frameRate(1000);
}

void draw()
{
  imageMode(CENTER);
  image(img, width/2, height/2, width, height);       // 4 fps on standard renderer
  //image(img, width/2, height/2, img.width, img.height); // 42 fps on standard renderer
  
  textAlign(CENTER, CENTER);
  text(nf(frameRate, 1, 2), width/2, height/2);
}
```

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: macOS 13.0.1 (22A400) Ventura
* System Spec: Apple Silicon M1 Max 32GB, GPU 32 cores

**Comment by benfry** [comment]
Yeah, Java2D (the default renderer) is just really slow for this sort of thing. It's why we have the `P2D`, `P3D` and JavaFX renderers as options. Drawing to a full screen is one of the worst scenarios, sadly, but it's out of our control.

The default renderer is slow but most accurate for rendering 2D. There shouldn't be an expectation that it's the same speed as highly accelerated OpenGL (which also trades off quality for performance).

**Comment by rapatski** [comment]
Hi Ben!

Yeah, I know there was always a discrepancy, so maybe I worded my expectation above a bit wrong; I don't expect the performance to match, but this difference is _huge_ - I've been working with Processing for the past 15 years, and I do believe that 25ms (40fps) to render just a 256x256px image at 256x256px on a full screen window is not normal? (or at least I hope it not to be, on such a monster of a machine?)

Anyway, that said, taking this opportunity to express my appreciation for your project. Still absolutely love it. 💪

T

**Comment by dzaima** [comment]
98% of the runtime of that sketch is spent in `sun.java2d.SunGraphics2D.drawImage()`, so Java2D really just is that slow. (I'd assume even with CPU-based rendering it should be able to be faster, but it isn't, and this is out of scope of Processing anyway.)

**Comment by benfry** [comment]
Yes, it truly sucks. Especially with retina, especially full screen. Again, that's why I put all that time into the JavaFX renderer (and OpenGL before it) because it's just abysmal in these situations. There are ways to get more speed out of it, but it's far, far too much effort and the improvement is minimal.
