### ISSUE TITLE
PApplet.selectFolder not found

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#61]
Travis noticed that we broke the build on `PreferencesFrame`: https://travis-ci.org/sampottinger/processing4/builds/639584837?utm_medium=notification&utm_source=github_status.

**Comment by sampottinger** [comment]
@benfry, I can take this but should chat about getting Travis here again since it's still running on my fork.

**Comment by benfry** [comment]
I think I've caught the ones I missed due to the bad linking. 

Might need to rethink how they're handled though—I'd prefer the methods live in Toolkit() for the `processing.app` side of things, but it seems silly to just copy & paste the code in two places.

**Comment by benfry** [comment]
@sampottinger If you don't find any others, you can go ahead and close this.

**Comment by sampottinger** [comment]
Hey @benfry looks like you got everything (https://github.com/processing/processing4/commit/6979ece6f3c7c9ef9c045bd479e3b00130061d47). I'll close this out!
