### ISSUE TITLE
Processing doesn't recognize methods of PApplet when the sketchfolder has a hyphen in it

### ISSUE THREAD

**Issue by mythicaleinhorn** [benfry/processing4#610]
## Description

When the name of a sketch folder contains a hyphen, Processing doesn't recognize the methods of `PApplet` like `draw()`, `background()`, etc.
The sketch will compile and run without any problems anyway.

## Steps to Reproduce

1. Create a sketch in a folder with a name containing a hyphen
2. A `sketch.properties` file is created pointing to the main file (which can't have a hyphen in it, Processing will refuse to start in that case)
3. Processing won't recognize the methods of `PApplet` anymore (`draw()`, `background()`, etc.)

## Your Environment

 

* Processing version: 4.1.1
* Operating System and OS version: TUXEDO OS 1 (KDE Plasma) / Windows 11
* Other information: This problem exists since 4.1.0

**Comment by mythicaleinhorn** [comment]
Suggested fix:
Adding a check similar to https://github.com/processing/processing4/blob/1e1d1964eef5a2660296d56ce68f4612b1c9e33e/app/src/processing/app/Base.java#L1606-L1615 to check for hypens in a folder name.

**Comment by clankill3r** [comment]
This does not happen on OSX. But it does indeed happen on windows.
The thing is, instead of a "sanitary check", it would be better to find why it breaks with a hyphen and fix that.

**Comment by benfry** [comment]
@sampottinger Any quick thoughts? (Not your fault, just that you were in this code recently dealing with incorrect/superficial errors/warnings being reported.)

This is another split between the live error checking and the generated code that's actually run. It looks like there's probably an assumption about class name being the same as the main tab name or the folder name, so this is showing errors when the sketch folder doesn't match up (i.e. it has spaces, hyphens, anything else that's now allowed if you un-check “Keep sketch name and main tab in sync”.

**Comment by sampottinger** [comment]
Weird. Yeah it could be something with the edt edit generation. It's strange that it is OS specific though. I'll take a look.

**Comment by benfry** [comment]
I'm seeing it on macOS, I don't think it's OS-specific. To reproduce:

1. Uncheck the pref to keep sketch name and tab in sync
2. Do a “Save As” and re-save the sketch to a folder that has spaces or hyphens in the name
3. You should see red squiggles in the editor area for built-in functions

(i.e. potentially nearby the other bit you had just fixed w/ error squiggles.)

**Comment by benfry** [comment]
Here's an example: [issue4 0610 hyphen trouble.zip](https://github.com/processing/processing4/files/10422141/issue4.0610.hyphen.trouble.zip)

**Comment by sampottinger** [comment]
Ah I must have misinterpreted an earlier comment. I'll try to take a look tomorrow!

**Comment by sampottinger** [comment]
Actually I think I have a minute let me pop in now @benfry

**Comment by benfry** [comment]
All set for 4.1.2 thanks to @sampottinger.
