### ISSUE TITLE
Trojan detected (Windows Security software)

### ISSUE THREAD

**Issue by grospoulpe** [benfry/processing4#612]
## Description
Detected (Windows Security software) TrojanDownloader:Java/OpenConnection.PM
First time ever (no problem with v 4.0.1)

## Expected Behavior
no detection of virus or something

## Current Behavior
TrojanDownloader:Java/OpenConnection.PM

## Steps to Reproduce
(re)download the Windows Intel x64 4.1.1

## Your Environment

 

* Processing version: 4.1.1
* Operating System and OS version: Windows 11 2022H2 x64
* Other information:

## Possible Causes / Solutions
false positive ? a file to clean up?

Thanks.

**Comment by EdwardFantasia** [comment]
I got the same thing and I was very confused as all I did was install the IDE. Hoping they fix this soon.

**Comment by renaudfv** [comment]
+1 on this.
4.1.1 was not working and then 4.0.2 triggered this warning.

**Comment by Hulyan** [comment]
Same issue for me. However, it worked for like the first-ever installation. The second I tried to open it, it showed errors like this malware.

**Comment by benfry** [comment]
It's not malware, more here: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

I've submitted the false positive to Microsoft, and hopefully they'll fix it.
