### ISSUE TITLE
Mode manager window is empty

### ISSUE THREAD

**Issue by WolfyD** [benfry/processing4#613]
## Description
In Processing 4.1.1 it is currently seemingly impossible to download and switch between modes.

## Expected Behavior
In Processing 3.5.4 if you open the "Modes" tab in the "Contribution Manager" window, there is a list of modes you can potentially install. At the very least you should find "R Mode" and "Python Mode". You can download any of these (the ones that are supported anyways) and than can use them in Processing.

## Current Behavior
In Processing 4.1.1 (and 4.1 and possibly earlier versions I haven't tested) when you click "Manage Modes..." you are taken to an empty "Modes" tab in the "Contribution Manager" window. There are no modes ready to download, therefore you are stuck in Java mode.

## Steps to Reproduce
1. Run Processing 4.1.*
2. Click on the selector with the word "Java" and a little downward triangle in it
3. Click on "Manage Modes..."

## Your Environment
* Processing version: 4.1.1
* Operating System and OS version: Windows 11 Pro x64 22H2 Build: 22621.900

## Possible Causes / Solutions
Not sure about the cause but I found a workaround (though haven't tested fully).
I downloaded Processing 3.5.4 and installed Python mode on it.
I than opened Processing 4.1.1 and I found that it also had Python mode installed.
The Modes tab was still empty, but apparently the mode for 3.5.4 was saved in the same place 4.1.1 was looking, and it at least thinks it can be used. I'm not sure how well it works.

Image:
![image](https://user-images.githubusercontent.com/6439157/204891586-96bee15a-c6b1-41ae-a295-c66902c92a62.png)

**Comment by SableRaf** [comment]
For what it's worth this doesn't seem to be limited to Windows 11. I noticed the same issue on macOS.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/290261/205065111-350fb938-db50-4a37-9177-5cf066488399.png">

**Comment by drvnprgrmr** [comment]
I have this same issue on Zorin (Ubuntu based)

![image](https://user-images.githubusercontent.com/67306305/205201063-5e3c15d6-a4ed-41fc-9274-2f1ac029050a.png)

**Comment by 7k50** [comment]
Same on MacOS Ventura, running on Apple Silicon. I installed Processing just today via Homebrew Cask.

**Comment by cannibull** [comment]
Same issue here on Linux Mint. I encountered the same quirk WolfyD did where installing python mode for Processing 3 resulted in it appearing in the mode select drop-down in Processing 4 but it doesn't seem to work at all; anything I put in spits out the same error.
![image](https://user-images.githubusercontent.com/41491123/205455454-f69332dd-b63d-4f97-80a0-977041e11098.png)
The mode manager is also still totally empty.
![image](https://user-images.githubusercontent.com/41491123/205455487-93b0c140-e14b-45ca-b6c6-e84f2e9f9ad0.png)

**Comment by rjsworking** [comment]
Processing 4.0.2 has the same issue. v4.01 is ok.

**Comment by npeters97** [comment]
I am having the same problem with Processing 4.1.1 on Mac OS Monterey on Apple Silicon.

**Comment by hkiel** [comment]
Workaround is to open the library manager and switching to "modes" tab. At least that's what works here (macOS M1, 4.1.1). I can confirm the bug. Also note, that you should not use the "manage modes" drop down item at all, if you want the workaround to work ;-)

**Comment by WolfyD** [comment]
> Workaround is to open the library manager and switching to "modes" tab. At least that's what works here (macOS M1, 4.1.1). I can confirm the bug. Also note, that you should not use the "manage modes" drop down item at all, if you want the workaround to work ;-)

I tried that and yes, that definitely works on Windows 11 x64 with Processing 4.1.1! :D

**Comment by 7k50** [comment]
> Workaround is to open the library manager and switching to "modes" tab. At least that's what works here (macOS M1, 4.1.1). I can confirm the bug. Also note, that you should not use the "manage modes" drop down item at all, if you want the workaround to work ;-)

Below seems to work on MacOS, **if** you don't use the "Manage Modes" dropdown first. If else, you need to restart the app first.

**_Menu Bar > Sketch > Import Library > Manage Libraries > Modes_**

**Comment by WolfyD** [comment]
> > Workaround is to open the library manager and switching to "modes" tab. At least that's what works here (macOS M1, 4.1.1). I can confirm the bug. Also note, that you should not use the "manage modes" drop down item at all, if you want the workaround to work ;-)
> 
> Below seems to work on MacOS, **if** you don't use the "Manage Modes" dropdown first. If else, you need to restart the app first.
> 
> **_Menu Bar > Sketch > Import Library > Manage Libraries > Modes_**

Yes, after testing it's clear, if you try to open it through the modes dropdown first, than it won't work.
I actually found a way through 

**_Tools > Manage tools > Modes_** 

Hope that helps :)

**Comment by hkiel** [comment]
> Yes, after testing it's clear, if you try to open it through the modes dropdown first, than it won't work. I actually found a way through
> 
> **_Tools > Manage tools > Modes_**
> 
> Hope that helps :)

When you do this then the Tools tab will be empty!
Both bugs seem to be connected. I guess once the one problem is found and solved, the other should be either already fixed or easy to fix.

**Comment by jetsup** [comment]
Have been having the same problem. None of the work around worked on my end. I'm running Kali Linux.

**Comment by kaibochan** [comment]
Fresh installed Processing just a few moments ago and on Windows 10. Running into the same issue as above. Tried all the above workarounds and Modes tab is still empty.

**Comment by mbrotz** [comment]
I have the same issue with Processing 4.1.1 on macOS Monterey. None of the above workarounds works for me.

**Comment by diwakar1998** [comment]
> Fresh installed Processing just a few moments ago and on Windows 10. Running into the same issue as above. Tried all the above workarounds and Modes tab is still empty.

the workaround Tools->ManageTools->Modes worked for me. If u first tried to change mode using the top right menu then try to restart processing once and try again

**Comment by bitsbau** [comment]
I tried all the three methods but it's all empty.

**Comment by hkiel** [comment]
> I tried all the three methods but it's all empty.

You need to restart processing each time the menu gets empty. Open the library manager from a fresh restart and then select other tabs.

**Comment by cheng3100** [comment]
> I tried all the three methods but it's all empty.

Just like @hkiel said you need restart processing firstly and not click the drop-down menu of the mode button. @WolfyD 's method work for me in win10 platform.

**Comment by benfry** [comment]
Resolved for 4.1.2. 

In the meantime, avoid using “Manage Modes…” and use any other method to open the Contribution Manager (clicking the update count in the lower-right of the window, using Manage Libraries or Manage Tools, etc). As soon as you select “Manage Modes”, you'll have to restart Processing before these alternatives will work again. Thanks @hkiel for identifying that.

**Comment by hkiel** [comment]
BTW, do not open via "Manage Tools", as this will make the tools tab unusable. The only two fully working ways are "Manage Libraries" and update count. After doing that you can use any way to open the manager window.

**Comment by benfry** [comment]
Thanks for the clarification!

**Comment by bitsbau** [comment]
@hkiel @cheng3100 Thanks. I didn't make it work through the way you recommended. However, I opened one of the sample files and through that file the modes appeared.

**Comment by benfry** [comment]
No need to use the workaround; please download 4.1.2 instead.
