### ISSUE TITLE
Tool to create JavaDoc for sketches

### ISSUE THREAD

**Issue by hkiel** [benfry/processing4#615]
## Description
Sketches are preprocessed before they are sent to the Java compiler to have a valid Java syntax. This preprocessing should also be done before sending the sources to `javadoc`.

## Expected Behavior
It would be nice to be able to generate JavaDoc for sketches from within Processing.

**Comment by benfry** [comment]
Thanks; this would be a good project for a “contributed” Tool (https://github.com/processing/processing/wiki/Tool-Overview), but not something that we plan add to the software.

**Comment by hkiel** [comment]
How do I retrieve the preprocessed code of a sketch? The plain pde cannot be sent to javadoc (no encapsulating class).

**Comment by benfry** [comment]
If you use “Export to Application” it will create a source folder for you that includes the preprocessed code.

**Comment by hkiel** [comment]
Is it possible to trigger preprocessing/exporting by a tool?
Otherwise it would be good if a tick box could be added to "Export to Application" where user can select "Generate JavaDoc". Also, the source folder is inside the arch folder and depends pn which target you build.

Anyways, maybe worth a second ticket: I can export one sketch, but if I try to export a second sketch directly afterwards, nothing is created. Only the sketch folder is opened.

**Comment by hkiel** [comment]
I created a tool to generate javadoc: [hkiel/JavaDoc#1](https://github.com/hkiel/JavaDoc/)

**Comment by hkiel** [comment]
@benfry What do I have to do to make it public?
The latest version can be obtained from
[https://github.com/hkiel/JavaDoc/releases/latest/download/JavaDoc.txt](https://github.com/hkiel/JavaDoc/releases/latest/download/JavaDoc.txt)
[https://github.com/hkiel/JavaDoc/releases/latest/download/JavaDoc.zip](https://github.com/hkiel/JavaDoc/releases/latest/download/JavaDoc.zip)

The documentation for tools still links to old github repository. Also the tool-template is using java1.7 and seems rather outdated.
