### ISSUE TITLE
Help menu items inactive on macOS

### ISSUE THREAD

**Issue by hkiel** [benfry/processing4#617]
## Description
All items of the help menu are occasionally inactive. 

## Expected Behavior
Help menu items should be active.

## Steps to Reproduce
Could not yet find a way to reproduce, but it happened multiple times.

## Your Environment
* Processing version: 4.1.1
* Operating System and OS version: macOS Monterey M1

**Comment by benfry** [comment]
Damn, this is a Java issue that we can't fix. It was first reported in the repository for 3.x and earlier: https://github.com/processing/processing4/issues/638

I was hoping that the new Java 17 we're using fixed it.

**Comment by benfry** [comment]
Closing as duplicate of https://github.com/processing/processing4/issues/638 (the old issue now moved to this repo).
