### ISSUE TITLE
cannot use @Override and @Deprecated in static mode

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#619]
I just updated Processing for version 4.1.1 and now when I run sketch when there is 
`@Override` `@Deprecated` inside `class` Processing don't run, that's a regression ? or there is a goal behind that ?
Before that's work fine withe processing 4.0b7... and all the version before that from 1.5.1

the console return:
```
Cannot find a class or type named @Overridepublic...
```

or 
```
Cannot find a class or type named @Deprecatedpublic...
```

And always bravo for the Processing Team !!!!

**Comment by benfry** [comment]
@sampottinger Possible regression with the preproc changes?

**Comment by sampottinger** [comment]
Yeah I'll take a look @benfry! @knupel are you comfortable sharing a code example?

**Comment by knupel** [comment]
Hi @sampottinger I think it's something like that : 
```
class Truc {
  Truc(){}
  @Deprecated void machin() {
  }
  
  
  @Override String toString() {
    return "oalala";
  }
}
```
I try to make something simple with my tiny time, the problem is here for `@Override`
https://github.com/knupel/Rope_framework/blob/master/Rope_framework/Z_R_Table_info.pde#L1222

and here for @Deprecated
https://github.com/knupel/Rope_framework/blob/master/Rope_framework/Z_R_Science.pde#L455

If you need more information, I can work on it this week-end

**Comment by sampottinger** [comment]
This is great thanks! Will see if I can take a look at this either this weekend or early next week.

**Comment by sampottinger** [comment]
Thanks @knupel! We seem to be passing our current annotations unit test but possible I missed something. I’ll try to make a new test to address your case.

**Comment by sampottinger** [comment]
@benfry made fix at #622. Note that I believe #619 does not impact most uses of annotations. I think this is limited to the following:

method with no visibility modifier && method with annotation && (static mode || class definitions extending PApplet)

See https://github.com/processing/processing4/blob/main/java/src/processing/mode/java/preproc/PdeParseTreeListener.java#L530. Thanks!

**Comment by knupel** [comment]
Thx a lot !!!!

**Comment by benfry** [comment]
Awesome, thanks Sam.

This will be in 4.1.2.

**Comment by tomuGo** [comment]
can early version work?

**Comment by sampottinger** [comment]
Hey @tomuGo! I think the fix was accepted. So the resolution for this will be included in the next processing release. Also, if you build processing yourself, the fix is currently on main. Does that help?

**Comment by sampottinger** [comment]
Sorry @tomuGo you might be able to use 4.0.2 to get around this. I think this is before the issue came up - https://github.com/processing/processing4/releases/tag/processing-1287-4.0.2
