### ISSUE TITLE
PGraphicsPDF build broken

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#62]
Looks like PGraphicsPDF is failing:

```
PGraphicsPDF.java:431: error: cannot find symbol
    [javac]       g2.drawImage(image.getImage(), 0, 0, null);
```

**Comment by sampottinger** [comment]
Found via Travis on sampottinger fork

**Comment by sampottinger** [comment]
Looks like https://github.com/processing/processing4/blob/master/java/libraries/pdf/src/processing/pdf/PGraphicsPDF.java#L431 is referring to now deprecated getImage.

**Comment by benfry** [comment]
I think this one is set now; but it looks like you had some other testing bits on that branch so I'll leave it open until you give the thumbs up.

**Comment by sampottinger** [comment]
Hey @benfry! Looks like this is resolved with https://github.com/processing/processing4/commit/624e9074aeb1d9e2e6b2943e35ffd97a90b8b737. I'll close this out.
