### ISSUE TITLE
''TrojanDownloader:Java/OpenConnection.PM'' whenever I try to open Processing

### ISSUE THREAD

**Issue by Diegogc1901** [benfry/processing4#620]
Hello!

I'm starting my coding journey and yesterday I downloaded Processing. 
Everything went fine until today, when I tried to open the program again, I received a Windows Defender alert and it's related to a ''TrojanDownloader:Java/OpenConnection.PM with this exact location

file: C:\Users\Diego\Documents\PROGRAMMING\PROCESSING\processing-4.1.1\core\library\core.jar

I deleted it and tried to extract the files again with Winrar again, and the same thing happened.

Has this happened to anybody else?
Thanks in advance

![processing](https://user-images.githubusercontent.com/120117670/206487479-c286fff6-2200-4986-82be-ed29e742988f.JPG)

**Comment by clankill3r** [comment]
https://github.com/processing/processing/issues/6202

**Comment by benfry** [comment]
Please see https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans
