### ISSUE TITLE
Cannot use keyboard shortcut for Comment/Uncomment on macOS with French keyboard - help me contribute a fix!

### ISSUE THREAD

**Issue by mglst** [benfry/processing4#625]
## Description
The ⌘ + / keyboard shortcut for Comment/Uncomment does not work for me. I'm on a mid 2015 MacBook pro with a French keyboard, running macOS 12.6.3 and Processing 4.0.1. For reference, other users have encountered similar difficulties in this [issue](https://github.com/processing/processing/issues/2199). The problem is that on the French keyboard, shift is needed to type a slash. However,

## Possible Causes / Solutions
I've found a workaround / solution! The character 'below' slash e.g. without using shift is colon. I've added `menu.edit.comment_uncomment.keystroke=meta pressed COLON` to my preferences.txt file, and I'm now a happy camper. I imagine other people on a MacBook with a French keyboard might benefit from this being default behaviour.

- Should I contribute this preference to PDE_fr.properties?
- My keyboard is French, but my macOS system language is English. Does PDE_fr.properties get used in my case?

**Comment by benfry** [comment]
If the language chosen in the Preferences dialog is French, it will use PDE_fr.properties. 

There's no GUI support for "PDE is in English, but the keyboard is French". 

However, you can edit `preferences.txt` as you've done:
https://github.com/processing/processing4/wiki/Translations#in-the-preferencestxt-file

**Comment by benfry** [comment]
We can certainly add this to `PDE_fr.properties` which will be used for anyone who's using French as the language in Preferences; is that what you're asking to contribute?

**Comment by mglst** [comment]
It's unfortunate for my use case that Processing assumes my keyboard layout matches my language preference. I appreciate this is likely a niche scenario. I suppose the logical next step would adding GUI support for choosing both independently. I also imagine it's more trouble than it's worth!

In the meantime I've made a PR #660 editing `PDE_fr.properties`

**Comment by benfry** [comment]
Thanks for that… Do you have a sense of how this is handled with other editors? i.e. is this a standard key combination for comment/uncomment used by any others (like VS Code or IntelliJ or who knows what)?

**Comment by mrbbp** [comment]
on `macOS French`
`Command + =` to comment/uncomment :)

**Comment by benfry** [comment]
Ok, so we contradicting suggestions for Cmd-Equals and a PR that uses Cmd-Colon. :)

Can anyone on a French system let me know what's used by other editors (VS Code and IntelliJ in particular) when French is the language? I'd like us to be using something that others will be expecting (if there is such a thing) rather than making up our own.

**Comment by mglst** [comment]
Here are the results of some investigating on my French macOS system:

#### In VS Code (1.80.0)

Under `Preferences: Open Keyboard Shortcuts`:
- `editor.action.commentLine` has binding `⇧` `⌘` `:`
- `editor.action.blockComment` has binding `⇧` `⌥` `A`

For some reason, in the JSON file the keymap for `editor.action.commentLine` is incorrectly stored as `shift+cmd+[Period]` however the shortcut is correctly triggered with a colon - seemingly this is a quirk / bug.


#### In IntelliJ IDEA (2023.1.4):

- `Comment with Line Comment` has binding `⌘` `:` 
- `Comment with Block Comment` has binding `⌥` `⌘` `:`

On JetBeans official help page, there is a note about [non-English keyboard layouts](https://www.jetbrains.com/help/idea/keyboard-shortcuts-troubleshooting.html#do-you-have-a-non-english-keyboard-layout) which includes a note about the German keyboard layout not having a key for forward slash and so not having a shortcut to comment the current line. The recommendation is to install a plugin called [Keymap Nationalizer](https://plugins.jetbrains.com/plugin/14625-keymap-nationalizer). Neither of the above shortcuts work, Installing this plugin resolves this.

#### In Xcode (14.3.1):

- `Editor > Structure > Comment Selection` has binding `⌘` `:` 

This is the same keybinding as IntelliJ. Seemingly there is option for block comments, unlike VS Code and IntelliJ.

**Comment by benfry** [comment]
This is so helpful, thank you! That's now merged for the next release.
