### ISSUE TITLE
Modularity of core? #JPMS

### ISSUE THREAD

**Issue by neilcsmith-net** [benfry/processing4#63]
I'm currently working on a fork (for PraxisLIVE / Codelerity use) splitting up Processing Core, modularizing and pushing to Maven Central for our and other use.  Has any thought been given to splitting up Processing Core and using JPMS - eg. core (with abstract GL), AWT, JavaFX, JOGL(?), LWJGL, etc.?  Given increasing dependencies, modularity and possibly JLink might be good for handling sketch export in 4?

**Comment by benfry** [comment]
The forum is a better place for coding discussions. This is too open-ended to be resolved as an "issue".

**Comment by neilcsmith-net** [comment]
If that was actually useful I'd try it!  It's also not open-ended - it's quite specific.  Will discuss elsewhere.
