### ISSUE TITLE
GStreamer-CRITICAL **

### ISSUE THREAD

**Issue by koundinyad** [benfry/processing4#630]
## Description

Getting an error and a crash trying to run any of the code examples with Video Library 2.2.1 for Processing 4.

## Expected Behavior

Capture laptop camera

## Current Behavior

```(Processing core video:74521): GStreamer-CRITICAL **: 13:30:48.493: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed```
- PDE quits unexpectedly
- `Could not run the sketch (Target VM failed to initialize). For more information, read Help → Troubleshooting.`

## Steps to Reproduce
- Running any of the `Capture` code examples from https://processing.org/reference/libraries/video/index.html

## Your Environment

 

* Processing version: 4.1.1
* Operating System and OS version: M1 macOS Ventura 13.1
* Other information:

**Comment by SableRaf** [comment]
Hi and thanks for the report. This issue is being tracked here https://github.com/processing/processing-video/issues/208
