### ISSUE TITLE
Current implementation of `Runner` prevents remote debugging

### ISSUE THREAD

**Issue by haschdl** [benfry/processing4#633]
## Description

I am trying to attach IntelliJ to a running Processsing sketch, by using Attach to process.  I get Connection Refused, no matter what. 
`Error running 'localhost:8774': Unable to open debugger port (127.0.0.1:8774): java.net.ConnectException "Connection refused (Connection refused)"``

I examined the source code for `Runner.java` and I verify that remote debugging is enabled prior to running the sketch:
https://github.com/processing/processing4/blob/1e1d1964eef5a2660296d56ce68f4612b1c9e33e/java/src/processing/mode/java/runner/Runner.java#L210

However `Runner` also attaches to the running sketches. This in effect prevents other clients from remote debugging (assumption). 

https://github.com/processing/processing4/blob/1e1d1964eef5a2660296d56ce68f4612b1c9e33e/java/src/processing/mode/java/runner/Runner.java#L228-L294

What did to verify my assumption. Note this is not suggested as solution, only a hack to test the hypothesis.
- Identify the running processes related to running the sketch. 
There should two PIDs, one for the sketch itself, and a second for `processing-java`, which is listed as `Commander`
- Kill the `Commander` process. This will disconnect `processing-java` from the running sketch, but the sketch itself will continue to run.
- Try again to attach to the running sketch. This time attaching works, and breakpoints are hit.

## Expected Behavior
Attaching to running process should work as expected, and breakpoints hit.

## Current Behavior
Attaching to a running sketch gives the error `Connection refused`.

## Steps to Reproduce
1. Using `processing-java`, run a sketch using a custom library
2. From the IDE where the source code of the sketch is open, go to Run -> Attach to process.

## Your Environment
* Processing version: 4.0
* Operating System and OS version: MacOS 11.7 BigSur

## Possible Causes / Solutions

The code in `Runner.java` attaches to the running sketch in order to capture the output, but in effects prevents debugging.  
A possible workaround is to add another flag which would disable the portions of `Runner.java` that attach to the running sketch.

https://github.com/processing/processing4/blob/main/java/src/processing/mode/java/runner/Runner.java

**Comment by benfry** [comment]
Yeah, I don't think this is something we'd really want/need to support—if someone's using IntelliJ for remote debugging (or even know what “remote debugging” is), I'd recommend they be using IntelliJ instead of the PDE for development of their sketch.

To open it up further would also require looking into the security implications, and thus probably a new preference for making it (un)available, etc—just a lot of extra work for an esoteric use case that we'd not recommend anyway.

**Comment by haschdl** [comment]
@benfry I agree that changing this part of Processing is not a priority, however I wanted to clarify the use-case.

It seems I forgot to mention the most important part, that remote debugging was not a needed feature for using Processing and writing a sketch in an esoteric way. It is however a key feature for the proper development of robust libraries for Processing.

In other words, the need to attach a debugger to the PDE is to be able to test and troubleshoot custom libraries. The intention of doing that is to know exactly how a library behaves in PDE - so the opposite of an esoteric use case.  

There are of course other standard ways to test custom code within the IDE, but ultimately if the library is to be used from PDE, being able to test the library as a user would use it is kind of important. The convoluted way I described above is a workaround at least.  A proper debugging experience would have helped  e.g. https://github.com/processing/processing4/issues/631 

There might be simpler ways to achieve what I described related to killing a process, after running the sketch with `processing-java` - hopefully a more experienced library developer could chip in.

**Comment by benfry** [comment]
I see; that makes sense, thanks for the clarification.

Though if you're killing the hosting process, haven't you eliminated the reason for using the PDE in the first place? Once you've killed the PDE or Commander process, the only difference between running directly from IntelliJ is extra command line arguments passed that tell the sketch to send messages back to the PDE. You could still do that from IntelliJ.
