### ISSUE TITLE
Mode update not shown correctly in Contribution Manager

### ISSUE THREAD

**Issue by hkiel** [benfry/processing4#640]
## Description
I just installed new processing 4.1.2 with a pending update of Android mode.
I open the Modes Manager via drop down menu and do not see the Android mode in the list of modes (though it is installed).
Also in "Updates" tab "Timer" Library pretends to be updateabe (but with installed 1.0.1 vs. available 1.0.1 versions)

Timer is neither installed on my setup nor is it updateable. Looks like the index of updateable Android mode is used on Libraries list, showing the wrong thing.

## Steps to Reproduce
see above

## Your Environment
* Processing version: 4.1.2
* Operating System and OS version: win10

**Comment by benfry** [comment]
Can you post a screenshot of what the “Updates” tab looks like in this setup? 

Also, would you mind posting a zip of the Android Mode that needed to be updated so I can try to reproduce this?

**Comment by hkiel** [comment]
Processing 4.1.2 main window with update indicator:
![p4_main](https://user-images.githubusercontent.com/9904830/213202424-0b41d684-cfd0-45b8-a017-2eb8529a03b8.png)

I select "Manage modes" menu and see that there is a mode "Timer" which is actually a library. This should really be "Android Mode".
![p4_modes](https://user-images.githubusercontent.com/9904830/213202472-5cdaddfe-84c1-4c24-9223-e0e854311c52.png)

Same name mismatch on the update tab:
![p4_update](https://user-images.githubusercontent.com/9904830/213202517-6e804ee3-8ea7-4ff3-be2f-ad9efb8c11d8.png)

Here is the old Android mode zip:
[AndroidMode.zip](https://github.com/processing/processing4/files/10447526/AndroidMode.zip)

**Comment by benfry** [comment]
Great thanks; as suspected, that was something I saw show up while I was working on 4.1.2 all weekend… Thought I had a workaround for it, but it looks like it needs a more thorough fix.

**Comment by benfry** [comment]
Ok, I think we're set for 4.1.3… Will try to push that release out shortly, just a few things remaining to tidy up.
