### ISSUE TITLE
Windows is blocking 4.1.2 with virus warning

### ISSUE THREAD

**Issue by glasscanvas** [benfry/processing4#656]
## Steps to Reproduce

Download is blocked because a virus is reported. 

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:
Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM	16.0 GB (15.6 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎28/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by benfry** [comment]
It's a false detection: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

Please submit it to Microsoft (see instructions at the link above) so that they can fix it.
