### ISSUE TITLE
FAILED VIRUS DETECTED WINDOWS 11 DOWNLOAD

### ISSUE THREAD

**Issue by CPTNMTRCYCL3** [benfry/processing4#658]
## Description

When trying to download on Windows 11, zip file will attempt to download. Upon completion, if you try to open the downloaded .zip file, it will give a warning "Failed -Virus Detected" followed by an immediate SEVERE warning from Microsoft Antivirus. Windows will not allow you to download the file, without changing advanced settings to override the Antivirus software. My system is up to date, with the latest Windows version. 

## Expected Behavior

I was expecting it to download without a virus.

Something that will allow Windows users to download without getting a virus warning.

## Steps to Reproduce

1. Click Download Windows Version
2. Wait for download to finish
3. Click on download, warning will appear.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by benfry** [comment]
It's a false detection: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

Please submit it to Microsoft (see instructions at the link above) so that they can fix it.
