### ISSUE TITLE
doen't launch on linux mint vera 21.1

### ISSUE THREAD

**Issue by remibemol** [benfry/processing4#662]
Hello

I just installed processing on linuxmint vera 21.1

when I run ~/Downloads/processing-4.1.2$ ./processing
i get

Error: LinkageError occurred while loading main class processing.app.ui.Splash
	java.lang.UnsupportedClassVersionError: processing/app/ui/Splash has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

how to deal with that ?

**Comment by SableRaf** [comment]
Thank you for reaching out with your issue. It seems that you are encountering an error related to Java runtime versions. Processing 4.1.2 requires Java 17, however it appears that you are using Java 11 which [only supports class file versions up to 55](https://javaalmanac.io/bytecode/versions/).

We recommend updating to Java 17 to resolve this issue. If the issue persists, it might be a better idea to seek help in the Processing forum (https://discourse.processing.org/). Thank you!

**Comment by benfry** [comment]
Closing this one since it sounds like the download, which includes Java 17, was somehow modified since that JVM wasn't being used.
