### ISSUE TITLE
Multiple users cannot open processing due to folder in /tmp/

### ISSUE THREAD

**Issue by jonalf** [benfry/processing4#666]
## Description
I maintain a classroom of ubuntu 20.0.4 computers, multiple users, with unique accounts, per day need to be able to launch and run processing. Students started to complain that they were getting a strange error when trying to launch processing. Processing is installed locally in
`/usr/local/bin/`

After investigating, I discovered that processing creates a directory in:
`/tmp/processing`
This directory is owned by the user that opened processing, but remains after processing is closed and the user has logged out. I believe that the existence of this directory is keeping other users from launching processing. Rebooting the computer (or just removing the directory in `/tmp` does allow a new user to start processing.

**Comment by benfry** [comment]
This should be fixed since 4.0.2: https://github.com/processing/processing4/issues/549

Are you using the latest release?

**Comment by jonalf** [comment]
I'm using processing 4.1.2 revision 1290.

I was wondering why we hadn't had this problem earlier in the year. After your comment about the version I checked back on it and discovered that a colleague had upgraded to the newer version last week. The upgrade coincides with the problem occurring.

**Comment by benfry** [comment]
Got it; will check into it—I suspect an extra subfolder may be created that's causing the issue.

**Comment by benfry** [comment]
Can you give it a try with this: https://download.processing.org/processing-230214-linux-x64.tgz

First delete the `/tmp/processing` folder, but when you run this version, it should hopefully set permissions so that others can share the directory.

**Comment by jonalf** [comment]
First, thanks for the prompt work on this.

The new processing binary gives the folder in tmp 775 permissions. So users in the same group can run processing, but not any user. See below:

```
$ ls -l /tmp | grep proce
drwxrwxr-x  3 jadw         jadw      4096 Feb 16 11:39 processing
```

**Comment by benfry** [comment]
Nuts; it's supposed to be doing 777 (via https://github.com/processing/processing4/commit/b01487453d445f053e3a1e4af4bdbb7fab679401 and https://github.com/processing/processing4/commit/9fed8a291b88a5f414053aaf4aab5e423fbaf166) but perhaps failing silently. 

I'll have to do more testing…

**Comment by benfry** [comment]
Ok, here's another to try: https://download.processing.org/processing-230216-linux-x64.tgz

If that doesn't work, is there anything set with the students' user accounts (i.e. `umask` related) that prevents them from setting a folder to be readable by all? On a Linux testing machine here, even the previous version was properly showing `rwxrwxrwx` for the folder.

**Comment by jonalf** [comment]
It works! After looking back at the problem it did seem as if it were `umask` related. In any event, permissions look good now.

```
$ ls -l /tmp/ | grep proce
drwxrwxrwx  3 jadw           jadw      4096 Feb 16 20:48 processing
```

**Comment by benfry** [comment]
Awesome, thanks for letting me know. I'll try to get this posted as 4.2 (which also includes a bunch of updates for Python Mode) in the next day or two.
