### ISSUE TITLE
Exported project to Windows cannot find Java

### ISSUE THREAD

**Issue by alekratz** [benfry/processing4#667]
## Description
I am exporting a project on Linux, and creating an .exe for Windows. When I try to run the .exe on a Windows 10 machine, I am given this error: "This application requires a Java Runtime Environment 17". However, I have already installed JRE 17, the JAVA_HOME environment variable is set correctly, and the PATH environment variable is set up to point to the correct version of Java.

## Expected Behavior
Application starts up and runs as expected.

## Current Behavior
Error message described above. When I run `java -version` it shows the expected version.

## Steps to Reproduce
1. Export to Windows via Linux
2. Install JRE 17
3. Set JAVA_HOME and PATH environment variables appropriately
4. Try to run application.

## Your Environment
* Processing version: 4, rev 1291
* Operating System and OS version: Arch Linux
* Other information: Exporting to Windows target, running on Windows 10

## Possible Causes / Solutions
I can skim the source code to see what may be going on, I haven't taken the time to do that.

Additionally, I'm using a couple of weird built-in Java libraries, like the clipboard and gzip. I don't expect that using those would be causing this issue however.

Java 8 is also installed on this machine, but I don't think any environment variables are pointing to it.

**Comment by benfry** [comment]
It's probably the Java 8 on your machine inserting itself somehow… Try copying the JRE to a folder called `java` adjacent to that `.exe`. (So that `java/bin` contains `java.exe` and that sort of thing.) Does that work?

**Comment by benfry** [comment]
Found the problem here while looking into something else. Fixed for 4.2, when released. Thanks for the report…

**Comment by alekratz** [comment]
Hey, thanks so much for checking this out (and fixing it, nice). I was going to give your suggestion a try when I had Windows access again. Keep up the awesome work.
