### ISSUE TITLE
Downloading the 4.1.3 for Windows zip file leads to a Trojan Warning

### ISSUE THREAD

**Issue by creadicted** [benfry/processing4#668]
## Description
Title says it all. I tried to download the app and got a warning from windows that it quarantined the file immediately.  

TrojanDownloader:Java/OpenConnection.PM

Discussed here with an older version: https://github.com/processing/processing/issues/6202

**Comment by benfry** [comment]
Sorry for the trouble; but not a trojan. 

More here: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

It's been submitted to Microsoft, all we can do is wait until it clears.
