### ISSUE TITLE
Very weird stuff going on with colors and transparency with the P2D renderer

### ISSUE THREAD

**Issue by PianoMastR64** [benfry/processing4#669]
``` java
PGraphics pg;

void setup() {
  size(800, 800, P2D);

  pg = createGraphics(width, height, P2D);

  pg.beginDraw();

  pg.noStroke();

  pg.clear();

  pg.fill(255, 127);
  pg.rect(0, 0, 195, height);
  printColor(pg.get(10, 10));

  pg.endDraw();

  background(0);
  image(pg, 0, 0);
}

void draw() {
  pg.beginDraw();
  //pg.clear();

  pg.fill(255, 127);
  switch(frameCount) {
  case 1 :
    pg.rect(200, 0, 195, height);
    printColor(pg.get(210, 10));
    break;
  case 2 :
    pg.rect(400, 0, 195, height);
    printColor(pg.get(410, 10));
    break;
  case 3 :
    pg.rect(600, 0, 195, height);
    printColor(pg.get(610, 10));
    break;
  }

  pg.endDraw();

  background(0);
  image(pg, 0, 0);
}

void printColor(int c) {
  println("color RBGA: (" +
    red(c) + ", " +
    green(c) + ", " +
    blue(c) + ", " +
    alpha(c) + ")");
}
```

This is my attempt to figure out why my images are darker than they're supposed to be sometimes, and I admit that I'm completely lost. It's seriously messing up a project I'm trying to work on. Colors below are in RGBA format.

The 4 rectangles are supposed to be `255, 255, 255, 127` as I've set in the `fill()` methods. In the above code, the colors of the four rectangles are apparently `127, 127, 127, 127`. If you comment out `pg.clear();` in `setup()`, then the color of the fist rectangle is `229, 229, 229, 127` for some reason. Uncommenting `pg.clear();` in `draw()` doesn't seem to make a difference (besides making it so you can't see anything which is expected). When I analyze the colors using an image editor, then they're `63, 63, 63` when they should be `127, 127, 127` because it's drawn onto the primary `PGraphics` set to ` 0, 0, 0, 255`. In any case, I can't get the first rectangle to even show up on screen.

Furthermore, If I change just the primary to the default renderer, it crashes. (I think this is supposed to be unsurprising, but makes the next result confusing.) If I instead change just `pg` to the default renderer *or* I change both to the default renderer, then all the colors in all situations described above are correct. The first rectangle even shows up. Unfortunately I kind of need `P2D` because it's way faster, and I'm doing something that requires a lot of computation.

I can't make sense of any of this. All I want to do is draw a translucent shape onto a transparent `PGraphics` then draw that onto the primary without having all of these strange color anomalies.

**Comment by benfry** [comment]
Please use https://discourse.processing.org/ for coding questions and discussion.

**Comment by PianoMastR64** [comment]
> Please use https://discourse.processing.org/ for coding questions and discussion.

I put this here because I'm fairly confident this is a bug that needs to be fixed. Am I just doing something wrong then? I'll post there and come back if it's really a bug

**Comment by knupel** [comment]
@PianoMastR64 it's true, ask your question on the https://discourse.processing.org/ because your code work like expected.

```
println(frameCount);
```
when you check the `println`, you can see your `switch(frameCount)` is just for the first moment of your program.
So try something like that with adding modulo in your switch

```
switch(frameCount%4) {
  case 1 :
    pg.fill(255, 0, 0);
    pg.rect(200, 0, 195, height);
    break;
  // other cases
}
```

**Comment by PianoMastR64** [comment]
@knupel That was on purpose. `setup()` is frame 0, while `draw()` is frames 1, 2, and 3. The purpose is just to show what's happening on each of the first frames because I've noticed sometimes that makes a difference. I don't care about the rest of the frames because they very likely will be the same as frame 3. In this particular case, the only special one seems to be 0

**Comment by knupel** [comment]
I think there is no bug, just the behavior is behavior is different with classic rendering and with P2D rendering,
when it's in P2D the alpha is apply to the color too, and not in classic mode, see the log.

```java
PGraphics pg;

void setup() {
  // size(400,400,P2D);
  size(400,400);
  frameRate(1);
  background(255, 127);
  int c = get(width/2, height/2);
  
  // println("P2D background color", red(c), green(c), blue(c), alpha(c));
  // pg = createGraphics(width, height, P2D);
  
  println("CLASSIC background color", red(c), green(c), blue(c), alpha(c));
  pg = createGraphics(width, height);
}

void draw() {
  pg.beginDraw();
  pg.fill(255, 0,0, 127);
  pg.rect(0,0,width, height);
  pg.endDraw();
  int c = pg.get(width/2, height/2);
  image(pg, 0, 0);
  // println("P2D pg.rect color", red(c), green(c), blue(c), alpha(c));
  println("CLASSIC pg.rect color", red(c), green(c), blue(c), alpha(c));
}
```

consol log
```
P2D background color 255.0 255.0 255.0 127.0
P2D pg.rect color 0.0 0.0 0.0 0.0
P2D pg.rect color 127.0 0.0 0.0 127.0
P2D pg.rect color 191.0 0.0 0.0 254.0
P2D pg.rect color 223.0 0.0 0.0 255.0
P2D pg.rect color 239.0 0.0 0.0 255.0
P2D pg.rect color 247.0 0.0 0.0 255.0
P2D pg.rect color 251.0 0.0 0.0 255.0
P2D pg.rect color 253.0 0.0 0.0 255.0
P2D pg.rect color 254.0 0.0 0.0 255.0
P2D pg.rect color 254.0 0.0 0.0 255.0

CLASSIC background color 255.0 255.0 255.0 255.0
CLASSIC pg.rect color 255.0 0.0 0.0 127.0
CLASSIC pg.rect color 255.0 0.0 0.0 191.0
CLASSIC pg.rect color 255.0 0.0 0.0 223.0
CLASSIC pg.rect color 255.0 0.0 0.0 239.0
CLASSIC pg.rect color 255.0 0.0 0.0 247.0
CLASSIC pg.rect color 255.0 0.0 0.0 251.0
CLASSIC pg.rect color 255.0 0.0 0.0 253.0
CLASSIC pg.rect color 255.0 0.0 0.0 254.0
CLASSIC pg.rect color 255.0 0.0 0.0 254.0
```

**Comment by benfry** [comment]
Again, please use https://discourse.processing.org/ for discussing specific coding problems. If it's actually identified to be a problem through discussion, then I want to hear about it. 

This will help save my time for things that are broken and actually need to be fixed.
