### ISSUE TITLE
Register `pde://` browser protocol for .pdez and .pdex files on Linux

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#674]
Starting with Processing 4.2, you can use `pde://` URLs to open `.pdex` and `.pdez` files from the internet and the local machine (see #559). These are implemented on macOS and Windows, but I ran out of time to implement and test them properly on Linux.

To implement, the necessary incantations should be added to the Linux install script. [This](https://unix.stackexchange.com/a/497147) looks like a reasonably up to date resource on how to make it happen. Or [this](https://web.archive.org/web/20210601082308/https://support.shotgunsoftware.com/hc/en-us/articles/219031308-How-to-launch-external-applications-using-custom-protocols-rock-instead-of-http-?mobile_site=true) older document was used as the basis for the Windows and macOS versions, and includes a Linux implementation as well. 

Please help!

**Comment by lala-lala-lori** [comment]
I have kinda got familiar around the repo, I want to work on this. Could you please assign this to me.

**Comment by zriqo** [comment]
Could you please assign this issue to me. I have already finished half of the work. I'll raise a PR soon.
