### ISSUE TITLE
Feature: Language Server Protocol, Definition support

### ISSUE THREAD

**Issue by Efratror** [benfry/processing4#676]
## Description
Since there now is [LSP](https://github.com/processing/processing4/pull/564) support for processing, it would be nice if the server would be able to "find declarations"

## Expected Behavior
Finding declarations is supported in the PDE, so it should also be available for the LS

## Current Behavior
Finding declarations isn't supported at the moment

## Your Environment
* Processing version: 4.2
* Operating System and OS version: Windows 10

## Possible Causes / Solutions
- Add a declarationFinder class to the LSP folder
- Use it to find a declaration using the AST from the preprocessor (Use "InspectMode" as an example)
- Send (found) the declaration back to a LS-client

I'm willing to implement this, so a PR is in the making

**Comment by benfry** [comment]
A PR would be great, thank you!

**Comment by benfry** [comment]
Now incorporated for the release that comes after 4.2 (probably 4.2.1).
