### ISSUE TITLE
Developing a tool inside wsl2 running linux using javac to compile

### ISSUE THREAD

**Issue by dantearaujo1** [benfry/processing4#679]
## Description
I'm currently trying to implement a simple tool that prints to console  of the PDE "Hello", i don't have eclipse on my machine so, i had to use the javac to compile my code. It compiles and it worked, but when i move my project folder to my sketchbook/tools folder it doesn't show anything inside the PDE tools menu

## Expected Behavior
Place my project folder like the documentation says inside sketchbook/tools/ and my tool appears in the tools menu

## Current Behavior
Doesn't show nothing

## Steps to Reproduce
1. Create a folder ProjectName with a tool.properties file and a tool folder inside (for the jar file)
2. Create a src folder inside the ProjectName folder with your java file
3. Place pde.jar and core.jar inside a folder called libs inside ProjectName folder
4. Write our code implementing Tool class and overriding his methods and importing processing.app.tools.* ; processing.app.Base; processing.app.ui
5.  Compile your code from the ProjectName directory using javac --classpath ".:$CLASSPATH:./libs/pde.jar:./libs/core.jar ProjectName.java
6. Now use the command from the ProjectName directory in your command line: jar -cfe tool/ProjectName.jar src/ProjectName.class
7. Move your folder to your processing/sketchbook/tools/ folder

## Your Environment
* Processing version: 4.2
* Operating System and OS version: Windows 22H2
* Other information: WSL2 Ubuntu 20.04.05 LTS

## Possible Causes / Solutions
Not using eclipse to build my tool

**Comment by benfry** [comment]
This is a better discussion for the forum: https://discourse.processing.org/
