### ISSUE TITLE
Feature: Language Server Protocol, Reference Support

### ISSUE THREAD

**Issue by Efratror** [benfry/processing4#684]
## Description
Add a feature for supporting references to the LS

## Expected Behavior
References are supported by the PDE (find usage). So it would be nice to have it for the server as well

## Current Behavior
Only finding declarations is supported at the moment

## Your Environment
* Processing version: 4.2
* Operating System and OS version: Windows 10
* Other information: Source includes PR #678

## Possible Causes / Solutions
* Add static function "searchReference" to the "pdeSymbolFinder" class
* Use it to find all references using the AST,
* Send (found) references back to the LS-client

I'm willing to implement this, please assignee me if you're ok with this idea.

**Comment by benfry** [comment]
Yes please, thanks!

**Comment by Efratror** [comment]
@benfry could you please explain what I missed in my previous pr regarding the style sheet? I had read it before placing the pr but clearly I misunderstood some parts of it.

Thanks in advance

**Comment by benfry** [comment]
The main one was things like 

```java
if(optionalJavaOffset.isEmpty()){
``` 

which should read

```java
if (optionalJavaOffset.isEmpty()) {
```

but I'd have to check if there were others. Perhaps it wasn't much?

**Comment by Efratror** [comment]
aha thanks, i will try doing better for this PR😊
