### ISSUE TITLE
Stroke overlapping issue on co-planar shapes in P3D

### ISSUE THREAD

**Issue by vincentsijben** [benfry/processing4#697]
## Description
The stroke of the red square should be overlapped with the fill of the blue square.

## Steps to Reproduce
Changing P3D to P2D gives the expected result.

<table>
<tr>
<td> Code </td> <td> P2D </td><td>P3D</td>
</tr>
<tr>
<td>

```java
void setup() {
  size(170, 170, P3D);
}

void draw() {
  background(220);
  
  stroke(0);
  fill(255,0,0);
  rect(20, 20, 100, 100);
  
  fill(0,0,255);
  rect(50, 50, 100, 100);
}
```

</td>
<td>
<img width="162" alt="image" src="https://user-images.githubusercontent.com/36117924/230743244-a7998047-e0ab-4f97-9792-8dd6b7c09aff.png">

</td>
<td>
<img width="159" alt="image" src="https://user-images.githubusercontent.com/36117924/230743119-709ca819-3d35-4d9e-b307-57cd675863ea.png">
</td>
</tr>

</table>

## Your Environment
* Processing version: 4.2
* Operating System and OS version: MacOS Ventura 13.3.1 on Apple M1 Pro

## Possible Causes / Solutions
It's the same issue as reported [here for p5js in WebGL mode](https://github.com/processing/p5.js/issues/2938).

**Comment by dzaima** [comment]
duplicate: https://github.com/processing/processing4/issues/27#issuecomment-558570106

**Comment by vincentsijben** [comment]
Thanks. Yes it was closed in 2019, but 4 years later, we would like to have P3D performance boosts and be able to have consistency with overlap. Still not possible?

**Comment by benfry** [comment]
`P2D` is the same engine (same performance). The primary reason it exists is to resolve this specific issue (handling of coplanar drawing).
