### ISSUE TITLE
[Feature request] Provide functions that will setup center/direction of coordinate system and persist the settings

### ISSUE THREAD

**Issue by JocaPC** [benfry/processing4#706]
## Description

Processing uses the upper left corner as a starting point of the coordinate system. There are scenarios where we need to translate coordinate system to other starting point:
1. Coordinate system starting in center (requires translate(width/2,height/2) and scale(1,-1)) to represent four quadrants of [Cartesian coordinate system](https://en.wikipedia.org/wiki/Cartesian_coordinate_system).
2. Coordinate system starting in bottom left corner (requires translate(0,height) and scale(1,-1)) to represent first quadrant of [Cartesian coordinate system](https://en.wikipedia.org/wiki/Cartesian_coordinate_system). 

Other graphycal engines/tools support right-handed or left-handed coordinate systems with y-up and z-up to support different scenarios - see: https://www.techarthub.com/a-guide-to-unitys-coordinate-system-with-practical-examples/#:~:text=World%20Coordinate%20System%20Quick%20Guide.  
The feature request is to acknowlege that there are valid scenarios for customized coordinate systems and enable easier setup.

Although it is easy to change the matrix, we need to do it in every function and change it sometime
- Functions like `draw()` always reset matrix,
- `mouseX`, `mouseY` and other system coordinates are always calculated from the upper left corner.
- `text()` and `image()` are shown upside-down when the scale is changed to inverse the y axis.
- `scale(1,-1)` also impacts the direction of angle calculation.
 
The feature request is to provide a set of functions that can be used in `setup()` and set the right/left handed coordinate system or define y-up or z-up direction.

## Expected Behavior

I'm proposing two functions that might solve this:
```
setup() {
    moveCenter(0,height);  // equivalent of **persistent** translate(0,height);
    yAxisDirection("up");  // equivalent of **persistent** scale(1,-1); that will not turn upside-down images and text
}
```
The expected behavior would be to use the setting in all other functions without a need to re-apply the matrix.

```
draw() {
   // In this function we should not need to repeat translate() and scale() and to revert them whenever we draw text or image
   // mouseX and mouseY should be calculated from the coordinate center defined in setup()
   // text() and image() should honour reversed coordinate system
}
```

## Current Behavior

Currently, we need to repeat translate&scale in every draw() call and re-calculate mouseY when needed:
```
def draw():
  translate(0,height)
  scale(1,-1)
  background(255)
  x = mouseX
  y = height-mouseY  # y coordinate must be recalculated because it is calculated from the upper right corner.
  line(0,0, x,y)
```
Once we revert y-axis to be in the up direction, we need to translate and scale the coordinates locally. This means that we need to create custom functions to show images just ot re-adjust the coordinates:
```
def showImage(x,y, img):
  pushMatrix()
  translate(x,y)
  scale(1,-1)   # without reverting scale(1,-1) image is upside-down (at least in Processing Python mode)
  image(img, 0,0)
  popMatrix()
```

Also reverting y-axis redefines the definition of the begining corner for images.

If the coordinate system is changed, we cannot directly use `text()`, and we need to wrap it with a custom function that uses modified coordinates to position text and then re-scale the y axis to show the text properly:

```
def showText(x,y, tekst):
  pushMatrix()
  translate(x,y)
  scale(1,-1)
  text(tekst, 0, 0)
  popMatrix()
```

Generally, changing the coordinate system position and direction causes messy&error-prone behavior. However, in some scenarios we would need different coordinate system. Example are games where it is natural that the gravity is pushing the objects **down** to the x axis or math/measyremnt in physics where we are drawing graphs or charts where naturally y axis is oriented up.

## Steps to Reproduce

1.
4.
5.

## Your Environment

 

* Processing version: All
* Operating System and OS version: All
* Other information: This is request to customize existing standard behavior.

## Possible Causes / Solutions

The solution is wrapping subset of function with push/pop matrix, and scale/translate, which is messy and error-prone.

**Comment by benfry** [comment]
That's only the default transformation; you have full control over all of that using the camera and projection functions in the API: https://processing.org/reference/#lights-camera
