### ISSUE TITLE
P4 (vs P3): GLException: Unable to determine GraphicsConfiguration:

### ISSUE THREAD

**Issue by markhen57** [benfry/processing4#708]
I have a fairly large Processing/Javamail program that I have been developing on WIn10 and Win11 machines. It uses JCEF (Chromium) for email rendering. Under P3 everything works as expected (currently I'm using 3.5.4).

When I try to run the program under P4 (I've tried several versions up to 4.2, same result) and attempt to open a JCEF browser window I get this error:

GLException: Unable to determine GraphicsConfiguration: WindowsWGLGraphicsConfiguration[DefaultGraphicsScreen[WindowsGraphicsDevice[type .windows, connection decon, unitID 0, handle 0x0, owner false, NullToolkitLock[obj 0x50cedc43]], idx 0], pfdID 8, ARB-Choosen true,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[wgl vid 8 arb: rgba 10/10/10/2, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]

I realize there are many things that COULD cause this, my question is for clues about what is different between P3 and P4 that could cause this?

TIA

Mark

**Comment by benfry** [comment]
Hard to say—this is an error coming from JOGL, which is a new version int 4.x, and you're in pretty messy territory with dueling graphics contexts that want to use GL (Chromium and Processing). I've not got much unless something comes to mind for @codeanticode.

**Comment by codeanticode** [comment]
@markhen57 I agree with @benfry, sounds like this could be due to some conflict between JCEF and JOGL rendering contexts. I don't have any experience with this, seems like people have run into similar problems:

https://forum.jogamp.org/GLCanvas-paint-get-stuck-after-some-idle-time-td4041584.html#a4041594

Maybe you can get some responses by posting on the JOGL forum.
