### ISSUE TITLE
How to upload video in processing

### ISSUE THREAD

**Issue by Barannasirii** [benfry/processing4#712]
Does anyone know how to upload a video in processing language?

**Comment by knupel** [comment]
Hello, for this is better to post your question on the forum https://discourse.processing.org/

**Comment by EinsMalte** [comment]
@Barannasirii What exactly do you by "uploading" a video?

You can play a video using the processing video library, which you can download using processing:
`Sketch > Import library > Manage libraries > (type "Video" in the filter field) > Video Library for Processing 3/4 > Install`
Take a look at the `Loop` example. To open it press `CRTL + SHIFT + O` and then navigate to `Libraries > Video Library for Processing 3/4 > Movie > Loop` and then double click to open

**Comment by SableRaf** [comment]
@Barannasirii, due to a lack of activity and no further clarification on your request, we will be closing this issue. If you wish to revisit this issue or have other questions regarding processing video in the future, please don't hesitate to open a new one. Thank you for your understanding.
