### ISSUE TITLE
No PDF Output (connected to stroke opacity, colorMode)

### ISSUE THREAD

**Issue by andrewcooke** [benfry/processing4#725]
## Expected Behavior
I expect the PDF file to match the displayed output when running the included code in the IDE.

## Current Behavior
Instead, the PDF is blank.  I do get the expected output if I change the stroke() to omit alpha.

## Steps to Reproduce

```
import processing.pdf.PGraphicsPDF;

void setup() {  
  noLoop();
  colorMode(HSB, 1, 1, 1, 1);
}

void draw() {
  beginRecord(PDF, "triangles.pdf");
  // this works!
  // stroke(#000000);
  // this does not
  stroke(#000000, 0.5);
  line(0, 0, 100, 100);
  endRecord();
}

```

1. Run the code above in the IDE.
2. The screen displays a line, but the PDF is blank.
3. Swap the comments on the stroke.
4. The PDF reflects the screen output.

## Your Environment

 

* Processing version: 4,2 (bottom right of help/about popup)
* Operating System and OS version: OpenSuse 15.4
* Other information: Gnome, installed from processing-4.2-linux-x64.tgz

**Comment by andrewcooke** [comment]
i think i have an explanation.  the PDF is ignoring the colorMode that is setting opacity from 0 to 1.  instead, it remains working with 0 to 100 (the PDF is correct with an opacity of 100).  however, the on-screen display (and png output, which i removed to simplify the demo) reflect the colorMode setting (and so an opacity of 0.5 or 1 is visible there).

**Comment by andrewcooke** [comment]
a workaround is to specify opacity in the color rather than the stroke.  in fact, this seems like t was a confused moment on my part (i normally use opacity in the color) which is why i only noticed it in one sketch.

**Comment by glvjr** [comment]
Use colorMode() between beginRecord() and EndRecord().

```
import processing.pdf.PGraphicsPDF;

void setup() 
  {
  size(330, 330);  
  background(255);
  //colorMode(HSB, 1, 1, 1, 1);
  noLoop();
  }

void draw() {
  beginRecord(PDF, "triangles.pdf");
  colorMode(HSB, 1, 1, 1, 1);        // Use colorMode here  

  strokeWeight(10);
  for(int i = 0; i<11; i++)
    {
    stroke(#000000, i*0.1);
    println(i*0.1, hex(g.strokeColor));
    line(i*30+15, 0, i*30+15, height);
    }
  endRecord();
  }
```

**Comment by andrewcooke** [comment]
ah, thanks.  makes sense.  should i close this?

**Comment by glvjr** [comment]
If it is a working solution it should be closed.

It may be worthy as an additional note here to emphasize this:
[https://processing.org/reference/libraries/pdf/index.html](url)

In this section:
_Additional notes for the PDF renderer:_

Also applies to things like background() which came up in another recent discussion of forum.

:)
