### ISSUE TITLE
Fail to start due to debugger

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#73]
I'm trying to see what's up but it looks like `master` is broken (tested on Mac OS X). NullPointerException at `JavaEditor.java:1389`.

**Comment by sampottinger** [comment]
Looks like constructor in `Editor` called from from `JavaEditor` is calling an overridden method back in `JavaEditor` that expects `debugger` to have been initialized which is not possible since the parent constructor has not returned.

**Comment by sampottinger** [comment]
<img width="593" alt="Screen Shot 2020-03-08 at 10 14 32 AM" src="https://user-images.githubusercontent.com/110391/76167670-a64d7600-6125-11ea-8af9-47c9345e917d.png">

**Comment by sampottinger** [comment]
Hey there! There's a few PRs outstanding (with inter-dependencies) and the build on master has been broken on Mac for some time. So, I have an integration branch over at https://github.com/sampottinger/processing4 master. That branch includes this bug's PR. This allows one to use Processing 4 again on a Mac along with all of the recent bug fixes. For your convenience, I have made builds available at https://www.datadrivenempathy.com/processing.

**Comment by benfry** [comment]
Ok, just checked in a solution that delays the init of the menu and toolbar buttons. Still an issue with the toolbar button not highlighting that I need to sort out, but I think I saw that filed as a separate issue.
