### ISSUE TITLE
The font-renderer messes up Inter-Font

### ISSUE THREAD

**Issue by EinsMalte** [benfry/processing4#731]
## Description

When using the Inter-Font by Google Fonts at extrabold width the text becomes messy.

Please fix the alignment issues. Also please add a function, that centers the text on the y axis based off of the actual height and not the max height and consider adding a textWeight() function to change text weight without loading 10 different fonts.
```
thin = createFont("fonts/Inter-Thin.ttf", 128);
semi = createFont("fonts/Inter-SemiBold.ttf", 128);
regular = createFont("fonts/Inter-Regular.ttf", 128);
medium = createFont("fonts/Inter-Medium.ttf", 128);
light = createFont("fonts/Inter-Light.ttf", 128);
extralight = createFont("fonts/Inter-ExtraLight.ttf", 128);
extrabold = createFont("fonts/Inter-ExtraBold.ttf", 128);
bold = createFont("fonts/Inter-Bold.ttf", 128);
black = createFont("fonts/Inter-Black.ttf", 128);
```

## Expected Behavior

Expected:
![image](https://github.com/processing/processing4/assets/49271270/1b4a9e06-00cf-4347-ac43-3fe16f8618b9)
This image was grabbed from figma. As you can see the text is perfectly centered.

## Current Behavior

![image](https://github.com/processing/processing4/assets/49271270/361e0975-f3ad-42dd-a1bf-814f4ed83553)
This image is a screenshot of processing. The text shows multiple issues (white lines, inconsistent char height and messed up y alignment)

## Steps to Reproduce

1. Download the inter-font
2. Use it at extrabold width
3. Use textalign CENTER TOP and display a text at any size

## Your Environment

 

* Processing version: 4.0b8
* Operating System and OS version: Windows 10
* Other information:

**Comment by benfry** [comment]
You'll get some weirdness when creating a font at 128 pixels but then scaling it down to about 12 point. Use `createFont()` within 2-3x of the font size you need. 

Also please use the latest; 4.0b8 is very, very old.
