### ISSUE TITLE
 IDE Source Code Colours not fully working.

### ISSUE THREAD

**Issue by RichardDL99** [benfry/processing4#736]
## Description

I've edited theme.txt aiming a getting a dark scheme clear and easy to work with.  I've tried all the language syntax items in theme.txt.  Some of them seem to do nothing.  Some parts of the language (Java) can't be user-coloured.

This is the relevant part of theme.txt with my comments on what each item applies to.

```
# Two sorts of comments
editor.token.comment1.style = #00FF00,plain
editor.token.comment2.style = #00FF00,plain
#
# Nothing/Don't know
editor.token.function1.style   = #B020E0,plain
#
# methods, e.g. format of String.format
editor.token.function2.style   = #0080F0,plain
#
# for and if (but not else) catch
editor.token.function3.style   = #F09000,plain
#
# Predifined func names e.g. setup, draw, mousePressed
editor.token.function4.style   = #FFFF00,bold
#
# Nothing/Don't know
editor.token.invalid.style     = #666666,bold
#
# void, new, public, import
editor.token.keyword1.style    = #B00080,plain
#
# Nothing/Don't know
editor.token.keyword2.style    = #FF8000,bold
#
# else, try
editor.token.keyword3.style    = #F09000,plain
#
# width, height
editor.token.keyword4.style    = #80B000,plain
#
# Data types: int, long, String, boolean, ArrayList
editor.token.keyword5.style    = #E06000,plain
#
# this
editor.token.keyword6.style    = #9080E0,plain
#
# Nothing/Don't know
editor.token.label.style       = #666666,bold
#
# Character and string literals e.g. 'A' "Hello"
editor.token.literal1.style    = #00B0B0,plain
#
# Constants: LEFT, RIGHT, CENTER,
editor.token.literal2.style    = #404080,plain
#
# Nothing/Don't know
editor.token.operator.style    = #FFFF00,bold
#

```
Just to prove the point I tried setting all those items to green.  Then all the items that can't be user-coloured will be visible as white.

![image](https://github.com/processing/processing4/assets/28405897/1b5b149c-9520-4b39-8137-e4c6d010c812)

Operators, variables, brackets, values all the same colour.  By contrast the Arduino IDE is more flexible, the same code can look like this:

![image](https://github.com/processing/processing4/assets/28405897/c99ec3d4-7736-4df9-b006-03049c7ce7b1)

## Expected Behavior
I want to be able to colour each part of the language differently.

## Current Behavior
Can't colour the operators, variables, values, brackets.

## Steps to Reproduce
Just show me how to colour the operators red.

## Your Environment
Processing 4.2
Windows 7 (Same on 10)

## Possible Causes / Solutions
Use the syntax colouring module from Arduino IDE.

**Comment by benfry** [comment]
Yeah, the editor component isn't great, and fixing this requires a larger rewrite. More about how that would happen is here: https://github.com/processing/processing4/blob/main/CONTRIBUTING.md#editor
