### ISSUE TITLE
In ten years how have you guys not found the time and precedence to integrate a debugger

### ISSUE THREAD

**Issue by iiian** [benfry/processing4#767]
In ten years how have you guys not found the time and precedence to integrate a debugger

**Comment by sterretjeToo** [comment]
There is a debugger in (at least) 4.2 and 4.3.

Does it not suite your needs? If so, I suggest that you make suggestions how it can be improved ;)

**Comment by benfry** [comment]
You can find the debugger in the “Debug” menu.

**Comment by iiian** [comment]
Nice. Only for Java.

**Comment by benfry** [comment]
This is the repository for the Java version of Processing. If you have a problem with another project, you'll need to take it up there. 

There's no need for the sarcastic “Nice” or the nasty “In ten years…” in the subject title. This work is done by volunteers, and the attitude has no place here.
