### ISSUE TITLE
cut/copy/paste while saving a sketch on OS X goes to the editor, not the save dialog

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#77]
Not that important, but this old bug is back:

https://github.com/processing/processing/issues/1035

OSX 10.12.6
Processing 4.0a1

If you save a sketch, and paste during that proces for either the filename of the sketch or the filename of a new folder then it paste the content you copied before in the sketch itself.

**Comment by sampottinger** [comment]
Thanks @clankill3r! Apologies for the delay. Can confirm this... Will look into it.

**Comment by sampottinger** [comment]
Ooph. It happens with `FileDialog` but not `JFileChooser`. :(

**Comment by sampottinger** [comment]
Bad news... https://stackoverflow.com/questions/53309692/awt-filedialog-filename-copy-paste-keystrokes/56793268. I'm wondering if this cropped up with OpenJDK.

**Comment by sampottinger** [comment]
Just confirmed that it doesn't have anything to do with our copy / paste actions within processing itself. Ugh...

**Comment by sampottinger** [comment]
Personally, I'm not sure what the preferred action is here. Right click in the box works. However, the precedent of the previous decision made in https://github.com/processing/processing/issues/1035 suggests mac should use JFileChooser. :(

> Using JFileChooser fixes the problem (but is ugly and not very Mac-like). But maybe we'll have to use it

**Comment by clankill3r** [comment]
JFileChooser is far worse then the paste bug.

I would either leave the bug, or else maybe if it's possible:

- if a paste is done but a save dialog is open, ignore the paste

Op zo 19 apr. 2020 om 01:51 schreef A Samuel Pottinger <
notifications@github.com>:

**Comment by sampottinger** [comment]
Hey @clankill3r! I was able to reach a different solution in #88 through [vaqua](https://violetlib.org/vaqua/overview.html). It is in sampottinger/processing4 and https://www.datadrivenempathy.com/processing.

**Comment by benfry** [comment]
FYI for alpha 5… going back to the native file chooser as the default because `JFileChooser` goes from bad to total abomination on Big Sur. So the cure seems worse than the disease here, and the VAqua solution also wound up being a problematic alternative in different ways.

Actual changes in this commit: https://github.com/processing/processing4/commit/5e0776161e4ca1ad5311907ea08f69aa40942f50
