### ISSUE TITLE
Theme Location Unknown

### ISSUE THREAD

**Issue by RamonAbudAlcala** [benfry/processing4#774]
## Description
I am unable to find the file theme.txt responsible for the current theme.

## Expected Behavior
I'd like the functionality of  tools -> themes -> 
"save the theme to sketchbook for editing" || "Reload theme.txt update the current theme"
to work

## Current Behavior
Cannot find theme.txt and cannot create custom themes using the aforementioned functionality.

## Steps to Reproduce
I go to tools -> themes -> select a theme e.g. Alloys/morito.txt -> click "save the theme to sketchbook for editing"
I don't see the file theme.txt anywhere. 
At first I assume "sketchbook" is the location of my .pde file, but theme.txt is not there.
Where is "sketchbook"?

I can see theme.txt in /lib/themes but this was already there.
Changes to /libt/themes/theme.txt file do not affect the current theme.

The consequence is that I am unable to create custom themes. But I'd like the functionality of 
"save the theme to sketchbook for editing" + "Reload theme.txt update the current theme" to work
Default themes work as expected, just by clicking on them.

## Your Environment
I am running Processing 4.3 portable on a Windows 10 machine.

## Other tests
I have also tried to create a theme under /lib/Personal/mytheme.txt and edited the line 
```
theme=Alloys/morito.txt
```
to
```
theme=Personal/mytheme.txt
```
in the preferences.txt file with processing not running. This changes the theme when I open processing, but I am unable to use the functionality of editing the file and click on 
tools -> themes -> click "Reload theme.txt update the current theme"

Furthermore, If from this state I select Alloys/morito then preferences.txt changes back to `theme=Alloys/morito.txt`
and then if I click "save the theme to sketchbook for editing" preferences.txt stays as `theme=Alloys/morito.txt`. Is this meant to happen?

I cannot find anything online about the location of the file theme.txt, it seems that this is taken for granted everywhere.

**Comment by benfry** [comment]
You can see the location of the sketchbook folder at the bottom of the Preferences window:
https://processing.org/environment/#sketches-and-sketchbook

**Comment by RamonAbudAlcala** [comment]
Thanks!

Just for reference, the folder is specified at the top of the Preferences window, rather than the bottom :)
