### ISSUE TITLE
Runner produces misleading '<library> does not run on this architecture' error messages

### ISSUE THREAD

**Issue by kevinstadler** [benfry/processing4#780]
## Description
Processing 4.3 produces bogus/misleading console error messages of the format `library.getName() + " does not run on this architecture: " + variant` when running sketches that load a library which bundles native libraries for at least one architecture, but none for the architecture/OS on which the sketch is run. The error message is triggered by the following heuristic:
https://github.com/processing/processing4/blob/f1da3739ba504b5b8010e91790e065819a7be3ad/app/src/processing/app/Library.java#L511-L517
which is a bit too aggressive: the upcoming release of the Processing Sound library will bundle native dlls for Windows to improve audio device support, but not for other platforms (linux, mac, arm, android) which it nevertheless supports out of the box. Based on the current behaviour, users of any platform other than Windows will be shown a disconcerting (and wrong) error message any time they run a sketch.

## Expected behaviour
There should be a way for libraries to selectively suppress Processing's 'does not run on this architecture' error message, for example by providing an optional mechanism that allows libraries to specify explicitly which OSs/platforms they support (maybe something for `library.properties`?).

I suppose the error message could already be suppressed by creating native library sub-folders for every platform/architecture and adding an empty dummy file into each. If this is deemed a sufficient solution, then it should probably be documented somewhere.

## Steps to Reproduce
On any platform/OS other than Windows, run any of the example sketches from this [current dev build of the Sound library](https://github.com/processing/processing-sound/releases/tag/windows).

**Comment by benfry** [comment]
Does it work if you just create a dummy empty folder for other architectures? (Without even placing a file inside?)

**Comment by kevinstadler** [comment]
Ah yes, the mere existence of the architecture folder (at the time of Processing startup, not at the time of running the sketch) seems to be enough to suppress the message, at least on MacOS!

**Comment by benfry** [comment]
Ok good; let's go with that. I've updated the [wiki notes](https://github.com/processing/processing4/wiki/Supported-Platforms#native-libraries) to that effect, since the solutions to handle this on the PDE are far too complicated for a situation this rare.
