### ISSUE TITLE
`PShape.getSpecular()`, `.getEmissive()`, and `.getShininess()` don't work correctly

### ISSUE THREAD

**Issue by hx2A** [benfry/processing4#781]
## Description

...but `PShape.getAmbient()` does work, which is an important clue. This is an obscure bug but don't worry, I will make a PR to fix this.

Those 3 methods return `0`, regardless of what the PShape's material settings are.

## Steps to Reproduce

Below is some code that demonstrates the problem.

```java
size(300, 300, P3D);

PShape s = createShape();
s.beginShape();
s.vertex(-100, -100, 0);
s.vertex(100, -100, 0);
s.vertex(100, 100, 0);
s.vertex(-100, 100, 0);
s.endShape(CLOSE);

s.setAmbient(color(255, 204, 15));
s.setSpecular(color(13, 52, 29));
s.setEmissive(color(30, 20, 29));
s.setShininess(3);

translate(150, 150);

lights();

shape(s);

println("AMBIENT", hex(s.getAmbient(0)));
println("SPECULAR", hex(s.getSpecular(0)));
println("EMISSIVE", hex(s.getEmissive(0)));
println("SHININESS", s.getShininess(0));
```

The current output is:

```txt
AMBIENT FFFFCC0F
SPECULAR 00000000
EMISSIVE 00000000
SHININESS 0.0
```

The expected output is:

```txt
AMBIENT FFFFCC0F
SPECULAR FF0D341D
EMISSIVE FF1E141D
SHININESS 3.0
```

## Your Environment
* Processing version: 4.3
* Operating System and OS version: Fedora Linux
* Other information:

## Possible Causes / Solutions
I see the problem and will make a PR for this.

**Comment by benfry** [comment]
Excellent, thanks! Merged for what will likely be 4.3.1 (or whatever comes after 4.3).
