### ISSUE TITLE
Running a P3D Sketch adds a keyboard layout to windows

### ISSUE THREAD

**Issue by ellie-okay** [benfry/processing4#784]
## Description
Running a P3D Sketch adds a keyboard layout to Windows. In my case, my Windows language is English (US) and my only layout is German. After running any P3D sketch, the language list in the taskbar appears with English (US), US layout added to it. 
Before:
![image](https://github.com/processing/processing4/assets/143844667/15f124de-6bbe-42d7-a230-1685402e0a72)

After running a P3D sketch: 
![image](https://github.com/processing/processing4/assets/143844667/6f7ca296-5661-4cbd-9107-5839e9139ee3)

It's unclear whether this is a windows issue or a P3D issue, but P3D certainly causes it.

## Expected Behavior
Don't add a keyboard layout.

## Current Behavior
P3D adds layout.

## Steps to Reproduce
Run any sketch that uses P3D on a Windows machine that does not use the keyboard layout associated with the system language(?). It's sadly not quite clear to me what the deciding factor is here, but I've actually encountered this problem before with other 3D programs. This happens on win 10 and win 11.
Even just this code causes it:
```processing
void setup(){
size(800, 800, P3D);
}
```

## Your Environment

* Processing version: 4.3
* Operating System and OS version: Windows 11 Pro and Windows 10
* Other information:

## Possible Causes / Solutions
Some P3D process requires/expects/adds the "default" keyboard layout to a Windows system. My current solution is running a command to remove the layout after every time I work with a P3D sketch.

**Comment by benfry** [comment]
We're not doing anything to add a keyboard layout from Processing… Especially if you're seeing this in other 3D programs, it's likely to be a problem with the drivers you're using for your video card.
