### ISSUE TITLE
Processing IDE takes an extremely long time to launch

### ISSUE THREAD

**Issue by tristanbay** [benfry/processing4#785]
## Expected Behavior
I open the application and it takes no longer than a few seconds to load the UI. I'd run the application from a terminal window to look for warnings, errors, etc. but I don't know how to do that with a Java application.

## Current Behavior
The flatpak distribution of the Processing IDE takes around 2 minutes to launch on my system, from first clicking the application icon to the IDE GUI actually appearing. Sometimes, a light gray block appears without the splash screen graphics instead of the full splash screen, and either one is there for essentially the full duration of the launch process.

## Steps to Reproduce
1. Enable Flathub repository on GNOME software application and download Processing IDE.
2. Open the application.
3. Wait up to several minutes. If the GUI still doesn't appear, restart your computer and try again.

## Your Environment
* Processing version: 4.2 (Flatpak Flathub package)
* Operating System and OS version: Fedora 38 Workstation (GNOME/Wayland)
* Other information: Running on a laptop with 16 GiB of RAM and a 12th gen Intel i5 CPU.

## Possible Causes / Solutions
May be related to translating Xorg code into Wayland. It could also have to do directly with Java.

**Comment by benfry** [comment]
I did not create, and therefore cannot support, the Flatpak release… You'll have to take it up with whoever built that.
