### ISSUE TITLE
libsoup linux video library

### ISSUE THREAD

**Issue by K0F** [benfry/processing4#787]
It may not be a Processing issue but something is not working using recent kernel and Arch-like distribution system with Video Library for Processing 4. This is what it tells me:

libsoup-ERROR **: 18:40:31.123: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.

Anyone having same issue?

Thanks,
Krystof

**Comment by benfry** [comment]
Please use the discourse board for questions and discussion: https://discourse.processing.org/ Thanks!
