### ISSUE TITLE
<!DOCTYPE html>

### ISSUE THREAD

**Issue by kkzeryri** [benfry/processing4#796]
## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by kkzeryri** [comment]
<!DOCTYPE html>の部分でエラーが発生します。
.jsが付くファイルに問題があるのでしょうか？

**Comment by benfry** [comment]
Sorry, I think you have the wrong repository.
