### ISSUE TITLE
Android SDK + emulator run

### ISSUE THREAD

**Issue by piglu** [benfry/processing4#805]
## Description
Example can't be run on android emulator

## Expected Behavior
Example must be run on android emulator

## Current Behavior
Can't run example on android emulator

## Steps to Reproduce
1. code is not the problem
2. choose Run in emulator
3. Info about SDK is not installed. Accept SDK installation. SDK installed
4. Accept licenses
5. message "The system image needed by emulator does not appear...install it now. YES
6. choose (it doesn't matter) ARM image
7. after emulator installation message is "The SDK is not properly installed". instructions bla bla

## Your Environment
* Processing version: 4.3
* Operating System and OS version: Manjaro Linux 6.1.62-1-MANJARO

## Possible Causes / Solutions
Here is complete (after i clicked on option run in emulator) log
[code]
Build folder: /tmp/android6743957359406834435sketch
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.0) was tested up to compileSdk = 32

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33
Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Checking the license for package Android Emulator in /home/dstanko/sketchbook/android/sdk/licenses
License for package Android Emulator accepted.
Preparing "Install Android Emulator (revision: 32.1.15)".
"Install Android Emulator (revision: 32.1.15)" ready.
Installing Android Emulator in /home/dstanko/sketchbook/android/sdk/emulator
"Install Android Emulator (revision: 32.1.15)" complete.
"Install Android Emulator (revision: 32.1.15)" finished.
Checking the license for package Android SDK Tools in /home/dstanko/sketchbook/android/sdk/licenses
License for package Android SDK Tools accepted.
Preparing "Install Android SDK Tools (revision: 26.1.1)".
"Install Android SDK Tools (revision: 26.1.1)" ready.
Installing Android SDK Tools in /home/dstanko/sketchbook/android/sdk/tools
"Install Android SDK Tools (revision: 26.1.1)" complete.
"Install Android SDK Tools (revision: 26.1.1)" finished.
Checking the license for package Android SDK Build-Tools 30.0.3 in /home/dstanko/sketchbook/android/sdk/licenses
License for package Android SDK Build-Tools 30.0.3 accepted.
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /home/dstanko/sketchbook/android/sdk/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Checking the license for package Android SDK Platform 33 in /home/dstanko/sketchbook/android/sdk/licenses
License for package Android SDK Platform 33 accepted.
Preparing "Install Android SDK Platform 33 (revision: 3)".
Warning: Package "com.android.repository.impl.generated.v2.RemotePackage@ca71eb40" (platforms;android-33) should be installed in 
"/home/dstanko/sketchbook/android/sdk/platforms/android-33" but 
"Android SDK Platform 33" (platforms;android-33-ext5) is already installed there.
Installing in "/home/dstanko/sketchbook/android/sdk/platforms/android-33-2" instead.
"Install Android SDK Platform 33 (revision: 3)" ready.
Installing Android SDK Platform 33 in /home/dstanko/sketchbook/android/sdk/platforms/android-33-2
"Install Android SDK Platform 33 (revision: 3)" complete.
"Install Android SDK Platform 33 (revision: 3)" finished.
Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Observed package id 'platforms;android-33' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33-2' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33')
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest
> Task :app:processDebugManifest
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:compressDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugNativeLibs NO-SOURCE
> Task :app:stripDebugDebugSymbols NO-SOURCE
> Task :app:mergeDebugJavaResource
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions
> Task :app:processDebugManifestForPackage
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac
Annotation processing got disabled, since it requires a 1.6 compliant JVM

> Task :app:dexBuilderDebug
> Task :app:desugarDebugFileDependencies
> Task :app:mergeExtDexDebug
> Task :app:mergeDexDebug
> Task :app:packageDebug
> Task :app:createDebugApkListingFileRedirect
> Task :app:assembleDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

**BUILD SUCCESSFUL in 1m 54s**
27 actionable tasks: 27 executed
**Warning: Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Warning: Observed package id 'platforms;android-33' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33-2' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33')**
Loading package information...                                                  
Loading local repository...                                                     
**Warning: Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Warning: Observed package id 'platforms;android-33' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33-2' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33')**
[                                       ] 3% Loading local repository...        
[                                       ] 3% Fetch remote repository...         
[=                                      ] 3% Fetch remote repository...         
[=                                      ] 4% Fetch remote repository...         
[=                                      ] 5% Fetch remote repository...         
[==                                     ] 5% Fetch remote repository...         
[==                                     ] 6% Fetch remote repository...         
[==                                     ] 7% Fetch remote repository...         
[==                                     ] 7% Computing updates...               
[===                                    ] 8% Computing updates...               
[===                                    ] 10% Computing updates...              
[=======================================] 100% Computing updates...             

**Output from emulator download 0
Emulator installation was successful.**
Please re-read the installation instructions for Processing<br>found in <a href="https://android.processing.org/tutorials/getting_started/index.html">this online tutorial</a>.
Loading local repository...                                                     
**Warning: Observed package id 'platforms;android-33-ext5' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33-ext5')
Warning: Observed package id 'platforms;android-33' in inconsistent location '/home/dstanko/sketchbook/android/sdk/platforms/android-33-2' (Expected '/home/dstanko/sketchbook/android/sdk/platforms/android-33')**
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
**Error: Package path is not valid. Valid system image paths are:
system-images;android-24;default;x86
null**
[/code]
Important parts are bolded in above log. I don't know if this is the problem with processing or with something in manjaro system. I d/l processing from your homepage not from repo.

Thx for reading

**Comment by benfry** [comment]
Sorry, you'll need to file this one here: https://github.com/processing/processing-android/issues
