### ISSUE TITLE
on windows the default editor font is not present

### ISSUE THREAD

**Issue by hellonearthis** [benfry/processing4#82]
## Description
I installed processing for the first time,  I had not previously installed it so had not settings file on my machine.  The default font was not on my windows system and the codes text looked like boxes.

## Expected Behavior
A readable text due to editor font being on my system

## Current Behavior
The default font was not on my windows system and the codes text looked like boxes.

## Steps to Reproduce
Install on a windows system that's never had processing installed on it.
Meaning, with no preferences files,  so default preferences are used.

## Your Environment
* Processing version: 4.0a1
* Operating System and OS version: Microsoft Windows 10 Professional Build 18363

## Possible Causes / Solutions
The default font for the windows build is trying to use a linux font that isn't available on the windows system.
Solution would be to use a font that MS windows uses.

**Comment by sampottinger** [comment]
Thank you @hellonearthis! Apologies for the delay. I will take a look into this on a fresh VM.

**Comment by sampottinger** [comment]
Hello @hellonearthis! Thank you for submitting this bug report. Unfortunately, I was unable to reproduce this issue using a fresh Windows 10 VM and the `on_demand_debugger` branch. It correctly defaults to Source Code Pro which is present on the machine. This is consistent with the Processing 3 behavior.

Can you please confirm which version of Windows you are using, which font is being selected, and which version of Processing you are running?

**Comment by hellonearthis** [comment]
OH wow, since I have installed Processing it now finds the font when I try to install in again.

I don't think Source Code Pro is a default windows font.  Defaulting to Arial might be a safer option.
https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list

Microsoft Windows 10 Professional Build 18363,  It was processing 3 but I don't know what font it was trying to use.

I will try and reproduce the bug in a couple of days as I'm busy at the moment doing virtual hackathons in New Zealand.

**Comment by sampottinger** [comment]
Thanks @hellonearthis! If it's processing 3, please file at https://github.com/processing/processing
