### ISSUE TITLE
JOGL 2.4

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#84]
It looks like the 2.4 train has reached some viable release candidates. Might be time to make the jump! Just creating this issue to track some of the efforts :)

**Comment by sampottinger** [comment]
Blocked on #73 .

**Comment by sampottinger** [comment]
Blocked on #76

**Comment by benfry** [comment]
@sampottinger is your plan to leave this open for the final 2.4, or was it just a note about updating the RC?

**Comment by sampottinger** [comment]
I'll close this and open another for a future version.
