### ISSUE TITLE
Update "no plans" on the P3 repo wiki

### ISSUE THREAD

**Issue by jeremydouglass** [benfry/processing4#86]
Currently the Processing 3 repo wiki has a page entitled "Processing 4" that opens:

"There are currently no plans to create a Processing 4.x."

https://github.com/processing/processing/wiki/Processing-4

Should that statement be modified a bit -- and perhaps with a link to this repo and a call for help?

**Comment by benfry** [comment]
Thanks; done over the weekend.

**Comment by jeremydouglass** [comment]
...odd, it still says that page hasn't been updated since Sept 12 2019...?

"There are currently no plans to create a Processing 4.x."
https://github.com/processing/processing/wiki/Processing-4

I can't see any changes in readme's either, and <strike>the processing4 repo doesn't have a visible wiki, so it isn't there</strike> -- actually, I do see the page here: https://github.com/processing/processing4/wiki/Changes-in-4.0 -- but it would be nice to update that misleading page on the old P3 repo.

Let me know if I can help.

**Comment by jeremydouglass** [comment]
I went ahead and edited the page at:
https://github.com/processing/processing/wiki/Processing-4

as follows, with a link to the new repo, deprecation warning for those page contents, and a strikeout. Happy to update if that wasn't the right thing.

> ### Work on Processing 4 is proceeding at:
> **https://github.com/processing/processing4**
> 
> The page contents below are deprecated.
> <strike>There are currently no plans to create a Processing 4.x.</strike>
